In [9]:
import sys
from pathlib import Path
sys.path.append(f"{Path().absolute().parent}")

In [10]:
import pandas as pd
from notebooks.radp_library import (preprocess_ue_data)
from apps.mobility_robustness_optimization.simple_mro import SimpleMRO

In [11]:
simple_ue = pd.read_csv('E:/Repositories/maveric/notebooks/data/sim_data/UE_data_20UE_100ticks.csv')
topology = pd.read_csv('E:/Repositories/maveric/notebooks/data/sim_data/topology.csv')
simple_ue.drop(columns=['mock_ue_id', 'tick'], inplace=True)
simple_ue

       longitude   latitude
0     -22.625309  59.806764
1     119.764151  54.857584
2      72.095437 -20.253892
3     -67.548009 -38.100941
4      59.867089 -83.103930
...          ...        ...
1995   45.564260  42.609846
1996  132.457280  17.241235
1997 -101.217659  72.295988
1998  -16.480045 -26.656397
1999   34.222834  63.970820

[2000 rows x 2 columns]

In [12]:
input_data = preprocess_ue_data(simple_ue, topology)
input_data

       longitude   latitude  ...  log_distance  cell_rxpwr_dbm
0     -22.625309  59.806764  ...     16.043691     -100.000472
1     -22.625309  59.806764  ...     16.043691     -100.000472
2     -22.625309  59.806764  ...     16.043691     -100.000472
3     119.764151  54.857584  ...     14.780124      -99.287948
4     119.764151  54.857584  ...     14.780124      -99.287948
...          ...        ...  ...           ...             ...
5995  -16.480045 -26.656397  ...     16.681342     -100.339006
5996  -16.480045 -26.656397  ...     16.681342     -100.339006
5997   34.222834  63.970820  ...     15.788136      -99.861003
5998   34.222834  63.970820  ...     15.788136      -99.861003
5999   34.222834  63.970820  ...     15.788136      -99.861003

[6000 rows x 9 columns]

In [13]:
mro = SimpleMRO(simple_ue,topology)

In [14]:
mro.train_or_update_rf_twin(simple_ue)

ValueError: The input DataFrame must contain the following columns: {'longitude', 'tick', 'latitude', 'mock_ue_id'}