In [1]:
import sys
from pathlib import Path
sys.path.append(f"{Path().absolute().parent}")

In [2]:
import pandas as pd
from notebooks.radp_library import (preprocess_ue_data)
from apps.mobility_robustness_optimization.simple_mro import SimpleMRO
from apps.mobility_robustness_optimization.mro_rl import ReinforcedMRO

In [3]:
simple_ue = pd.read_csv('E:/Repositories/maveric/notebooks/data/sim_data/UE_data_20UE_100ticks.csv')
topology = pd.read_csv('E:/Repositories/maveric/notebooks/data/sim_data/topology.csv')
topology.loc[topology["cell_id"] == "cell_1", "cell_lat"] = -90
topology.loc[topology["cell_id"] == "cell_2", "cell_lat"] = 0
topology.loc[topology["cell_id"] == "cell_3", "cell_lat"] = 90

topology.loc[topology["cell_id"] == "cell_1", "cell_lon"] = -180
topology.loc[topology["cell_id"] == "cell_2", "cell_lon"] = 0
topology.loc[topology["cell_id"] == "cell_3", "cell_lon"] = 180

topology.loc[topology["cell_id"] == "cell_1", "cell_carrier_freq_mhz"] = 2100
topology.loc[topology["cell_id"] == "cell_2", "cell_carrier_freq_mhz"] = 2100
topology.loc[topology["cell_id"] == "cell_3", "cell_carrier_freq_mhz"] = 2100

simple_ue.drop(columns=['mock_ue_id', 'tick'], inplace=True)
simple_ue

       longitude   latitude
0     -22.625309  59.806764
1     119.764151  54.857584
2      72.095437 -20.253892
3     -67.548009 -38.100941
4      59.867089 -83.103930
...          ...        ...
1995   45.564260  42.609846
1996  132.457280  17.241235
1997 -101.217659  72.295988
1998  -16.480045 -26.656397
1999   34.222834  63.970820

[2000 rows x 2 columns]

In [4]:
topology

   cell_lat  cell_lon cell_id  cell_az_deg  cell_carrier_freq_mhz
0     -90.0    -180.0  cell_1            0                   2100
1       0.0       0.0  cell_2          120                   2100
2      90.0     180.0  cell_3          240                   2100

In [5]:
params = {
    "ue_tracks_generation": {
            "params": {
                "simulation_duration": 3600,
                "simulation_time_interval_seconds": 0.01,
                "num_ticks": 100,
                "num_batches": 1,
                "ue_class_distribution": {
                    "stationary": {
                        "count": 5,
                        "velocity": 0,
                        "velocity_variance": 1
                    },
                    "pedestrian": {
                        "count": 5,
                        "velocity": 2,
                        "velocity_variance": 1
                    },
                    "cyclist": {
                        "count": 5,
                        "velocity": 5,
                        "velocity_variance": 1
                    },
                    "car": {
                        "count": 5,
                        "velocity": 20,
                        "velocity_variance": 1
                    }
                },
                "lat_lon_boundaries": {
                    "min_lat": -90,
                    "max_lat": 90,
                    "min_lon": -180,
                    "max_lon": 180
                },
                "gauss_markov_params": {
                    "alpha": 0.5,
                    "variance": 0.8,
                    "rng_seed": 42,
                    "lon_x_dims": 100,
                    "lon_y_dims": 100,
                    "// TODO": "Account for supporting the user choosing the anchor_loc and cov_around_anchor.",
                    "// Current implementation": "the UE Tracks generator will not be using these values.",
                    "// anchor_loc": {},
                    "// cov_around_anchor": {}
            }
        }
    }
}

__Start__

In [6]:
input_data = preprocess_ue_data(simple_ue, topology)
input_data

,longitude,latitude,cell_lat,cell_lon,cell_id,cell_az_deg,cell_carrier_freq_mhz,log_distance,cell_rxpwr_dbm
0,-22.625309,59.806764,-90.0,-180.0,1,0,2100,16.629500,-100.311970
1,-22.625309,59.806764,0.0,0.0,2,120,2100,15.752768,-99.841523
2,-22.625309,59.806764,90.0,180.0,3,240,2100,15.027772,-99.432278
3,119.764151,54.857584,-90.0,-180.0,1,0,2100,16.595905,-100.294405
4,119.764151,54.857584,0.0,0.0,2,120,2100,16.289273,-100.132420
...,...,...,...,...,...,...,...,...,...
5995,-16.480045,-26.656397,0.0,0.0,2,120,2100,15.054748,-99.447856
5996,-16.480045,-26.656397,90.0,180.0,3,240,2100,16.379387,-100.180339
5997,34.222834,63.970820,-90.0,-180.0,1,0,2100,16.656917,-100.326278
5998,34.222834,63.970820,0.0,0.0,2,120,2100,15.850264,-99.895116
5999,34.222834,63.970820,90.0,180.0,3,240,2100,14.879372,-99.346078

### Simple MRO

__init__

In [7]:
mro = SimpleMRO(mobility_model_params = params, topology = topology)

__update__

In [8]:
mro.train_or_update_rf_twin(input_data)

No Bayesian Digital Twins available for update. Training from scratch.

[2025-05-10 14:08:56,922] INFO:  Iter 1/100 - Loss: 0.784 (delta=inf)
[2025-05-10 14:08:57,069] INFO:  Iter 2/100 - Loss: 0.765 (delta=-0.019080)
[2025-05-10 14:08:57,228] INFO:  Iter 3/100 - Loss: 0.745 (delta=-0.019101)
[2025-05-10 14:08:57,371] INFO:  Iter 4/100 - Loss: 0.726 (delta=-0.019147)
[2025-05-10 14:08:57,518] INFO:  Iter 5/100 - Loss: 0.707 (delta=-0.019220)
[2025-05-10 14:08:57,655] INFO:  Iter 6/100 - Loss: 0.688 (delta=-0.019358)
[2025-05-10 14:08:57,787] INFO:  Iter 7/100 - Loss: 0.668 (delta=-0.019525)
[2025-05-10 14:08:57,913] INFO:  Iter 8/100 - Loss: 0.648 (delta=-0.019719)
[2025-05-10 14:08:58,045] INFO:  Iter 9/100 - Loss: 0.629 (delta=-0.019950)
[2025-05-10 14:08:58,173] INFO:  Iter 10/100 - Loss: 0.608 (delta=-0.020138)
[2025-05-10 14:08:58,299] INFO:  Iter 11/100 - Loss: 0.588 (delta=-0.020339)
[2025-05-10 14:08:58,417] INFO:  Iter 12/100 - Loss: 0.567 (delta=-0.020539)
[2025-05-10 14:08:58,545] INFO:  Iter 13/100 - Loss: 0.547 (delta=-0.020725)
[2025-05-10 14:08:58,667] INFO:  Iter 14/100 - Loss: 0.526 (delta=-0.020907)
[2025-05-10 14:08:58,795] INFO:  Iter 15/100 - Loss: 0.505 (delta=-0.021107)
[2025-05-10 14:08:58,945] INFO:  Iter 16/100 - Loss: 0.483 (delta=-0.021265)
[2025-05-10 14:08:59,064] INFO:  Iter 17/100 - Loss: 0.462 (delta=-0.021440)
[2025-05-10 14:08:59,189] INFO:  Iter 18/100 - Loss: 0.440 (delta=-0.021616)
[2025-05-10 14:08:59,312] INFO:  Iter 19/100 - Loss: 0.419 (delta=-0.021784)
[2025-05-10 14:08:59,431] INFO:  Iter 20/100 - Loss: 0.397 (delta=-0.021969)
[2025-05-10 14:08:59,548] INFO:  Iter 21/100 - Loss: 0.375 (delta=-0.022146)
[2025-05-10 14:08:59,671] INFO:  Iter 22/100 - Loss: 0.352 (delta=-0.022311)
[2025-05-10 14:08:59,867] INFO:  Iter 23/100 - Loss: 0.330 (delta=-0.022498)
[2025-05-10 14:08:59,981] INFO:  Iter 24/100 - Loss: 0.307 (delta=-0.022651)
[2025-05-10 14:09:00,103] INFO:  Iter 25/100 - Loss: 0.284 (delta=-0.022846)
[2025-05-10 14:09:00,232] INFO:  Iter 26/100 - Loss: 0.261 (delta=-0.022993)
[2025-05-10 14:09:00,353] INFO:  Iter 27/100 - Loss: 0.238 (delta=-0.023174)
[2025-05-10 14:09:00,481] INFO:  Iter 28/100 - Loss: 0.215 (delta=-0.023321)
[2025-05-10 14:09:00,607] INFO:  Iter 29/100 - Loss: 0.191 (delta=-0.023501)
[2025-05-10 14:09:00,731] INFO:  Iter 30/100 - Loss: 0.168 (delta=-0.023640)
[2025-05-10 14:09:00,853] INFO:  Iter 31/100 - Loss: 0.144 (delta=-0.023814)
[2025-05-10 14:09:00,981] INFO:  Iter 32/100 - Loss: 0.120 (delta=-0.023961)
[2025-05-10 14:09:01,104] INFO:  Iter 33/100 - Loss: 0.096 (delta=-0.024117)
[2025-05-10 14:09:01,225] INFO:  Iter 34/100 - Loss: 0.071 (delta=-0.024290)
[2025-05-10 14:09:01,355] INFO:  Iter 35/100 - Loss: 0.047 (delta=-0.024446)
[2025-05-10 14:09:01,481] INFO:  Iter 36/100 - Loss: 0.022 (delta=-0.024603)
[2025-05-10 14:09:01,604] INFO:  Iter 37/100 - Loss: -0.002 (delta=-0.024775)
[2025-05-10 14:09:01,728] INFO:  Iter 38/100 - Loss: -0.027 (delta=-0.024836)
[2025-05-10 14:09:01,847] INFO:  Iter 39/100 - Loss: -0.052 (delta=-0.025104)
[2025-05-10 14:09:01,974] INFO:  Iter 40/100 - Loss: -0.077 (delta=-0.025114)
[2025-05-10 14:09:02,097] INFO:  Iter 41/100 - Loss: -0.103 (delta=-0.025244)
[2025-05-10 14:09:02,217] INFO:  Iter 42/100 - Loss: -0.128 (delta=-0.025327)
[2025-05-10 14:09:02,340] INFO:  Iter 43/100 - Loss: -0.153 (delta=-0.025318)
[2025-05-10 14:09:02,461] INFO:  Iter 44/100 - Loss: -0.179 (delta=-0.025500)
[2025-05-10 14:09:02,584] INFO:  Iter 45/100 - Loss: -0.204 (delta=-0.025379)
[2025-05-10 14:09:02,710] INFO:  Iter 46/100 - Loss: -0.230 (delta=-0.025679)
[2025-05-10 14:09:02,839] INFO:  Iter 47/100 - Loss: -0.255 (delta=-0.025464)
[2025-05-10 14:09:02,964] INFO:  Iter 48/100 - Loss: -0.281 (delta=-0.025932)
[2025-05-10 14:09:03,086] INFO:  Iter 49/100 - Loss: -0.307 (delta=-0.025491)
[2025-05-10 14:09:03,204] INFO:  Iter 50/100 - Loss: -0.333 (delta=-0.026236)
[2025-05-10 14:09:03,329] INFO:  Iter 51/100 - Loss: -0.359 (delta=-0.026055)
[2025-05-10 14:09:03,456] INFO:  Iter 52/100 - Loss: -0.385 (delta=-0.026222)
[2025-05-10 14:09:03,574] INFO:  Iter 53/100 - Loss: -0.411 (delta=-0.025850)
[2025-05-10 14:09:03,695] INFO:  Iter 54/100 - Loss: -0.437 (delta=-0.026266)
[2025-05-10 14:09:03,822] INFO:  Iter 55/100 - Loss: -0.464 (delta=-0.026219)
[2025-05-10 14:09:03,935] INFO:  Iter 56/100 - Loss: -0.490 (delta=-0.025904)
[2025-05-10 14:09:04,059] INFO:  Iter 57/100 - Loss: -0.516 (delta=-0.026360)
[2025-05-10 14:09:04,183] INFO:  Iter 58/100 - Loss: -0.542 (delta=-0.026370)
[2025-05-10 14:09:04,310] INFO:  Iter 59/100 - Loss: -0.568 (delta=-0.026061)
[2025-05-10 14:09:04,436] INFO:  Iter 60/100 - Loss: -0.595 (delta=-0.026448)
[2025-05-10 14:09:04,558] INFO:  Iter 61/100 - Loss: -0.621 (delta=-0.026542)
[2025-05-10 14:09:04,677] INFO:  Iter 62/100 - Loss: -0.648 (delta=-0.026371)
[2025-05-10 14:09:04,802] INFO:  Iter 63/100 - Loss: -0.674 (delta=-0.026412)
[2025-05-10 14:09:04,922] INFO:  Iter 64/100 - Loss: -0.701 (delta=-0.026438)
[2025-05-10 14:09:05,052] INFO:  Iter 65/100 - Loss: -0.727 (delta=-0.026530)
[2025-05-10 14:09:05,172] INFO:  Iter 66/100 - Loss: -0.753 (delta=-0.026299)
[2025-05-10 14:09:05,294] INFO:  Iter 67/100 - Loss: -0.780 (delta=-0.026536)
[2025-05-10 14:09:05,416] INFO:  Iter 68/100 - Loss: -0.806 (delta=-0.026243)
[2025-05-10 14:09:05,545] INFO:  Iter 69/100 - Loss: -0.833 (delta=-0.026692)
[2025-05-10 14:09:05,669] INFO:  Iter 70/100 - Loss: -0.859 (delta=-0.026448)
[2025-05-10 14:09:05,795] INFO:  Iter 71/100 - Loss: -0.886 (delta=-0.026412)
[2025-05-10 14:09:05,917] INFO:  Iter 72/100 - Loss: -0.912 (delta=-0.026578)
[2025-05-10 14:09:06,043] INFO:  Iter 73/100 - Loss: -0.939 (delta=-0.026308)
[2025-05-10 14:09:06,168] INFO:  Iter 74/100 - Loss: -0.965 (delta=-0.026641)
[2025-05-10 14:09:06,290] INFO:  Iter 75/100 - Loss: -0.992 (delta=-0.026523)
[2025-05-10 14:09:06,416] INFO:  Iter 76/100 - Loss: -1.018 (delta=-0.026645)
[2025-05-10 14:09:06,538] INFO:  Iter 77/100 - Loss: -1.045 (delta=-0.026301)
[2025-05-10 14:09:06,667] INFO:  Iter 78/100 - Loss: -1.071 (delta=-0.026398)
[2025-05-10 14:09:06,791] INFO:  Iter 79/100 - Loss: -1.097 (delta=-0.026234)
[2025-05-10 14:09:06,918] INFO:  Iter 80/100 - Loss: -1.124 (delta=-0.026490)
[2025-05-10 14:09:07,047] INFO:  Iter 81/100 - Loss: -1.150 (delta=-0.026302)
[2025-05-10 14:09:07,170] INFO:  Iter 82/100 - Loss: -1.177 (delta=-0.026750)
[2025-05-10 14:09:07,297] INFO:  Iter 83/100 - Loss: -1.203 (delta=-0.026098)
[2025-05-10 14:09:07,418] INFO:  Iter 84/100 - Loss: -1.229 (delta=-0.026218)
[2025-05-10 14:09:07,545] INFO:  Iter 85/100 - Loss: -1.256 (delta=-0.026480)
[2025-05-10 14:09:07,671] INFO:  Iter 86/100 - Loss: -1.282 (delta=-0.026353)
[2025-05-10 14:09:07,797] INFO:  Iter 87/100 - Loss: -1.308 (delta=-0.026097)
[2025-05-10 14:09:07,921] INFO:  Iter 88/100 - Loss: -1.334 (delta=-0.026126)
[2025-05-10 14:09:08,047] INFO:  Iter 89/100 - Loss: -1.361 (delta=-0.026266)
[2025-05-10 14:09:08,173] INFO:  Iter 90/100 - Loss: -1.387 (delta=-0.026512)
[2025-05-10 14:09:08,298] INFO:  Iter 91/100 - Loss: -1.413 (delta=-0.026064)
[2025-05-10 14:09:08,425] INFO:  Iter 92/100 - Loss: -1.439 (delta=-0.026325)
[2025-05-10 14:09:08,542] INFO:  Iter 93/100 - Loss: -1.465 (delta=-0.025899)
[2025-05-10 14:09:08,667] INFO:  Iter 94/100 - Loss: -1.491 (delta=-0.026107)
[2025-05-10 14:09:08,781] INFO:  Iter 95/100 - Loss: -1.518 (delta=-0.026150)
[2025-05-10 14:09:08,908] INFO:  Iter 96/100 - Loss: -1.543 (delta=-0.025822)
[2025-05-10 14:09:09,032] INFO:  Iter 97/100 - Loss: nan (delta=nan)
[2025-05-10 14:09:09,159] INFO:  Iter 98/100 - Loss: -1.595 (delta=nan)
[2025-05-10 14:09:09,279] INFO:  Iter 99/100 - Loss: nan (delta=nan)
[2025-05-10 14:09:09,402] INFO:  Iter 100/100 - Loss: -1.647 (delta=nan)
[2025-05-10 14:09:09,528] INFO:  Iter 1/100 - Loss: 0.761 (delta=inf)
[2025-05-10 14:09:09,654] INFO:  Iter 2/100 - Loss: 0.743 (delta=-0.018672)
[2025-05-10 14:09:09,776] INFO:  Iter 3/100 - Loss: 0.724 (delta=-0.018733)
[2025-05-10 14:09:09,899] INFO:  Iter 4/100 - Loss: 0.705 (delta=-0.018816)
[2025-05-10 14:09:10,028] INFO:  Iter 5/100 - Loss: 0.686 (delta=-0.018946)
[2025-05-10 14:09:10,155] INFO:  Iter 6/100 - Loss: 0.667 (delta=-0.019110)
[2025-05-10 14:09:10,276] INFO:  Iter 7/100 - Loss: 0.648 (delta=-0.019293)
[2025-05-10 14:09:10,396] INFO:  Iter 8/100 - Loss: 0.628 (delta=-0.019485)
[2025-05-10 14:09:10,520] INFO:  Iter 9/100 - Loss: 0.609 (delta=-0.019704)
[2025-05-10 14:09:10,647] INFO:  Iter 10/100 - Loss: 0.589 (delta=-0.019890)
[2025-05-10 14:09:10,771] INFO:  Iter 11/100 - Loss: 0.569 (delta=-0.020107)
[2025-05-10 14:09:10,896] INFO:  Iter 12/100 - Loss: 0.548 (delta=-0.020310)
[2025-05-10 14:09:11,022] INFO:  Iter 13/100 - Loss: 0.528 (delta=-0.020505)
[2025-05-10 14:09:11,147] INFO:  Iter 14/100 - Loss: 0.507 (delta=-0.020706)
[2025-05-10 14:09:11,272] INFO:  Iter 15/100 - Loss: 0.486 (delta=-0.020885)
[2025-05-10 14:09:11,397] INFO:  Iter 16/100 - Loss: 0.465 (delta=-0.021086)
[2025-05-10 14:09:11,513] INFO:  Iter 17/100 - Loss: 0.444 (delta=-0.021264)
[2025-05-10 14:09:11,638] INFO:  Iter 18/100 - Loss: 0.422 (delta=-0.021454)
[2025-05-10 14:09:11,754] INFO:  Iter 19/100 - Loss: 0.401 (delta=-0.021638)
[2025-05-10 14:09:11,880] INFO:  Iter 20/100 - Loss: 0.379 (delta=-0.021823)
[2025-05-10 14:09:12,004] INFO:  Iter 21/100 - Loss: 0.357 (delta=-0.022007)
[2025-05-10 14:09:12,152] INFO:  Iter 22/100 - Loss: 0.335 (delta=-0.022177)
[2025-05-10 14:09:12,283] INFO:  Iter 23/100 - Loss: 0.312 (delta=-0.022357)
[2025-05-10 14:09:12,409] INFO:  Iter 24/100 - Loss: 0.290 (delta=-0.022531)
[2025-05-10 14:09:12,520] INFO:  Iter 25/100 - Loss: 0.267 (delta=-0.022706)
[2025-05-10 14:09:12,633] INFO:  Iter 26/100 - Loss: 0.244 (delta=-0.022869)
[2025-05-10 14:09:12,747] INFO:  Iter 27/100 - Loss: 0.221 (delta=-0.023042)
[2025-05-10 14:09:12,874] INFO:  Iter 28/100 - Loss: 0.198 (delta=-0.023204)
[2025-05-10 14:09:12,993] INFO:  Iter 29/100 - Loss: 0.175 (delta=-0.023361)
[2025-05-10 14:09:13,120] INFO:  Iter 30/100 - Loss: 0.151 (delta=-0.023512)
[2025-05-10 14:09:13,246] INFO:  Iter 31/100 - Loss: 0.128 (delta=-0.023664)
[2025-05-10 14:09:13,368] INFO:  Iter 32/100 - Loss: 0.104 (delta=-0.023804)
[2025-05-10 14:09:13,492] INFO:  Iter 33/100 - Loss: 0.080 (delta=-0.023951)
[2025-05-10 14:09:13,613] INFO:  Iter 34/100 - Loss: 0.056 (delta=-0.024085)
[2025-05-10 14:09:13,732] INFO:  Iter 35/100 - Loss: 0.032 (delta=-0.024210)
[2025-05-10 14:09:13,854] INFO:  Iter 36/100 - Loss: 0.007 (delta=-0.024347)
[2025-05-10 14:09:13,969] INFO:  Iter 37/100 - Loss: -0.017 (delta=-0.024462)
[2025-05-10 14:09:14,094] INFO:  Iter 38/100 - Loss: -0.042 (delta=-0.024581)
[2025-05-10 14:09:14,212] INFO:  Iter 39/100 - Loss: -0.067 (delta=-0.024700)
[2025-05-10 14:09:14,335] INFO:  Iter 40/100 - Loss: -0.091 (delta=-0.024798)
[2025-05-10 14:09:14,463] INFO:  Iter 41/100 - Loss: -0.116 (delta=-0.024906)
[2025-05-10 14:09:14,580] INFO:  Iter 42/100 - Loss: -0.141 (delta=-0.025002)
[2025-05-10 14:09:14,698] INFO:  Iter 43/100 - Loss: -0.166 (delta=-0.025105)
[2025-05-10 14:09:14,825] INFO:  Iter 44/100 - Loss: -0.192 (delta=-0.025190)
[2025-05-10 14:09:14,943] INFO:  Iter 45/100 - Loss: -0.217 (delta=-0.025282)
[2025-05-10 14:09:15,065] INFO:  Iter 46/100 - Loss: -0.242 (delta=-0.025359)
[2025-05-10 14:09:15,185] INFO:  Iter 47/100 - Loss: -0.268 (delta=-0.025431)
[2025-05-10 14:09:15,311] INFO:  Iter 48/100 - Loss: -0.293 (delta=-0.025503)
[2025-05-10 14:09:15,438] INFO:  Iter 49/100 - Loss: -0.319 (delta=-0.025593)
[2025-05-10 14:09:15,543] INFO:  Iter 50/100 - Loss: -0.344 (delta=-0.025647)
[2025-05-10 14:09:15,669] INFO:  Iter 51/100 - Loss: -0.370 (delta=-0.025702)
[2025-05-10 14:09:15,792] INFO:  Iter 52/100 - Loss: -0.396 (delta=-0.025756)
[2025-05-10 14:09:15,905] INFO:  Iter 53/100 - Loss: -0.422 (delta=-0.025822)
[2025-05-10 14:09:16,029] INFO:  Iter 54/100 - Loss: -0.448 (delta=-0.025858)
[2025-05-10 14:09:16,152] INFO:  Iter 55/100 - Loss: -0.473 (delta=-0.025922)
[2025-05-10 14:09:16,274] INFO:  Iter 56/100 - Loss: -0.499 (delta=-0.025952)
[2025-05-10 14:09:16,393] INFO:  Iter 57/100 - Loss: -0.525 (delta=-0.026000)
[2025-05-10 14:09:16,508] INFO:  Iter 58/100 - Loss: -0.551 (delta=-0.026034)
[2025-05-10 14:09:16,631] INFO:  Iter 59/100 - Loss: -0.578 (delta=-0.026090)
[2025-05-10 14:09:16,753] INFO:  Iter 60/100 - Loss: -0.604 (delta=-0.026087)
[2025-05-10 14:09:16,876] INFO:  Iter 61/100 - Loss: -0.630 (delta=-0.026140)
[2025-05-10 14:09:16,994] INFO:  Iter 62/100 - Loss: -0.656 (delta=-0.026159)
[2025-05-10 14:09:17,118] INFO:  Iter 63/100 - Loss: -0.682 (delta=-0.026213)
[2025-05-10 14:09:17,238] INFO:  Iter 64/100 - Loss: -0.708 (delta=-0.026212)
[2025-05-10 14:09:17,362] INFO:  Iter 65/100 - Loss: -0.735 (delta=-0.026259)
[2025-05-10 14:09:17,486] INFO:  Iter 66/100 - Loss: -0.761 (delta=-0.026303)
[2025-05-10 14:09:17,605] INFO:  Iter 67/100 - Loss: -0.787 (delta=-0.026315)
[2025-05-10 14:09:17,730] INFO:  Iter 68/100 - Loss: -0.814 (delta=-0.026375)
[2025-05-10 14:09:17,855] INFO:  Iter 69/100 - Loss: -0.840 (delta=-0.026411)
[2025-05-10 14:09:17,971] INFO:  Iter 70/100 - Loss: -0.866 (delta=-0.026468)
[2025-05-10 14:09:18,097] INFO:  Iter 71/100 - Loss: -0.893 (delta=-0.026490)
[2025-05-10 14:09:18,219] INFO:  Iter 72/100 - Loss: -0.919 (delta=-0.026502)
[2025-05-10 14:09:18,336] INFO:  Iter 73/100 - Loss: -0.946 (delta=-0.026474)
[2025-05-10 14:09:18,455] INFO:  Iter 74/100 - Loss: -0.972 (delta=-0.026508)
[2025-05-10 14:09:18,582] INFO:  Iter 75/100 - Loss: -0.999 (delta=-0.026337)
[2025-05-10 14:09:18,701] INFO:  Iter 76/100 - Loss: -1.025 (delta=-0.026333)
[2025-05-10 14:09:18,826] INFO:  Iter 77/100 - Loss: -1.051 (delta=-0.026363)
[2025-05-10 14:09:18,948] INFO:  Iter 78/100 - Loss: -1.078 (delta=-0.026188)
[2025-05-10 14:09:19,075] INFO:  Iter 79/100 - Loss: -1.104 (delta=-0.026357)
[2025-05-10 14:09:19,200] INFO:  Iter 80/100 - Loss: -1.130 (delta=-0.026396)
[2025-05-10 14:09:19,321] INFO:  Iter 81/100 - Loss: -1.157 (delta=-0.026452)
[2025-05-10 14:09:19,447] INFO:  Iter 82/100 - Loss: -1.183 (delta=-0.026269)
[2025-05-10 14:09:19,569] INFO:  Iter 83/100 - Loss: -1.210 (delta=-0.026386)
[2025-05-10 14:09:19,686] INFO:  Iter 84/100 - Loss: -1.236 (delta=-0.026323)
[2025-05-10 14:09:19,807] INFO:  Iter 85/100 - Loss: -1.262 (delta=-0.026305)
[2025-05-10 14:09:19,935] INFO:  Iter 86/100 - Loss: -1.289 (delta=-0.026374)
[2025-05-10 14:09:20,057] INFO:  Iter 87/100 - Loss: -1.315 (delta=-0.026170)
[2025-05-10 14:09:20,182] INFO:  Iter 88/100 - Loss: -1.341 (delta=-0.026097)
[2025-05-10 14:09:20,308] INFO:  Iter 89/100 - Loss: -1.367 (delta=-0.026110)
[2025-05-10 14:09:20,421] INFO:  Iter 90/100 - Loss: -1.393 (delta=-0.026095)
[2025-05-10 14:09:20,544] INFO:  Iter 91/100 - Loss: nan (delta=nan)
[2025-05-10 14:09:20,662] INFO:  Iter 92/100 - Loss: -1.445 (delta=nan)
[2025-05-10 14:09:20,782] INFO:  Iter 93/100 - Loss: -1.472 (delta=-0.026221)
[2025-05-10 14:09:20,904] INFO:  Iter 94/100 - Loss: -1.497 (delta=-0.025915)
[2025-05-10 14:09:21,031] INFO:  Iter 95/100 - Loss: -1.523 (delta=-0.025923)
[2025-05-10 14:09:21,148] INFO:  Iter 96/100 - Loss: nan (delta=nan)
[2025-05-10 14:09:21,264] INFO:  Iter 97/100 - Loss: nan (delta=nan)
[2025-05-10 14:09:21,378] INFO:  Iter 98/100 - Loss: nan (delta=nan)
[2025-05-10 14:09:21,506] INFO:  Iter 99/100 - Loss: nan (delta=nan)
[2025-05-10 14:09:21,631] INFO:  Iter 100/100 - Loss: nan (delta=nan)
[2025-05-10 14:09:21,763] INFO:  Iter 1/100 - Loss: 0.778 (delta=inf)
[2025-05-10 14:09:21,889] INFO:  Iter 2/100 - Loss: 0.759 (delta=-0.019060)
[2025-05-10 14:09:22,011] INFO:  Iter 3/100 - Loss: 0.740 (delta=-0.019109)
[2025-05-10 14:09:22,132] INFO:  Iter 4/100 - Loss: 0.721 (delta=-0.019170)
[2025-05-10 14:09:22,255] INFO:  Iter 5/100 - Loss: 0.702 (delta=-0.019236)
[2025-05-10 14:09:22,373] INFO:  Iter 6/100 - Loss: 0.682 (delta=-0.019358)
[2025-05-10 14:09:22,498] INFO:  Iter 7/100 - Loss: 0.663 (delta=-0.019489)
[2025-05-10 14:09:22,616] INFO:  Iter 8/100 - Loss: 0.643 (delta=-0.019668)
[2025-05-10 14:09:22,739] INFO:  Iter 9/100 - Loss: 0.623 (delta=-0.019856)
[2025-05-10 14:09:22,860] INFO:  Iter 10/100 - Loss: 0.603 (delta=-0.020075)
[2025-05-10 14:09:22,972] INFO:  Iter 11/100 - Loss: 0.583 (delta=-0.020269)
[2025-05-10 14:09:23,098] INFO:  Iter 12/100 - Loss: 0.562 (delta=-0.020482)
[2025-05-10 14:09:23,212] INFO:  Iter 13/100 - Loss: 0.542 (delta=-0.020697)
[2025-05-10 14:09:23,322] INFO:  Iter 14/100 - Loss: 0.521 (delta=-0.020866)
[2025-05-10 14:09:23,446] INFO:  Iter 15/100 - Loss: 0.500 (delta=-0.021047)
[2025-05-10 14:09:23,560] INFO:  Iter 16/100 - Loss: 0.478 (delta=-0.021247)
[2025-05-10 14:09:23,682] INFO:  Iter 17/100 - Loss: 0.457 (delta=-0.021404)
[2025-05-10 14:09:23,805] INFO:  Iter 18/100 - Loss: 0.435 (delta=-0.021590)
[2025-05-10 14:09:23,923] INFO:  Iter 19/100 - Loss: 0.414 (delta=-0.021764)
[2025-05-10 14:09:24,052] INFO:  Iter 20/100 - Loss: 0.392 (delta=-0.021926)
[2025-05-10 14:09:24,175] INFO:  Iter 21/100 - Loss: 0.370 (delta=-0.022105)
[2025-05-10 14:09:24,296] INFO:  Iter 22/100 - Loss: 0.347 (delta=-0.022270)
[2025-05-10 14:09:24,408] INFO:  Iter 23/100 - Loss: 0.325 (delta=-0.022423)
[2025-05-10 14:09:24,534] INFO:  Iter 24/100 - Loss: 0.302 (delta=-0.022622)
[2025-05-10 14:09:24,652] INFO:  Iter 25/100 - Loss: 0.280 (delta=-0.022767)
[2025-05-10 14:09:24,773] INFO:  Iter 26/100 - Loss: 0.257 (delta=-0.022943)
[2025-05-10 14:09:24,891] INFO:  Iter 27/100 - Loss: 0.234 (delta=-0.023090)
[2025-05-10 14:09:25,011] INFO:  Iter 28/100 - Loss: 0.210 (delta=-0.023255)
[2025-05-10 14:09:25,137] INFO:  Iter 29/100 - Loss: 0.187 (delta=-0.023401)
[2025-05-10 14:09:25,259] INFO:  Iter 30/100 - Loss: 0.163 (delta=-0.023559)
[2025-05-10 14:09:25,379] INFO:  Iter 31/100 - Loss: 0.140 (delta=-0.023702)
[2025-05-10 14:09:25,498] INFO:  Iter 32/100 - Loss: 0.116 (delta=-0.023848)
[2025-05-10 14:09:25,617] INFO:  Iter 33/100 - Loss: 0.092 (delta=-0.023970)
[2025-05-10 14:09:25,738] INFO:  Iter 34/100 - Loss: 0.068 (delta=-0.024116)
[2025-05-10 14:09:25,854] INFO:  Iter 35/100 - Loss: 0.043 (delta=-0.024256)
[2025-05-10 14:09:25,979] INFO:  Iter 36/100 - Loss: 0.019 (delta=-0.024360)
[2025-05-10 14:09:26,102] INFO:  Iter 37/100 - Loss: -0.005 (delta=-0.024522)
[2025-05-10 14:09:26,226] INFO:  Iter 38/100 - Loss: -0.030 (delta=-0.024618)
[2025-05-10 14:09:26,340] INFO:  Iter 39/100 - Loss: -0.055 (delta=-0.024743)
[2025-05-10 14:09:26,466] INFO:  Iter 40/100 - Loss: -0.080 (delta=-0.024851)
[2025-05-10 14:09:26,588] INFO:  Iter 41/100 - Loss: -0.105 (delta=-0.025015)
[2025-05-10 14:09:26,707] INFO:  Iter 42/100 - Loss: -0.130 (delta=-0.025096)
[2025-05-10 14:09:26,830] INFO:  Iter 43/100 - Loss: -0.155 (delta=-0.025251)
[2025-05-10 14:09:26,949] INFO:  Iter 44/100 - Loss: -0.180 (delta=-0.025392)
[2025-05-10 14:09:27,071] INFO:  Iter 45/100 - Loss: -0.206 (delta=-0.025482)
[2025-05-10 14:09:27,190] INFO:  Iter 46/100 - Loss: -0.231 (delta=-0.025500)
[2025-05-10 14:09:27,308] INFO:  Iter 47/100 - Loss: -0.257 (delta=-0.025770)
[2025-05-10 14:09:27,436] INFO:  Iter 48/100 - Loss: -0.283 (delta=-0.025720)
[2025-05-10 14:09:27,554] INFO:  Iter 49/100 - Loss: -0.309 (delta=-0.025836)
[2025-05-10 14:09:27,682] INFO:  Iter 50/100 - Loss: -0.334 (delta=-0.025773)
[2025-05-10 14:09:27,804] INFO:  Iter 51/100 - Loss: -0.360 (delta=-0.025980)
[2025-05-10 14:09:27,930] INFO:  Iter 52/100 - Loss: -0.386 (delta=-0.025927)
[2025-05-10 14:09:28,057] INFO:  Iter 53/100 - Loss: -0.412 (delta=-0.025896)
[2025-05-10 14:09:28,177] INFO:  Iter 54/100 - Loss: -0.438 (delta=-0.025849)
[2025-05-10 14:09:28,303] INFO:  Iter 55/100 - Loss: -0.464 (delta=-0.026315)
[2025-05-10 14:09:28,430] INFO:  Iter 56/100 - Loss: -0.490 (delta=-0.025770)
[2025-05-10 14:09:28,548] INFO:  Iter 57/100 - Loss: -0.517 (delta=-0.026523)
[2025-05-10 14:09:28,668] INFO:  Iter 58/100 - Loss: -0.543 (delta=-0.026188)
[2025-05-10 14:09:28,786] INFO:  Iter 59/100 - Loss: -0.569 (delta=-0.025967)

In [9]:
mro.bayesian_digital_twins

{'cell_1': <radp.digital_twin.rf.bayesian.bayesian_engine.BayesianDigitalTwin at 0x1d8490a2cd0>,
 'cell_2': <radp.digital_twin.rf.bayesian.bayesian_engine.BayesianDigitalTwin at 0x1d8255d2700>,
 'cell_3': <radp.digital_twin.rf.bayesian.bayesian_engine.BayesianDigitalTwin at 0x1d849135070>}

__solve__

In [10]:
mro.solve()

e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
e:\Repositories\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(

Epoch  Hyst           TTT    MRO Metric
-----------------------------------------
0      3.1582717095   62     99.350000
1      3.8788105877   14     99.850000
2      3.1172331095   10     100.000000
3      4.0460215430   76     99.300000
4      3.1482105634   17     99.750000
5      2.7659850041   63     99.350000
6      4.0140340921   67     99.350000
7      1.6198089543   84     99.250000
8      2.7246807445   31     99.600000
9      0.4396126301   2      99.950000
10     3.5901407516   11     100.000000
11     0.6142438519   42     99.550000
12     1.2851398145   5      100.000000
13     2.8878472879   78     99.300000
14     0.6839633563   82     99.300000
15     3.1045648162   35     99.550000
16     1.1314945183   86     99.150000
17     2.1038873008   60     99.350000
18     4.0894394660   3      100.000000
19     3.2053840459   4      100.000000
20     0.1492972897   25     99.650000
21     1.0219787213   32     99.550000
22     4.0944345965   8      100.000000
23     3.7354649919   64     99.350000
24     2.1031961562   82     99.300000
25     2.4790789275   94     99.150000
26     0.4299485178   5      99.950000
27     2.0326131282   32     99.550000
28     1.9293294664   21     99.650000
29     3.8283002821   100    99.150000
30     3.8179770178   10     100.000000
31     0.8305844050   26     99.650000
32     2.5999998298   41     99.550000
33     1.2057760234   6      100.000000
34     3.8137785050   45     99.500000
35     2.9510023447   5      100.000000
36     3.9492217687   80     99.300000
37     0.5403725763   57     99.350000
38     3.6762380270   57     99.350000
39     1.6731410705   88     99.150000
40     0.2786409185   57     99.350000
41     0.9568857077   91     99.150000
42     2.2515554493   6      100.000000
43     3.7897248022   62     99.350000
44     3.7034610284   51     99.450000
45     1.9811636417   68     99.350000
46     1.3112371569   32     99.550000
47     3.9159509095   38     99.550000
48     2.9811425071   48     99.450000
49     3.7454883050   7      100.000000
50     1.7373216887   95     99.150000
51     2.1194263426   25     99.650000
52     0.9113832495   29     99.650000
53     3.8519020646   74     99.350000
54     3.2357504566   44     99.550000
55     0.3561641097   19     99.650000
56     4.0808428596   45     99.500000
57     0.9206799405   58     99.350000
58     2.8098126285   91     99.150000
59     2.8785982473   89     99.150000
60     0.6871273100   58     99.350000
61     0.2634903241   72     99.350000
62     3.2857677460   47     99.500000
63     1.0030762743   37     99.550000
64     3.9211571657   50     99.450000
65     3.3522723433   38     99.550000
66     4.0457966838   86     99.150000
67     3.3217884444   73     99.350000
68     3.9473011399   38     99.550000
69     1.0659742540   57     99.350000
70     0.0318231176   44     99.550000
71     2.1936431406   98     99.150000
72     0.6993687066   92     99.150000
73     1.4220485349   31     99.600000
74     0.3611540963   25     99.650000
75     2.1556126210   43     99.550000
76     3.4602875152   99     99.150000
77     0.3715420092   72     99.350000
78     2.2702270482   42     99.550000
79     1.3969866188   93     99.150000
80     1.0187166124   57     99.350000
81     2.9349894307   28     99.650000
82     1.1096159538   99     99.150000
83     1.0089244027   40     99.550000
84     3.2669578203   85     99.200000
85     0.2071474602   80     99.300000
86     2.2113533708   16     99.750000
87     0.1252505383   41     99.550000
88     0.3980755658   40     99.550000
89     0.8096600400   30     99.650000
90     3.9766015168   20     99.650000
91     1.8577347500   69     99.350000
92     1.1446843786   94     99.150000
93     1.2914032081   44     99.550000
94     0.4611309539   98     99.150000
95     2.9162101564   91     99.150000
96     0.8654970393   5      100.000000
97     1.2675688521   35     99.550000
98     1.9566164124   65     99.350000
99     1.9270835472   60     99.350000

Optimized Hyst: 3.1172331095138524, Optimized TTT: 10

(3.1172331095138524, 10)

In [11]:
mro.solve()

Epoch  Hyst           TTT    MRO Metric
-----------------------------------------
0      1.7639327835   39     99.550000
1      2.6361970214   30     99.650000
2      1.9588965632   4      100.000000
3      0.9877411034   27     99.650000
4      2.4459890405   18     99.700000
5      2.8002814540   38     99.550000
6      1.1594129407   78     99.300000
7      3.9577477030   90     99.150000
8      3.3210715569   39     99.550000
9      3.9663343374   95     99.150000
10     1.4497641215   84     99.250000
11     0.4477494902   87     99.150000
12     1.4644293616   49     99.450000
13     2.4410799000   12     99.950000
14     1.7552598574   58     99.350000
15     2.4278209601   20     99.650000
16     1.9578000841   54     99.400000
17     0.4074081844   98     99.150000
18     1.9838415046   77     99.300000
19     2.9610700859   87     99.150000
20     0.0073801038   88     99.150000
21     2.5617725796   65     99.350000
22     2.1277216343   39     99.550000
23     3.2447861159   58     99.350000
24     1.3936992885   61     99.350000
25     1.1377547154   37     99.550000
26     0.1449658730   100    99.150000
27     2.3599559445   23     99.650000
28     0.7645361466   9      100.000000
29     3.7989247573   36     99.550000
30     2.5617599673   84     99.250000
31     2.1585500744   86     99.150000
32     0.0727450376   62     99.350000
33     2.6311472440   30     99.650000
34     1.9251078244   53     99.400000
35     3.1512932296   100    99.150000
36     1.0040882872   65     99.350000
37     0.6261823283   42     99.550000
38     0.6926812701   53     99.400000
39     3.9667593231   7      100.000000
40     3.5081222884   100    99.150000
41     3.7064791757   73     99.350000
42     0.8139916603   87     99.150000
43     2.7027521712   20     99.650000
44     2.9278057276   99     99.150000
45     3.7986459609   91     99.150000
46     2.8214028974   69     99.350000
47     2.2760537107   76     99.300000
48     3.7523563690   27     99.650000
49     2.5928592989   83     99.250000
50     2.7788999518   7      100.000000
51     0.6341534907   96     99.150000
52     3.9897974226   72     99.350000
53     4.0345406097   51     99.450000
54     2.7474411306   94     99.150000
55     0.8638099071   71     99.350000
56     0.0082054063   13     99.950000
57     1.1012039520   84     99.250000
58     0.5355100210   54     99.400000
59     3.0901375043   87     99.150000
60     3.9697600408   56     99.350000
61     1.2215702748   63     99.350000
62     0.1482067969   83     99.250000
63     4.1052566488   57     99.350000
64     1.8301186274   6      100.000000
65     2.4541158464   44     99.550000
66     3.8194465876   28     99.650000
67     4.0736492525   38     99.550000
68     3.4603560454   50     99.450000
69     2.3089836468   5      100.000000
70     4.2039447740   20     99.650000
71     4.2296288636   60     99.350000
72     0.9019224653   16     99.750000
73     4.1997831092   63     99.350000
74     2.5654902772   73     99.350000
75     2.3693260483   3      100.000000
76     1.4671238932   96     99.150000
77     1.7458932159   31     99.600000
78     4.0529577114   61     99.350000
79     2.5256945695   9      100.000000
80     3.4911999389   44     99.550000
81     2.0576737695   77     99.300000
82     4.1375854781   4      100.000000
83     0.9586175285   42     99.550000
84     2.1378479742   28     99.650000
85     0.9557472400   23     99.650000
86     1.3871812362   21     99.650000
87     1.9612514185   13     99.950000
88     2.5771036966   49     99.450000
89     1.5710495293   75     99.350000
90     4.2002273549   48     99.450000
91     0.6821748663   44     99.550000
92     2.1869686445   9      100.000000
93     0.8167904658   46     99.500000
94     0.2258372038   61     99.350000
95     0.4207038612   30     99.650000
96     1.8459688793   64     99.350000
97     1.7903690280   68     99.350000
98     0.8313186938   62     99.350000
99     2.7054667335   40     99.550000

Optimized Hyst: 1.95889656321369, Optimized TTT: 4

(1.95889656321369, 4)

In [12]:
mro.train_or_update_rf_twin(input_data)

ValueError: The input DataFrame must contain the following columns: {'cell_az_deg', 'cell_rxpwr_dbm', 'longitude', 'cell_lat', 'cell_lon', 'cell_carrier_freq_mhz', 'cell_id', 'latitude'}

### RL MRO

In [13]:
rl_mro = ReinforcedMRO(mobility_model_params = params, topology = topology)

In [17]:
input_data = preprocess_ue_data(simple_ue, topology)

In [19]:
rl_mro.train_or_update_rf_twin(input_data)

[2025-05-10 14:36:03,564] INFO:  Iter 1/100 - Loss: 0.784 (delta=inf)

No Bayesian Digital Twins available for update. Training from scratch.

[2025-05-10 14:36:03,728] INFO:  Iter 2/100 - Loss: 0.765 (delta=-0.019080)
[2025-05-10 14:36:03,870] INFO:  Iter 3/100 - Loss: 0.745 (delta=-0.019100)
[2025-05-10 14:36:04,012] INFO:  Iter 4/100 - Loss: 0.726 (delta=-0.019144)
[2025-05-10 14:36:04,153] INFO:  Iter 5/100 - Loss: 0.707 (delta=-0.019228)
[2025-05-10 14:36:04,296] INFO:  Iter 6/100 - Loss: 0.688 (delta=-0.019357)
[2025-05-10 14:36:04,437] INFO:  Iter 7/100 - Loss: 0.668 (delta=-0.019525)
[2025-05-10 14:36:04,573] INFO:  Iter 8/100 - Loss: 0.648 (delta=-0.019734)
[2025-05-10 14:36:04,709] INFO:  Iter 9/100 - Loss: 0.629 (delta=-0.019926)
[2025-05-10 14:36:04,864] INFO:  Iter 10/100 - Loss: 0.608 (delta=-0.020139)
[2025-05-10 14:36:05,020] INFO:  Iter 11/100 - Loss: 0.588 (delta=-0.020334)
[2025-05-10 14:36:05,160] INFO:  Iter 12/100 - Loss: 0.567 (delta=-0.020559)
[2025-05-10 14:36:05,301] INFO:  Iter 13/100 - Loss: 0.547 (delta=-0.020715)
[2025-05-10 14:36:05,452] INFO:  Iter 14/100 - Loss: 0.526 (delta=-0.020919)
[2025-05-10 14:36:05,593] INFO:  Iter 15/100 - Loss: 0.505 (delta=-0.021087)
[2025-05-10 14:36:05,736] INFO:  Iter 16/100 - Loss: 0.483 (delta=-0.021271)
[2025-05-10 14:36:05,894] INFO:  Iter 17/100 - Loss: 0.462 (delta=-0.021436)
[2025-05-10 14:36:06,044] INFO:  Iter 18/100 - Loss: 0.440 (delta=-0.021624)
[2025-05-10 14:36:06,186] INFO:  Iter 19/100 - Loss: 0.419 (delta=-0.021790)
[2025-05-10 14:36:06,331] INFO:  Iter 20/100 - Loss: 0.397 (delta=-0.021957)
[2025-05-10 14:36:06,485] INFO:  Iter 21/100 - Loss: 0.375 (delta=-0.022148)
[2025-05-10 14:36:06,634] INFO:  Iter 22/100 - Loss: 0.352 (delta=-0.022312)
[2025-05-10 14:36:06,790] INFO:  Iter 23/100 - Loss: 0.330 (delta=-0.022492)
[2025-05-10 14:36:06,947] INFO:  Iter 24/100 - Loss: 0.307 (delta=-0.022667)
[2025-05-10 14:36:07,106] INFO:  Iter 25/100 - Loss: 0.284 (delta=-0.022830)
[2025-05-10 14:36:07,262] INFO:  Iter 26/100 - Loss: 0.261 (delta=-0.023005)
[2025-05-10 14:36:07,408] INFO:  Iter 27/100 - Loss: 0.238 (delta=-0.023168)
[2025-05-10 14:36:07,551] INFO:  Iter 28/100 - Loss: 0.215 (delta=-0.023330)
[2025-05-10 14:36:07,697] INFO:  Iter 29/100 - Loss: 0.191 (delta=-0.023490)
[2025-05-10 14:36:07,833] INFO:  Iter 30/100 - Loss: 0.168 (delta=-0.023645)
[2025-05-10 14:36:07,973] INFO:  Iter 31/100 - Loss: 0.144 (delta=-0.023820)
[2025-05-10 14:36:08,120] INFO:  Iter 32/100 - Loss: 0.120 (delta=-0.023963)
[2025-05-10 14:36:08,254] INFO:  Iter 33/100 - Loss: 0.096 (delta=-0.024114)
[2025-05-10 14:36:08,402] INFO:  Iter 34/100 - Loss: 0.071 (delta=-0.024280)
[2025-05-10 14:36:08,549] INFO:  Iter 35/100 - Loss: 0.047 (delta=-0.024438)
[2025-05-10 14:36:08,678] INFO:  Iter 36/100 - Loss: 0.022 (delta=-0.024612)
[2025-05-10 14:36:08,816] INFO:  Iter 37/100 - Loss: -0.002 (delta=-0.024744)
[2025-05-10 14:36:08,957] INFO:  Iter 38/100 - Loss: -0.027 (delta=-0.024905)
[2025-05-10 14:36:09,097] INFO:  Iter 39/100 - Loss: -0.052 (delta=-0.024970)
[2025-05-10 14:36:09,232] INFO:  Iter 40/100 - Loss: -0.078 (delta=-0.025269)
[2025-05-10 14:36:09,364] INFO:  Iter 41/100 - Loss: -0.103 (delta=-0.025114)
[2025-05-10 14:36:09,500] INFO:  Iter 42/100 - Loss: -0.128 (delta=-0.025348)
[2025-05-10 14:36:09,638] INFO:  Iter 43/100 - Loss: -0.153 (delta=-0.025173)
[2025-05-10 14:36:09,773] INFO:  Iter 44/100 - Loss: -0.179 (delta=-0.025653)
[2025-05-10 14:36:09,906] INFO:  Iter 45/100 - Loss: -0.204 (delta=-0.025520)
[2025-05-10 14:36:10,036] INFO:  Iter 46/100 - Loss: -0.230 (delta=-0.025473)
[2025-05-10 14:36:10,175] INFO:  Iter 47/100 - Loss: -0.255 (delta=-0.025601)
[2025-05-10 14:36:10,312] INFO:  Iter 48/100 - Loss: -0.281 (delta=-0.025764)
[2025-05-10 14:36:10,448] INFO:  Iter 49/100 - Loss: -0.307 (delta=-0.025994)
[2025-05-10 14:36:10,579] INFO:  Iter 50/100 - Loss: -0.333 (delta=-0.025972)
[2025-05-10 14:36:10,713] INFO:  Iter 51/100 - Loss: -0.359 (delta=-0.025963)
[2025-05-10 14:36:10,851] INFO:  Iter 52/100 - Loss: -0.385 (delta=-0.025808)
[2025-05-10 14:36:11,045] INFO:  Iter 53/100 - Loss: -0.411 (delta=-0.026118)
[2025-05-10 14:36:11,184] INFO:  Iter 54/100 - Loss: -0.437 (delta=-0.026427)
[2025-05-10 14:36:11,324] INFO:  Iter 55/100 - Loss: -0.464 (delta=-0.026178)
[2025-05-10 14:36:11,460] INFO:  Iter 56/100 - Loss: -0.490 (delta=-0.026102)
[2025-05-10 14:36:11,600] INFO:  Iter 57/100 - Loss: -0.516 (delta=-0.026197)
[2025-05-10 14:36:11,735] INFO:  Iter 58/100 - Loss: -0.542 (delta=-0.026422)
[2025-05-10 14:36:11,872] INFO:  Iter 59/100 - Loss: -0.569 (delta=-0.026307)
[2025-05-10 14:36:11,999] INFO:  Iter 60/100 - Loss: -0.595 (delta=-0.026169)
[2025-05-10 14:36:12,136] INFO:  Iter 61/100 - Loss: -0.621 (delta=-0.026516)
[2025-05-10 14:36:12,273] INFO:  Iter 62/100 - Loss: -0.648 (delta=-0.026269)
[2025-05-10 14:36:12,402] INFO:  Iter 63/100 - Loss: -0.674 (delta=-0.026465)
[2025-05-10 14:36:12,537] INFO:  Iter 64/100 - Loss: -0.700 (delta=-0.026293)
[2025-05-10 14:36:12,667] INFO:  Iter 65/100 - Loss: -0.727 (delta=-0.026715)
[2025-05-10 14:36:12,801] INFO:  Iter 66/100 - Loss: -0.753 (delta=-0.026361)
[2025-05-10 14:36:12,934] INFO:  Iter 67/100 - Loss: -0.780 (delta=-0.026404)
[2025-05-10 14:36:13,072] INFO:  Iter 68/100 - Loss: -0.806 (delta=-0.026448)
[2025-05-10 14:36:13,203] INFO:  Iter 69/100 - Loss: -0.833 (delta=-0.026479)
[2025-05-10 14:36:13,341] INFO:  Iter 70/100 - Loss: -0.860 (delta=-0.026739)
[2025-05-10 14:36:13,479] INFO:  Iter 71/100 - Loss: -0.886 (delta=-0.026484)
[2025-05-10 14:36:13,622] INFO:  Iter 72/100 - Loss: -0.912 (delta=-0.026497)
[2025-05-10 14:36:13,753] INFO:  Iter 73/100 - Loss: -0.939 (delta=-0.026306)
[2025-05-10 14:36:13,891] INFO:  Iter 74/100 - Loss: -0.965 (delta=-0.026537)
[2025-05-10 14:36:14,030] INFO:  Iter 75/100 - Loss: -0.992 (delta=-0.026441)
[2025-05-10 14:36:14,171] INFO:  Iter 76/100 - Loss: -1.018 (delta=-0.026433)
[2025-05-10 14:36:14,312] INFO:  Iter 77/100 - Loss: -1.044 (delta=-0.026270)
[2025-05-10 14:36:14,484] INFO:  Iter 78/100 - Loss: -1.071 (delta=-0.026677)
[2025-05-10 14:36:14,616] INFO:  Iter 79/100 - Loss: -1.098 (delta=-0.026408)
[2025-05-10 14:36:14,753] INFO:  Iter 80/100 - Loss: -1.124 (delta=-0.026363)
[2025-05-10 14:36:14,886] INFO:  Iter 81/100 - Loss: -1.150 (delta=-0.026541)
[2025-05-10 14:36:15,022] INFO:  Iter 82/100 - Loss: -1.177 (delta=-0.026488)
[2025-05-10 14:36:15,156] INFO:  Iter 83/100 - Loss: -1.203 (delta=-0.025867)
[2025-05-10 14:36:15,295] INFO:  Iter 84/100 - Loss: -1.229 (delta=-0.026528)
[2025-05-10 14:36:15,434] INFO:  Iter 85/100 - Loss: -1.256 (delta=-0.026550)
[2025-05-10 14:36:15,573] INFO:  Iter 86/100 - Loss: -1.282 (delta=-0.026093)
[2025-05-10 14:36:15,713] INFO:  Iter 87/100 - Loss: -1.308 (delta=-0.026468)
[2025-05-10 14:36:15,849] INFO:  Iter 88/100 - Loss: -1.334 (delta=-0.025790)
[2025-05-10 14:36:15,989] INFO:  Iter 89/100 - Loss: -1.361 (delta=-0.026539)
[2025-05-10 14:36:16,128] INFO:  Iter 90/100 - Loss: -1.387 (delta=-0.026169)
[2025-05-10 14:36:16,258] INFO:  Iter 91/100 - Loss: -1.413 (delta=-0.025988)
[2025-05-10 14:36:16,394] INFO:  Iter 92/100 - Loss: -1.439 (delta=-0.026149)
[2025-05-10 14:36:16,531] INFO:  Iter 93/100 - Loss: -1.465 (delta=-0.026048)
[2025-05-10 14:36:16,665] INFO:  Iter 94/100 - Loss: -1.492 (delta=-0.026466)
[2025-05-10 14:36:16,805] INFO:  Iter 95/100 - Loss: -1.517 (delta=-0.025827)
[2025-05-10 14:36:16,941] INFO:  Iter 96/100 - Loss: -1.544 (delta=-0.026082)
[2025-05-10 14:36:17,075] INFO:  Iter 97/100 - Loss: -1.569 (delta=-0.025490)
[2025-05-10 14:36:17,212] INFO:  Iter 98/100 - Loss: nan (delta=nan)
[2025-05-10 14:36:17,355] INFO:  Iter 99/100 - Loss: nan (delta=nan)
[2025-05-10 14:36:17,491] INFO:  Iter 100/100 - Loss: -1.647 (delta=nan)
[2025-05-10 14:36:17,634] INFO:  Iter 1/100 - Loss: 0.761 (delta=inf)
[2025-05-10 14:36:17,771] INFO:  Iter 2/100 - Loss: 0.743 (delta=-0.018666)
[2025-05-10 14:36:17,908] INFO:  Iter 3/100 - Loss: 0.724 (delta=-0.018735)
[2025-05-10 14:36:18,044] INFO:  Iter 4/100 - Loss: 0.705 (delta=-0.018825)
[2025-05-10 14:36:18,182] INFO:  Iter 5/100 - Loss: 0.686 (delta=-0.018943)
[2025-05-10 14:36:18,323] INFO:  Iter 6/100 - Loss: 0.667 (delta=-0.019099)
[2025-05-10 14:36:18,463] INFO:  Iter 7/100 - Loss: 0.648 (delta=-0.019290)
[2025-05-10 14:36:18,593] INFO:  Iter 8/100 - Loss: 0.628 (delta=-0.019500)
[2025-05-10 14:36:18,721] INFO:  Iter 9/100 - Loss: 0.609 (delta=-0.019694)
[2025-05-10 14:36:18,859] INFO:  Iter 10/100 - Loss: 0.589 (delta=-0.019905)
[2025-05-10 14:36:18,996] INFO:  Iter 11/100 - Loss: 0.569 (delta=-0.020109)
[2025-05-10 14:36:19,128] INFO:  Iter 12/100 - Loss: 0.548 (delta=-0.020312)
[2025-05-10 14:36:19,268] INFO:  Iter 13/100 - Loss: 0.528 (delta=-0.020499)
[2025-05-10 14:36:19,406] INFO:  Iter 14/100 - Loss: 0.507 (delta=-0.020699)
[2025-05-10 14:36:19,540] INFO:  Iter 15/100 - Loss: 0.486 (delta=-0.020890)
[2025-05-10 14:36:19,681] INFO:  Iter 16/100 - Loss: 0.465 (delta=-0.021081)
[2025-05-10 14:36:19,816] INFO:  Iter 17/100 - Loss: 0.444 (delta=-0.021261)
[2025-05-10 14:36:19,955] INFO:  Iter 18/100 - Loss: 0.422 (delta=-0.021464)
[2025-05-10 14:36:20,100] INFO:  Iter 19/100 - Loss: 0.401 (delta=-0.021636)
[2025-05-10 14:36:20,250] INFO:  Iter 20/100 - Loss: 0.379 (delta=-0.021816)
[2025-05-10 14:36:20,392] INFO:  Iter 21/100 - Loss: 0.357 (delta=-0.022007)
[2025-05-10 14:36:20,542] INFO:  Iter 22/100 - Loss: 0.335 (delta=-0.022177)
[2025-05-10 14:36:20,692] INFO:  Iter 23/100 - Loss: 0.312 (delta=-0.022362)
[2025-05-10 14:36:20,881] INFO:  Iter 24/100 - Loss: 0.290 (delta=-0.022533)
[2025-05-10 14:36:21,028] INFO:  Iter 25/100 - Loss: 0.267 (delta=-0.022704)
[2025-05-10 14:36:21,168] INFO:  Iter 26/100 - Loss: 0.244 (delta=-0.022874)
[2025-05-10 14:36:21,306] INFO:  Iter 27/100 - Loss: 0.221 (delta=-0.023038)
[2025-05-10 14:36:21,442] INFO:  Iter 28/100 - Loss: 0.198 (delta=-0.023205)
[2025-05-10 14:36:21,603] INFO:  Iter 29/100 - Loss: 0.175 (delta=-0.023357)
[2025-05-10 14:36:21,746] INFO:  Iter 30/100 - Loss: 0.151 (delta=-0.023514)
[2025-05-10 14:36:21,878] INFO:  Iter 31/100 - Loss: 0.128 (delta=-0.023666)
[2025-05-10 14:36:22,011] INFO:  Iter 32/100 - Loss: 0.104 (delta=-0.023805)
[2025-05-10 14:36:22,146] INFO:  Iter 33/100 - Loss: 0.080 (delta=-0.023948)
[2025-05-10 14:36:22,278] INFO:  Iter 34/100 - Loss: 0.056 (delta=-0.024084)
[2025-05-10 14:36:22,409] INFO:  Iter 35/100 - Loss: 0.032 (delta=-0.024219)
[2025-05-10 14:36:22,534] INFO:  Iter 36/100 - Loss: 0.007 (delta=-0.024340)
[2025-05-10 14:36:22,651] INFO:  Iter 37/100 - Loss: -0.017 (delta=-0.024459)
[2025-05-10 14:36:22,777] INFO:  Iter 38/100 - Loss: -0.042 (delta=-0.024585)
[2025-05-10 14:36:22,901] INFO:  Iter 39/100 - Loss: -0.067 (delta=-0.024692)
[2025-05-10 14:36:23,029] INFO:  Iter 40/100 - Loss: -0.091 (delta=-0.024801)
[2025-05-10 14:36:23,155] INFO:  Iter 41/100 - Loss: -0.116 (delta=-0.024915)
[2025-05-10 14:36:23,283] INFO:  Iter 42/100 - Loss: -0.141 (delta=-0.024996)
[2025-05-10 14:36:23,410] INFO:  Iter 43/100 - Loss: -0.166 (delta=-0.025108)
[2025-05-10 14:36:23,529] INFO:  Iter 44/100 - Loss: -0.192 (delta=-0.025190)
[2025-05-10 14:36:23,655] INFO:  Iter 45/100 - Loss: -0.217 (delta=-0.025274)
[2025-05-10 14:36:23,781] INFO:  Iter 46/100 - Loss: -0.242 (delta=-0.025366)
[2025-05-10 14:36:23,902] INFO:  Iter 47/100 - Loss: -0.268 (delta=-0.025437)
[2025-05-10 14:36:24,027] INFO:  Iter 48/100 - Loss: -0.293 (delta=-0.025496)
[2025-05-10 14:36:24,148] INFO:  Iter 49/100 - Loss: -0.319 (delta=-0.025595)
[2025-05-10 14:36:24,270] INFO:  Iter 50/100 - Loss: -0.344 (delta=-0.025641)
[2025-05-10 14:36:24,387] INFO:  Iter 51/100 - Loss: -0.370 (delta=-0.025696)
[2025-05-10 14:36:24,507] INFO:  Iter 52/100 - Loss: -0.396 (delta=-0.025769)
[2025-05-10 14:36:24,625] INFO:  Iter 53/100 - Loss: -0.422 (delta=-0.025827)
[2025-05-10 14:36:24,744] INFO:  Iter 54/100 - Loss: -0.448 (delta=-0.025862)
[2025-05-10 14:36:24,869] INFO:  Iter 55/100 - Loss: -0.473 (delta=-0.025910)
[2025-05-10 14:36:24,996] INFO:  Iter 56/100 - Loss: -0.499 (delta=-0.025958)
[2025-05-10 14:36:25,112] INFO:  Iter 57/100 - Loss: -0.525 (delta=-0.025994)
[2025-05-10 14:36:25,236] INFO:  Iter 58/100 - Loss: -0.551 (delta=-0.026030)
[2025-05-10 14:36:25,355] INFO:  Iter 59/100 - Loss: -0.577 (delta=-0.026076)
[2025-05-10 14:36:25,482] INFO:  Iter 60/100 - Loss: -0.604 (delta=-0.026134)
[2025-05-10 14:36:25,598] INFO:  Iter 61/100 - Loss: -0.630 (delta=-0.026100)
[2025-05-10 14:36:25,718] INFO:  Iter 62/100 - Loss: -0.656 (delta=-0.026160)
[2025-05-10 14:36:25,840] INFO:  Iter 63/100 - Loss: -0.682 (delta=-0.026251)
[2025-05-10 14:36:25,962] INFO:  Iter 64/100 - Loss: -0.708 (delta=-0.026185)
[2025-05-10 14:36:26,079] INFO:  Iter 65/100 - Loss: -0.735 (delta=-0.026262)
[2025-05-10 14:36:26,204] INFO:  Iter 66/100 - Loss: -0.761 (delta=-0.026286)
[2025-05-10 14:36:26,326] INFO:  Iter 67/100 - Loss: -0.787 (delta=-0.026321)
[2025-05-10 14:36:26,451] INFO:  Iter 68/100 - Loss: -0.814 (delta=-0.026415)
[2025-05-10 14:36:26,574] INFO:  Iter 69/100 - Loss: -0.840 (delta=-0.026377)
[2025-05-10 14:36:26,696] INFO:  Iter 70/100 - Loss: -0.866 (delta=-0.026448)
[2025-05-10 14:36:26,815] INFO:  Iter 71/100 - Loss: -0.893 (delta=-0.026490)
[2025-05-10 14:36:26,932] INFO:  Iter 72/100 - Loss: -0.919 (delta=-0.026475)
[2025-05-10 14:36:27,058] INFO:  Iter 73/100 - Loss: -0.946 (delta=-0.026570)
[2025-05-10 14:36:27,175] INFO:  Iter 74/100 - Loss: -0.972 (delta=-0.026411)
[2025-05-10 14:36:27,299] INFO:  Iter 75/100 - Loss: -0.999 (delta=-0.026373)
[2025-05-10 14:36:27,425] INFO:  Iter 76/100 - Loss: -1.025 (delta=-0.026401)
[2025-05-10 14:36:27,548] INFO:  Iter 77/100 - Loss: -1.051 (delta=-0.026167)
[2025-05-10 14:36:27,680] INFO:  Iter 78/100 - Loss: -1.078 (delta=-0.026196)
[2025-05-10 14:36:27,804] INFO:  Iter 79/100 - Loss: -1.104 (delta=-0.026520)
[2025-05-10 14:36:27,929] INFO:  Iter 80/100 - Loss: -1.130 (delta=-0.026368)
[2025-05-10 14:36:28,054] INFO:  Iter 81/100 - Loss: -1.157 (delta=-0.026417)
[2025-05-10 14:36:28,183] INFO:  Iter 82/100 - Loss: -1.183 (delta=-0.026319)
[2025-05-10 14:36:28,308] INFO:  Iter 83/100 - Loss: -1.210 (delta=-0.026393)
[2025-05-10 14:36:28,432] INFO:  Iter 84/100 - Loss: -1.236 (delta=-0.026339)
[2025-05-10 14:36:28,557] INFO:  Iter 85/100 - Loss: -1.262 (delta=-0.026305)
[2025-05-10 14:36:28,679] INFO:  Iter 86/100 - Loss: -1.288 (delta=-0.026264)
[2025-05-10 14:36:28,798] INFO:  Iter 87/100 - Loss: -1.315 (delta=-0.026181)
[2025-05-10 14:36:28,919] INFO:  Iter 88/100 - Loss: -1.341 (delta=-0.026289)
[2025-05-10 14:36:29,048] INFO:  Iter 89/100 - Loss: -1.367 (delta=-0.026098)
[2025-05-10 14:36:29,170] INFO:  Iter 90/100 - Loss: -1.393 (delta=-0.026123)
[2025-05-10 14:36:29,297] INFO:  Iter 91/100 - Loss: nan (delta=nan)
[2025-05-10 14:36:29,432] INFO:  Iter 92/100 - Loss: -1.445 (delta=nan)
[2025-05-10 14:36:29,556] INFO:  Iter 93/100 - Loss: nan (delta=nan)
[2025-05-10 14:36:29,671] INFO:  Iter 94/100 - Loss: -1.498 (delta=nan)
[2025-05-10 14:36:29,799] INFO:  Iter 95/100 - Loss: -1.524 (delta=-0.026008)
[2025-05-10 14:36:29,923] INFO:  Iter 96/100 - Loss: -1.549 (delta=-0.025822)
[2025-05-10 14:36:30,052] INFO:  Iter 97/100 - Loss: -1.576 (delta=-0.026270)
[2025-05-10 14:36:30,227] INFO:  Iter 98/100 - Loss: -1.601 (delta=-0.025678)
[2025-05-10 14:36:30,363] INFO:  Iter 99/100 - Loss: -1.627 (delta=-0.025762)
[2025-05-10 14:36:30,491] INFO:  Iter 100/100 - Loss: nan (delta=nan)
[2025-05-10 14:36:30,629] INFO:  Iter 1/100 - Loss: 0.778 (delta=inf)
[2025-05-10 14:36:30,760] INFO:  Iter 2/100 - Loss: 0.759 (delta=-0.019064)
[2025-05-10 14:36:30,885] INFO:  Iter 3/100 - Loss: 0.740 (delta=-0.019111)
[2025-05-10 14:36:31,015] INFO:  Iter 4/100 - Loss: 0.721 (delta=-0.019166)
[2025-05-10 14:36:31,143] INFO:  Iter 5/100 - Loss: 0.702 (delta=-0.019242)
[2025-05-10 14:36:31,273] INFO:  Iter 6/100 - Loss: 0.682 (delta=-0.019349)
[2025-05-10 14:36:31,389] INFO:  Iter 7/100 - Loss: 0.663 (delta=-0.019494)
[2025-05-10 14:36:31,525] INFO:  Iter 8/100 - Loss: 0.643 (delta=-0.019663)
[2025-05-10 14:36:31,652] INFO:  Iter 9/100 - Loss: 0.623 (delta=-0.019858)
[2025-05-10 14:36:31,782] INFO:  Iter 10/100 - Loss: 0.603 (delta=-0.020067)
[2025-05-10 14:36:31,914] INFO:  Iter 11/100 - Loss: 0.583 (delta=-0.020289)
[2025-05-10 14:36:32,041] INFO:  Iter 12/100 - Loss: 0.562 (delta=-0.020470)
[2025-05-10 14:36:32,162] INFO:  Iter 13/100 - Loss: 0.542 (delta=-0.020697)
[2025-05-10 14:36:32,293] INFO:  Iter 14/100 - Loss: 0.521 (delta=-0.020872)
[2025-05-10 14:36:32,422] INFO:  Iter 15/100 - Loss: 0.500 (delta=-0.021055)
[2025-05-10 14:36:32,544] INFO:  Iter 16/100 - Loss: 0.478 (delta=-0.021235)
[2025-05-10 14:36:32,690] INFO:  Iter 17/100 - Loss: 0.457 (delta=-0.021409)
[2025-05-10 14:36:32,816] INFO:  Iter 18/100 - Loss: 0.436 (delta=-0.021577)
[2025-05-10 14:36:32,942] INFO:  Iter 19/100 - Loss: 0.414 (delta=-0.021772)
[2025-05-10 14:36:33,070] INFO:  Iter 20/100 - Loss: 0.392 (delta=-0.021928)
[2025-05-10 14:36:33,192] INFO:  Iter 21/100 - Loss: 0.370 (delta=-0.022099)
[2025-05-10 14:36:33,318] INFO:  Iter 22/100 - Loss: 0.347 (delta=-0.022265)
[2025-05-10 14:36:33,452] INFO:  Iter 23/100 - Loss: 0.325 (delta=-0.022446)
[2025-05-10 14:36:33,571] INFO:  Iter 24/100 - Loss: 0.302 (delta=-0.022610)
[2025-05-10 14:36:33,689] INFO:  Iter 25/100 - Loss: 0.280 (delta=-0.022766)
[2025-05-10 14:36:33,816] INFO:  Iter 26/100 - Loss: 0.257 (delta=-0.022935)
[2025-05-10 14:36:33,937] INFO:  Iter 27/100 - Loss: 0.234 (delta=-0.023102)
[2025-05-10 14:36:34,064] INFO:  Iter 28/100 - Loss: 0.210 (delta=-0.023246)
[2025-05-10 14:36:34,178] INFO:  Iter 29/100 - Loss: 0.187 (delta=-0.023414)
[2025-05-10 14:36:34,297] INFO:  Iter 30/100 - Loss: 0.163 (delta=-0.023557)
[2025-05-10 14:36:34,425] INFO:  Iter 31/100 - Loss: 0.140 (delta=-0.023698)
[2025-05-10 14:36:34,595] INFO:  Iter 32/100 - Loss: 0.116 (delta=-0.023844)
[2025-05-10 14:36:34,723] INFO:  Iter 33/100 - Loss: 0.092 (delta=-0.023973)
[2025-05-10 14:36:34,848] INFO:  Iter 34/100 - Loss: 0.068 (delta=-0.024117)
[2025-05-10 14:36:34,968] INFO:  Iter 35/100 - Loss: 0.043 (delta=-0.024240)
[2025-05-10 14:36:35,094] INFO:  Iter 36/100 - Loss: 0.019 (delta=-0.024362)
[2025-05-10 14:36:35,208] INFO:  Iter 37/100 - Loss: -0.005 (delta=-0.024514)
[2025-05-10 14:36:35,327] INFO:  Iter 38/100 - Loss: -0.030 (delta=-0.024635)
[2025-05-10 14:36:35,456] INFO:  Iter 39/100 - Loss: -0.055 (delta=-0.024733)
[2025-05-10 14:36:35,584] INFO:  Iter 40/100 - Loss: -0.080 (delta=-0.024885)
[2025-05-10 14:36:35,707] INFO:  Iter 41/100 - Loss: -0.105 (delta=-0.024997)
[2025-05-10 14:36:35,827] INFO:  Iter 42/100 - Loss: -0.130 (delta=-0.025110)
[2025-05-10 14:36:35,955] INFO:  Iter 43/100 - Loss: -0.155 (delta=-0.025241)
[2025-05-10 14:36:36,079] INFO:  Iter 44/100 - Loss: -0.180 (delta=-0.025373)
[2025-05-10 14:36:36,205] INFO:  Iter 45/100 - Loss: -0.206 (delta=-0.025495)
[2025-05-10 14:36:36,332] INFO:  Iter 46/100 - Loss: -0.231 (delta=-0.025582)
[2025-05-10 14:36:36,453] INFO:  Iter 47/100 - Loss: -0.257 (delta=-0.025579)
[2025-05-10 14:36:36,578] INFO:  Iter 48/100 - Loss: -0.283 (delta=-0.025861)
[2025-05-10 14:36:36,697] INFO:  Iter 49/100 - Loss: -0.309 (delta=-0.025840)
[2025-05-10 14:36:36,821] INFO:  Iter 50/100 - Loss: -0.334 (delta=-0.025719)
[2025-05-10 14:36:36,952] INFO:  Iter 51/100 - Loss: -0.360 (delta=-0.026036)
[2025-05-10 14:36:37,077] INFO:  Iter 52/100 - Loss: -0.386 (delta=-0.025752)
[2025-05-10 14:36:37,198] INFO:  Iter 53/100 - Loss: -0.412 (delta=-0.025944)
[2025-05-10 14:36:37,321] INFO:  Iter 54/100 - Loss: -0.438 (delta=-0.025768)
[2025-05-10 14:36:37,442] INFO:  Iter 55/100 - Loss: -0.465 (delta=-0.026604)
[2025-05-10 14:36:37,564] INFO:  Iter 56/100 - Loss: -0.490 (delta=-0.025811)
[2025-05-10 14:36:37,692] INFO:  Iter 57/100 - Loss: -0.517 (delta=-0.026220)
[2025-05-10 14:36:37,807] INFO:  Iter 58/100 - Loss: -0.543 (delta=-0.026280)
[2025-05-10 14:36:37,935] INFO:  Iter 59/100 - Loss: -0.569 (delta=-0.026306)
[2025-05-10 14:36:38,062] INFO:  Iter 60/100 - Loss: -0.595 (delta=-0.026309)

In [18]:
input_data

,longitude,latitude,cell_lat,cell_lon,cell_id,cell_az_deg,cell_carrier_freq_mhz,log_distance,cell_rxpwr_dbm
0,-22.625309,59.806764,-90.0,-180.0,1,0,2100,16.629500,-100.311970
1,-22.625309,59.806764,0.0,0.0,2,120,2100,15.752768,-99.841523
2,-22.625309,59.806764,90.0,180.0,3,240,2100,15.027772,-99.432278
3,119.764151,54.857584,-90.0,-180.0,1,0,2100,16.595905,-100.294405
4,119.764151,54.857584,0.0,0.0,2,120,2100,16.289273,-100.132420
...,...,...,...,...,...,...,...,...,...
5995,-16.480045,-26.656397,0.0,0.0,2,120,2100,15.054748,-99.447856
5996,-16.480045,-26.656397,90.0,180.0,3,240,2100,16.379387,-100.180339
5997,34.222834,63.970820,-90.0,-180.0,1,0,2100,16.656917,-100.326278
5998,34.222834,63.970820,0.0,0.0,2,120,2100,15.850264,-99.895116
5999,34.222834,63.970820,90.0,180.0,3,240,2100,14.879372,-99.346078

In [ ]:
rl_mro.solve()

e:\Repositories\maveric\.venv\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

Using cpu device
Episode: 1, Timestep: 1, Hyst: 0.359125, TTT: 2, Reward: 99.950000, Done: False
Episode: 1, Timestep: 2, Hyst: 1.058560, TTT: 2, Reward: 100.000000, Done: False
Episode: 1, Timestep: 3, Hyst: 1.066607, TTT: 2, Reward: 100.000000, Done: False
Episode: 1, Timestep: 4, Hyst: 0.000000, TTT: 2, Reward: 99.450000, Done: False
Episode: 1, Timestep: 5, Hyst: 0.000000, TTT: 2, Reward: 99.450000, Done: False