## Mobility Robustness Optimization (MRO)

Takes in new observation data to train or update the bayesian digital twin models. It processes the input data and updates the model to better reflect the current network conditions.

Then MRO optimizes the mobility robustness by solving the underlying problem using the trained model: finding optimal `HYST` and `TTT`. There are two solve approaches shown: 

- Simple MRO
- Reinforced MRO

In [1]:
import sys
from pathlib import Path
sys.path.append(f"{Path().absolute().parent}")

In [2]:
import pandas as pd
import numpy as np
from apps.mobility_robustness_optimization.simple_mro import SimpleMRO
from apps.mobility_robustness_optimization.mro_rl import ReinforcedMRO
from apps.mobility_robustness_optimization.mro_ml import BayesianMRO

*unzip the `data/mro_data.zip` file to get `data/mro_data/` folder*

# Showcasing **Simple MRO** Solving Approach

use the following example `topology` and `mobility_model_params` to initiate MRO.

In [3]:
topology = pd.read_csv('data/mro_data/mro_topology.csv')
topology

   cell_lat  cell_lon cell_id  cell_az_deg  cell_carrier_freq_mhz
0     -90.0    -180.0  cell_1            0                   2100
1       0.0       0.0  cell_2          120                   2100
2      90.0     180.0  cell_3          240                   2100

In [4]:
mobility_model_params = {
    "ue_tracks_generation": {
            "params": {
                "simulation_duration": 3600,
                "simulation_time_interval_seconds": 0.01,
                "num_ticks": 50,
                "num_batches": 1,
                "ue_class_distribution": {
                    "stationary": {
                        "count": 10,
                        "velocity": 0,
                        "velocity_variance": 1
                    },
                    "pedestrian": {
                        "count": 5,
                        "velocity": 2,
                        "velocity_variance": 1
                    },
                    "cyclist": {
                        "count": 5,
                        "velocity": 5,
                        "velocity_variance": 1
                    },
                    "car": {
                        "count": 12,
                        "velocity": 20,
                        "velocity_variance": 1
                    }
                },
                "lat_lon_boundaries": {
                    "min_lat": -90,
                    "max_lat": 90,
                    "min_lon": -180,
                    "max_lon": 180
                },
                "gauss_markov_params": {
                    "alpha": 0.5,
                    "variance": 0.8,
                    "rng_seed": 42,
                    "lon_x_dims": 100,
                    "lon_y_dims": 100,
                    "// TODO": "Account for supporting the user choosing the anchor_loc and cov_around_anchor.",
                    "// Current implementation": "the UE Tracks generator will not be using these values.",
                    "// anchor_loc": {},
                    "// cov_around_anchor": {}
            }
        }
    }
}

<b>Optionally,</b> use mobility model to get `alpha` of your data and set it to params.

In [5]:
# [OPTIONAL] run this cell to get alpha calculated from the data into mobility_model_params

from radp.digital_twin.mobility.param_regression import get_predicted_alpha

# 20 UEs x 50 ticks = 1000 rows
ue_data = pd.read_csv("data/mro_data/UE_data_20UE_100ticks.csv") # change this to the data you want to use
ue_data = ue_data.rename(columns={'latitude': 'lat', 'longitude': 'lon'})

# set random initial alpha
alpha0 = np.random.choice(np.arange(0, 1.1, 0.1))

alpha = get_predicted_alpha(ue_data, alpha0 = alpha0, seed = 42)

print(f"Learned alpha: {alpha:.2f}\n")

mobility_model_params["ue_tracks_generation"]["params"]["gauss_markov_params"]["alpha"] = alpha

Learned alpha: 0.50

/Users/tanzimfarhan/Desktop/Maveric/maveric/radp/digital_twin/mobility/param_regression.py:145: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  df = df.groupby("mock_ue_id").apply(calculate_distances_and_velocities)

In [ ]:
mro = SimpleMRO(mobility_model_params, topology)

In [15]:
# initially bayesian_digital_twins is empty
print(f"bayesian_digital_twins: {mro.bayesian_digital_twins}")

bayesian_digital_twins: {}

- prepare `new_data` for training/updating `bayesian_digital_twins`

    - `new_data` should have received power data in cartesian df format. required cols ['latitude', 'longitude', 'cell_id', 'cell_rxpwr_dbm']

In [6]:
# 20 UEs x 100 ticks x 3 cells cartesian = 6000 rows
ue_data_with_rxpower = pd.read_csv("data/mro_data/UE_data_with_rxpower_20UE_100ticks_train.csv") # change this to the data you want to use
input_data = ue_data_with_rxpower.copy()

input_data.head()

    longitude   latitude  cell_id  cell_rxpwr_dbm
0  -22.625309  59.806764        1     -100.311970
1  -22.625309  59.806764        2      -99.841523
2  -22.625309  59.806764        3      -99.432278
3  119.764151  54.857584        1     -100.294405
4  119.764151  54.857584        2     -100.132420

In [17]:
# train bayesian_digital_twins from scratch
mro.train_or_update_rf_twins(new_data=input_data)

[2025-07-13 21:53:05,309] INFO:  Iter 1/100 - Loss: 0.784 (delta=inf)

No Bayesian Digital Twins available for update. Training from scratch.

[2025-07-13 21:53:05,344] INFO:  Iter 2/100 - Loss: 0.765 (delta=-0.019081)
[2025-07-13 21:53:05,383] INFO:  Iter 3/100 - Loss: 0.745 (delta=-0.019100)
[2025-07-13 21:53:05,420] INFO:  Iter 4/100 - Loss: 0.726 (delta=-0.019148)
[2025-07-13 21:53:05,456] INFO:  Iter 5/100 - Loss: 0.707 (delta=-0.019222)
[2025-07-13 21:53:05,491] INFO:  Iter 6/100 - Loss: 0.688 (delta=-0.019364)
[2025-07-13 21:53:05,523] INFO:  Iter 7/100 - Loss: 0.668 (delta=-0.019518)
[2025-07-13 21:53:05,555] INFO:  Iter 8/100 - Loss: 0.648 (delta=-0.019725)
[2025-07-13 21:53:05,592] INFO:  Iter 9/100 - Loss: 0.629 (delta=-0.019932)
[2025-07-13 21:53:05,633] INFO:  Iter 10/100 - Loss: 0.608 (delta=-0.020143)
[2025-07-13 21:53:05,664] INFO:  Iter 11/100 - Loss: 0.588 (delta=-0.020348)
[2025-07-13 21:53:05,698] INFO:  Iter 12/100 - Loss: 0.567 (delta=-0.020547)
[2025-07-13 21:53:05,728] INFO:  Iter 13/100 - Loss: 0.547 (delta=-0.020700)
[2025-07-13 21:53:05,761] INFO:  Iter 14/100 - Loss: 0.526 (delta=-0.020930)
[2025-07-13 21:53:05,793] INFO:  Iter 15/100 - Loss: 0.505 (delta=-0.021092)
[2025-07-13 21:53:05,822] INFO:  Iter 16/100 - Loss: 0.483 (delta=-0.021274)
[2025-07-13 21:53:05,854] INFO:  Iter 17/100 - Loss: 0.462 (delta=-0.021440)
[2025-07-13 21:53:05,893] INFO:  Iter 18/100 - Loss: 0.440 (delta=-0.021611)
[2025-07-13 21:53:05,927] INFO:  Iter 19/100 - Loss: 0.419 (delta=-0.021793)
[2025-07-13 21:53:05,960] INFO:  Iter 20/100 - Loss: 0.397 (delta=-0.021964)
[2025-07-13 21:53:05,995] INFO:  Iter 21/100 - Loss: 0.375 (delta=-0.022138)
[2025-07-13 21:53:06,028] INFO:  Iter 22/100 - Loss: 0.352 (delta=-0.022316)
[2025-07-13 21:53:06,062] INFO:  Iter 23/100 - Loss: 0.330 (delta=-0.022494)
[2025-07-13 21:53:06,095] INFO:  Iter 24/100 - Loss: 0.307 (delta=-0.022664)
[2025-07-13 21:53:06,130] INFO:  Iter 25/100 - Loss: 0.284 (delta=-0.022833)
[2025-07-13 21:53:06,167] INFO:  Iter 26/100 - Loss: 0.261 (delta=-0.023002)
[2025-07-13 21:53:06,205] INFO:  Iter 27/100 - Loss: 0.238 (delta=-0.023176)
[2025-07-13 21:53:06,242] INFO:  Iter 28/100 - Loss: 0.215 (delta=-0.023324)
[2025-07-13 21:53:06,278] INFO:  Iter 29/100 - Loss: 0.191 (delta=-0.023489)
[2025-07-13 21:53:06,316] INFO:  Iter 30/100 - Loss: 0.168 (delta=-0.023648)
[2025-07-13 21:53:06,352] INFO:  Iter 31/100 - Loss: 0.144 (delta=-0.023812)
[2025-07-13 21:53:06,389] INFO:  Iter 32/100 - Loss: 0.120 (delta=-0.023966)
[2025-07-13 21:53:06,426] INFO:  Iter 33/100 - Loss: 0.096 (delta=-0.024102)
[2025-07-13 21:53:06,461] INFO:  Iter 34/100 - Loss: 0.071 (delta=-0.024300)
[2025-07-13 21:53:06,494] INFO:  Iter 35/100 - Loss: 0.047 (delta=-0.024453)
[2025-07-13 21:53:06,528] INFO:  Iter 36/100 - Loss: 0.022 (delta=-0.024589)
[2025-07-13 21:53:06,566] INFO:  Iter 37/100 - Loss: -0.002 (delta=-0.024718)
[2025-07-13 21:53:06,602] INFO:  Iter 38/100 - Loss: -0.027 (delta=-0.024964)
[2025-07-13 21:53:06,637] INFO:  Iter 39/100 - Loss: -0.052 (delta=-0.025047)
[2025-07-13 21:53:06,674] INFO:  Iter 40/100 - Loss: -0.077 (delta=-0.025061)
[2025-07-13 21:53:06,710] INFO:  Iter 41/100 - Loss: -0.103 (delta=-0.025266)
[2025-07-13 21:53:06,748] INFO:  Iter 42/100 - Loss: -0.128 (delta=-0.025267)
[2025-07-13 21:53:06,785] INFO:  Iter 43/100 - Loss: -0.153 (delta=-0.025359)
[2025-07-13 21:53:06,819] INFO:  Iter 44/100 - Loss: -0.179 (delta=-0.025396)
[2025-07-13 21:53:06,852] INFO:  Iter 45/100 - Loss: -0.204 (delta=-0.025528)
[2025-07-13 21:53:06,889] INFO:  Iter 46/100 - Loss: -0.230 (delta=-0.025555)
[2025-07-13 21:53:06,927] INFO:  Iter 47/100 - Loss: -0.256 (delta=-0.025735)
[2025-07-13 21:53:06,969] INFO:  Iter 48/100 - Loss: -0.281 (delta=-0.025492)
[2025-07-13 21:53:07,013] INFO:  Iter 49/100 - Loss: -0.307 (delta=-0.026089)
[2025-07-13 21:53:07,056] INFO:  Iter 50/100 - Loss: -0.333 (delta=-0.025668)
[2025-07-13 21:53:07,094] INFO:  Iter 51/100 - Loss: -0.359 (delta=-0.026211)
[2025-07-13 21:53:07,132] INFO:  Iter 52/100 - Loss: -0.385 (delta=-0.026289)
[2025-07-13 21:53:07,170] INFO:  Iter 53/100 - Loss: -0.411 (delta=-0.025977)
[2025-07-13 21:53:07,208] INFO:  Iter 54/100 - Loss: -0.437 (delta=-0.026198)
[2025-07-13 21:53:07,248] INFO:  Iter 55/100 - Loss: -0.464 (delta=-0.026130)
[2025-07-13 21:53:07,287] INFO:  Iter 56/100 - Loss: -0.490 (delta=-0.026098)
[2025-07-13 21:53:07,323] INFO:  Iter 57/100 - Loss: -0.516 (delta=-0.026220)
[2025-07-13 21:53:07,360] INFO:  Iter 58/100 - Loss: -0.542 (delta=-0.026399)
[2025-07-13 21:53:07,397] INFO:  Iter 59/100 - Loss: -0.569 (delta=-0.026288)
[2025-07-13 21:53:07,436] INFO:  Iter 60/100 - Loss: -0.595 (delta=-0.026242)
[2025-07-13 21:53:07,473] INFO:  Iter 61/100 - Loss: -0.621 (delta=-0.026498)
[2025-07-13 21:53:07,514] INFO:  Iter 62/100 - Loss: -0.648 (delta=-0.026525)
[2025-07-13 21:53:07,550] INFO:  Iter 63/100 - Loss: -0.674 (delta=-0.026393)
[2025-07-13 21:53:07,586] INFO:  Iter 64/100 - Loss: -0.701 (delta=-0.026379)
[2025-07-13 21:53:07,622] INFO:  Iter 65/100 - Loss: -0.727 (delta=-0.026389)
[2025-07-13 21:53:07,661] INFO:  Iter 66/100 - Loss: -0.753 (delta=-0.026259)
[2025-07-13 21:53:07,695] INFO:  Iter 67/100 - Loss: -0.780 (delta=-0.026506)
[2025-07-13 21:53:07,728] INFO:  Iter 68/100 - Loss: -0.806 (delta=-0.026654)
[2025-07-13 21:53:07,761] INFO:  Iter 69/100 - Loss: -0.833 (delta=-0.026331)
[2025-07-13 21:53:07,794] INFO:  Iter 70/100 - Loss: -0.859 (delta=-0.026559)
[2025-07-13 21:53:07,827] INFO:  Iter 71/100 - Loss: -0.886 (delta=-0.026662)
[2025-07-13 21:53:07,859] INFO:  Iter 72/100 - Loss: -0.912 (delta=-0.026361)
[2025-07-13 21:53:07,891] INFO:  Iter 73/100 - Loss: -0.939 (delta=-0.026344)
[2025-07-13 21:53:07,923] INFO:  Iter 74/100 - Loss: -0.965 (delta=-0.026530)
[2025-07-13 21:53:07,955] INFO:  Iter 75/100 - Loss: -0.992 (delta=-0.026674)
[2025-07-13 21:53:07,987] INFO:  Iter 76/100 - Loss: -1.018 (delta=-0.026082)
[2025-07-13 21:53:08,025] INFO:  Iter 77/100 - Loss: -1.045 (delta=-0.026582)
[2025-07-13 21:53:08,057] INFO:  Iter 78/100 - Loss: -1.071 (delta=-0.026620)
[2025-07-13 21:53:08,088] INFO:  Iter 79/100 - Loss: -1.097 (delta=-0.026189)
[2025-07-13 21:53:08,120] INFO:  Iter 80/100 - Loss: -1.124 (delta=-0.026623)
[2025-07-13 21:53:08,152] INFO:  Iter 81/100 - Loss: -1.150 (delta=-0.026464)
[2025-07-13 21:53:08,185] INFO:  Iter 82/100 - Loss: -1.177 (delta=-0.026325)
[2025-07-13 21:53:08,217] INFO:  Iter 83/100 - Loss: -1.203 (delta=-0.026257)
[2025-07-13 21:53:08,248] INFO:  Iter 84/100 - Loss: -1.229 (delta=-0.026262)
[2025-07-13 21:53:08,280] INFO:  Iter 85/100 - Loss: -1.255 (delta=-0.025885)
[2025-07-13 21:53:08,311] INFO:  Iter 86/100 - Loss: -1.282 (delta=-0.026980)
[2025-07-13 21:53:08,345] INFO:  Iter 87/100 - Loss: -1.308 (delta=-0.026053)
[2025-07-13 21:53:08,377] INFO:  Iter 88/100 - Loss: -1.334 (delta=-0.026209)
[2025-07-13 21:53:08,410] INFO:  Iter 89/100 - Loss: -1.361 (delta=-0.026461)
[2025-07-13 21:53:08,443] INFO:  Iter 90/100 - Loss: -1.387 (delta=-0.025967)
[2025-07-13 21:53:08,476] INFO:  Iter 91/100 - Loss: -1.413 (delta=-0.026222)
[2025-07-13 21:53:08,508] INFO:  Iter 92/100 - Loss: -1.439 (delta=-0.026338)
[2025-07-13 21:53:08,540] INFO:  Iter 93/100 - Loss: -1.465 (delta=-0.025934)
[2025-07-13 21:53:08,571] INFO:  Iter 94/100 - Loss: -1.492 (delta=-0.026186)
[2025-07-13 21:53:08,604] INFO:  Iter 95/100 - Loss: -1.517 (delta=-0.025889)
[2025-07-13 21:53:08,636] INFO:  Iter 96/100 - Loss: nan (delta=nan)
[2025-07-13 21:53:08,671] INFO:  Iter 97/100 - Loss: -1.569 (delta=nan)
[2025-07-13 21:53:08,709] INFO:  Iter 98/100 - Loss: -1.595 (delta=-0.026053)
[2025-07-13 21:53:08,745] INFO:  Iter 99/100 - Loss: -1.620 (delta=-0.024731)
[2025-07-13 21:53:08,787] INFO:  Iter 100/100 - Loss: -1.647 (delta=-0.026820)
[2025-07-13 21:53:08,873] INFO:  Iter 1/100 - Loss: 0.761 (delta=inf)
[2025-07-13 21:53:08,911] INFO:  Iter 2/100 - Loss: 0.743 (delta=-0.018670)
[2025-07-13 21:53:08,947] INFO:  Iter 3/100 - Loss: 0.724 (delta=-0.018729)
[2025-07-13 21:53:08,983] INFO:  Iter 4/100 - Loss: 0.705 (delta=-0.018821)
[2025-07-13 21:53:09,018] INFO:  Iter 5/100 - Loss: 0.686 (delta=-0.018946)
[2025-07-13 21:53:09,055] INFO:  Iter 6/100 - Loss: 0.667 (delta=-0.019100)
[2025-07-13 21:53:09,093] INFO:  Iter 7/100 - Loss: 0.648 (delta=-0.019296)
[2025-07-13 21:53:09,127] INFO:  Iter 8/100 - Loss: 0.628 (delta=-0.019483)
[2025-07-13 21:53:09,160] INFO:  Iter 9/100 - Loss: 0.609 (delta=-0.019711)
[2025-07-13 21:53:09,193] INFO:  Iter 10/100 - Loss: 0.589 (delta=-0.019906)
[2025-07-13 21:53:09,225] INFO:  Iter 11/100 - Loss: 0.569 (delta=-0.020106)
[2025-07-13 21:53:09,261] INFO:  Iter 12/100 - Loss: 0.548 (delta=-0.020301)
[2025-07-13 21:53:09,300] INFO:  Iter 13/100 - Loss: 0.528 (delta=-0.020509)
[2025-07-13 21:53:09,337] INFO:  Iter 14/100 - Loss: 0.507 (delta=-0.020698)
[2025-07-13 21:53:09,375] INFO:  Iter 15/100 - Loss: 0.486 (delta=-0.020881)
[2025-07-13 21:53:09,412] INFO:  Iter 16/100 - Loss: 0.465 (delta=-0.021084)
[2025-07-13 21:53:09,449] INFO:  Iter 17/100 - Loss: 0.444 (delta=-0.021271)
[2025-07-13 21:53:09,485] INFO:  Iter 18/100 - Loss: 0.422 (delta=-0.021455)
[2025-07-13 21:53:09,524] INFO:  Iter 19/100 - Loss: 0.401 (delta=-0.021642)
[2025-07-13 21:53:09,592] INFO:  Iter 20/100 - Loss: 0.379 (delta=-0.021816)
[2025-07-13 21:53:09,623] INFO:  Iter 21/100 - Loss: 0.357 (delta=-0.022001)
[2025-07-13 21:53:09,654] INFO:  Iter 22/100 - Loss: 0.335 (delta=-0.022184)
[2025-07-13 21:53:09,688] INFO:  Iter 23/100 - Loss: 0.312 (delta=-0.022360)
[2025-07-13 21:53:09,720] INFO:  Iter 24/100 - Loss: 0.290 (delta=-0.022530)
[2025-07-13 21:53:09,753] INFO:  Iter 25/100 - Loss: 0.267 (delta=-0.022707)
[2025-07-13 21:53:09,785] INFO:  Iter 26/100 - Loss: 0.244 (delta=-0.022876)
[2025-07-13 21:53:09,818] INFO:  Iter 27/100 - Loss: 0.221 (delta=-0.023038)
[2025-07-13 21:53:09,850] INFO:  Iter 28/100 - Loss: 0.198 (delta=-0.023199)
[2025-07-13 21:53:09,881] INFO:  Iter 29/100 - Loss: 0.175 (delta=-0.023361)
[2025-07-13 21:53:09,912] INFO:  Iter 30/100 - Loss: 0.151 (delta=-0.023513)
[2025-07-13 21:53:09,944] INFO:  Iter 31/100 - Loss: 0.128 (delta=-0.023664)
[2025-07-13 21:53:09,976] INFO:  Iter 32/100 - Loss: 0.104 (delta=-0.023806)
[2025-07-13 21:53:10,008] INFO:  Iter 33/100 - Loss: 0.080 (delta=-0.023947)
[2025-07-13 21:53:10,042] INFO:  Iter 34/100 - Loss: 0.056 (delta=-0.024084)
[2025-07-13 21:53:10,076] INFO:  Iter 35/100 - Loss: 0.032 (delta=-0.024215)
[2025-07-13 21:53:10,111] INFO:  Iter 36/100 - Loss: 0.007 (delta=-0.024344)
[2025-07-13 21:53:10,147] INFO:  Iter 37/100 - Loss: -0.017 (delta=-0.024462)
[2025-07-13 21:53:10,181] INFO:  Iter 38/100 - Loss: -0.042 (delta=-0.024582)
[2025-07-13 21:53:10,215] INFO:  Iter 39/100 - Loss: -0.067 (delta=-0.024697)
[2025-07-13 21:53:10,249] INFO:  Iter 40/100 - Loss: -0.091 (delta=-0.024795)
[2025-07-13 21:53:10,284] INFO:  Iter 41/100 - Loss: -0.116 (delta=-0.024915)
[2025-07-13 21:53:10,316] INFO:  Iter 42/100 - Loss: -0.141 (delta=-0.025001)
[2025-07-13 21:53:10,349] INFO:  Iter 43/100 - Loss: -0.166 (delta=-0.025103)
[2025-07-13 21:53:10,379] INFO:  Iter 44/100 - Loss: -0.192 (delta=-0.025191)
[2025-07-13 21:53:10,410] INFO:  Iter 45/100 - Loss: -0.217 (delta=-0.025281)
[2025-07-13 21:53:10,442] INFO:  Iter 46/100 - Loss: -0.242 (delta=-0.025356)
[2025-07-13 21:53:10,471] INFO:  Iter 47/100 - Loss: -0.268 (delta=-0.025435)
[2025-07-13 21:53:10,502] INFO:  Iter 48/100 - Loss: -0.293 (delta=-0.025504)
[2025-07-13 21:53:10,534] INFO:  Iter 49/100 - Loss: -0.319 (delta=-0.025589)
[2025-07-13 21:53:10,566] INFO:  Iter 50/100 - Loss: -0.344 (delta=-0.025645)
[2025-07-13 21:53:10,600] INFO:  Iter 51/100 - Loss: -0.370 (delta=-0.025695)
[2025-07-13 21:53:10,635] INFO:  Iter 52/100 - Loss: -0.396 (delta=-0.025764)
[2025-07-13 21:53:10,670] INFO:  Iter 53/100 - Loss: -0.422 (delta=-0.025820)
[2025-07-13 21:53:10,704] INFO:  Iter 54/100 - Loss: -0.448 (delta=-0.025856)
[2025-07-13 21:53:10,741] INFO:  Iter 55/100 - Loss: -0.473 (delta=-0.025927)
[2025-07-13 21:53:10,774] INFO:  Iter 56/100 - Loss: -0.499 (delta=-0.025956)
[2025-07-13 21:53:10,804] INFO:  Iter 57/100 - Loss: -0.525 (delta=-0.026000)
[2025-07-13 21:53:10,835] INFO:  Iter 58/100 - Loss: -0.551 (delta=-0.026035)
[2025-07-13 21:53:10,867] INFO:  Iter 59/100 - Loss: -0.577 (delta=-0.026067)
[2025-07-13 21:53:10,898] INFO:  Iter 60/100 - Loss: -0.604 (delta=-0.026105)
[2025-07-13 21:53:10,928] INFO:  Iter 61/100 - Loss: -0.630 (delta=-0.026140)
[2025-07-13 21:53:10,959] INFO:  Iter 62/100 - Loss: -0.656 (delta=-0.026166)
[2025-07-13 21:53:10,991] INFO:  Iter 63/100 - Loss: -0.682 (delta=-0.026186)
[2025-07-13 21:53:11,020] INFO:  Iter 64/100 - Loss: -0.708 (delta=-0.026233)
[2025-07-13 21:53:11,052] INFO:  Iter 65/100 - Loss: -0.735 (delta=-0.026253)
[2025-07-13 21:53:11,083] INFO:  Iter 66/100 - Loss: -0.761 (delta=-0.026310)
[2025-07-13 21:53:11,113] INFO:  Iter 67/100 - Loss: -0.787 (delta=-0.026315)
[2025-07-13 21:53:11,144] INFO:  Iter 68/100 - Loss: -0.814 (delta=-0.026376)
[2025-07-13 21:53:11,176] INFO:  Iter 69/100 - Loss: -0.840 (delta=-0.026371)
[2025-07-13 21:53:11,206] INFO:  Iter 70/100 - Loss: -0.866 (delta=-0.026489)
[2025-07-13 21:53:11,237] INFO:  Iter 71/100 - Loss: -0.893 (delta=-0.026496)
[2025-07-13 21:53:11,269] INFO:  Iter 72/100 - Loss: -0.919 (delta=-0.026529)
[2025-07-13 21:53:11,300] INFO:  Iter 73/100 - Loss: -0.946 (delta=-0.026462)
[2025-07-13 21:53:11,330] INFO:  Iter 74/100 - Loss: -0.972 (delta=-0.026501)
[2025-07-13 21:53:11,360] INFO:  Iter 75/100 - Loss: -0.999 (delta=-0.026363)
[2025-07-13 21:53:11,392] INFO:  Iter 76/100 - Loss: -1.025 (delta=-0.026346)
[2025-07-13 21:53:11,422] INFO:  Iter 77/100 - Loss: -1.052 (delta=-0.026374)
[2025-07-13 21:53:11,453] INFO:  Iter 78/100 - Loss: -1.078 (delta=-0.026093)
[2025-07-13 21:53:11,484] INFO:  Iter 79/100 - Loss: -1.104 (delta=-0.026338)
[2025-07-13 21:53:11,514] INFO:  Iter 80/100 - Loss: -1.130 (delta=-0.026517)
[2025-07-13 21:53:11,544] INFO:  Iter 81/100 - Loss: -1.157 (delta=-0.026047)
[2025-07-13 21:53:11,575] INFO:  Iter 82/100 - Loss: -1.183 (delta=-0.026560)
[2025-07-13 21:53:11,606] INFO:  Iter 83/100 - Loss: -1.210 (delta=-0.026486)
[2025-07-13 21:53:11,637] INFO:  Iter 84/100 - Loss: -1.236 (delta=-0.026333)
[2025-07-13 21:53:11,668] INFO:  Iter 85/100 - Loss: -1.262 (delta=-0.026343)
[2025-07-13 21:53:11,700] INFO:  Iter 86/100 - Loss: -1.288 (delta=-0.026187)
[2025-07-13 21:53:11,729] INFO:  Iter 87/100 - Loss: -1.315 (delta=-0.026204)
[2025-07-13 21:53:11,760] INFO:  Iter 88/100 - Loss: -1.341 (delta=-0.026208)
[2025-07-13 21:53:11,792] INFO:  Iter 89/100 - Loss: -1.367 (delta=-0.026169)
[2025-07-13 21:53:11,822] INFO:  Iter 90/100 - Loss: -1.393 (delta=-0.026138)
[2025-07-13 21:53:11,853] INFO:  Iter 91/100 - Loss: -1.419 (delta=-0.026133)
[2025-07-13 21:53:11,884] INFO:  Iter 92/100 - Loss: -1.445 (delta=-0.026083)
[2025-07-13 21:53:11,915] INFO:  Iter 93/100 - Loss: -1.471 (delta=-0.026142)
[2025-07-13 21:53:11,946] INFO:  Iter 94/100 - Loss: nan (delta=nan)
[2025-07-13 21:53:11,976] INFO:  Iter 95/100 - Loss: nan (delta=nan)
[2025-07-13 21:53:12,009] INFO:  Iter 96/100 - Loss: -1.550 (delta=nan)
[2025-07-13 21:53:12,038] INFO:  Iter 97/100 - Loss: nan (delta=nan)
[2025-07-13 21:53:12,069] INFO:  Iter 98/100 - Loss: nan (delta=nan)
[2025-07-13 21:53:12,100] INFO:  Iter 99/100 - Loss: nan (delta=nan)
[2025-07-13 21:53:12,131] INFO:  Iter 100/100 - Loss: -1.653 (delta=nan)
[2025-07-13 21:53:12,166] INFO:  Iter 1/100 - Loss: 0.778 (delta=inf)
[2025-07-13 21:53:12,196] INFO:  Iter 2/100 - Loss: 0.759 (delta=-0.019063)
[2025-07-13 21:53:12,226] INFO:  Iter 3/100 - Loss: 0.740 (delta=-0.019111)
[2025-07-13 21:53:12,257] INFO:  Iter 4/100 - Loss: 0.721 (delta=-0.019164)
[2025-07-13 21:53:12,288] INFO:  Iter 5/100 - Loss: 0.702 (delta=-0.019242)
[2025-07-13 21:53:12,318] INFO:  Iter 6/100 - Loss: 0.682 (delta=-0.019352)
[2025-07-13 21:53:12,350] INFO:  Iter 7/100 - Loss: 0.663 (delta=-0.019491)
[2025-07-13 21:53:12,379] INFO:  Iter 8/100 - Loss: 0.643 (delta=-0.019670)
[2025-07-13 21:53:12,411] INFO:  Iter 9/100 - Loss: 0.623 (delta=-0.019872)
[2025-07-13 21:53:12,442] INFO:  Iter 10/100 - Loss: 0.603 (delta=-0.020052)
[2025-07-13 21:53:12,471] INFO:  Iter 11/100 - Loss: 0.583 (delta=-0.020297)
[2025-07-13 21:53:12,502] INFO:  Iter 12/100 - Loss: 0.562 (delta=-0.020469)
[2025-07-13 21:53:12,533] INFO:  Iter 13/100 - Loss: 0.542 (delta=-0.020677)
[2025-07-13 21:53:12,563] INFO:  Iter 14/100 - Loss: 0.521 (delta=-0.020875)
[2025-07-13 21:53:12,594] INFO:  Iter 15/100 - Loss: 0.500 (delta=-0.021049)
[2025-07-13 21:53:12,625] INFO:  Iter 16/100 - Loss: 0.478 (delta=-0.021241)
[2025-07-13 21:53:12,654] INFO:  Iter 17/100 - Loss: 0.457 (delta=-0.021409)
[2025-07-13 21:53:12,685] INFO:  Iter 18/100 - Loss: 0.435 (delta=-0.021592)
[2025-07-13 21:53:12,715] INFO:  Iter 19/100 - Loss: 0.414 (delta=-0.021764)
[2025-07-13 21:53:12,745] INFO:  Iter 20/100 - Loss: 0.392 (delta=-0.021922)
[2025-07-13 21:53:12,776] INFO:  Iter 21/100 - Loss: 0.370 (delta=-0.022105)
[2025-07-13 21:53:12,806] INFO:  Iter 22/100 - Loss: 0.347 (delta=-0.022271)
[2025-07-13 21:53:12,836] INFO:  Iter 23/100 - Loss: 0.325 (delta=-0.022442)
[2025-07-13 21:53:12,867] INFO:  Iter 24/100 - Loss: 0.302 (delta=-0.022606)
[2025-07-13 21:53:12,897] INFO:  Iter 25/100 - Loss: 0.280 (delta=-0.022771)
[2025-07-13 21:53:12,927] INFO:  Iter 26/100 - Loss: 0.257 (delta=-0.022937)
[2025-07-13 21:53:12,958] INFO:  Iter 27/100 - Loss: 0.234 (delta=-0.023085)
[2025-07-13 21:53:12,988] INFO:  Iter 28/100 - Loss: 0.210 (delta=-0.023256)
[2025-07-13 21:53:13,019] INFO:  Iter 29/100 - Loss: 0.187 (delta=-0.023419)
[2025-07-13 21:53:13,050] INFO:  Iter 30/100 - Loss: 0.163 (delta=-0.023544)
[2025-07-13 21:53:13,081] INFO:  Iter 31/100 - Loss: 0.140 (delta=-0.023705)
[2025-07-13 21:53:13,114] INFO:  Iter 32/100 - Loss: 0.116 (delta=-0.023843)
[2025-07-13 21:53:13,148] INFO:  Iter 33/100 - Loss: 0.092 (delta=-0.023985)
[2025-07-13 21:53:13,184] INFO:  Iter 34/100 - Loss: 0.068 (delta=-0.024121)
[2025-07-13 21:53:13,220] INFO:  Iter 35/100 - Loss: 0.043 (delta=-0.024234)
[2025-07-13 21:53:13,256] INFO:  Iter 36/100 - Loss: 0.019 (delta=-0.024376)
[2025-07-13 21:53:13,294] INFO:  Iter 37/100 - Loss: -0.005 (delta=-0.024498)
[2025-07-13 21:53:13,331] INFO:  Iter 38/100 - Loss: -0.030 (delta=-0.024625)
[2025-07-13 21:53:13,369] INFO:  Iter 39/100 - Loss: -0.055 (delta=-0.024754)
[2025-07-13 21:53:13,406] INFO:  Iter 40/100 - Loss: -0.080 (delta=-0.024865)
[2025-07-13 21:53:13,442] INFO:  Iter 41/100 - Loss: -0.105 (delta=-0.025014)
[2025-07-13 21:53:13,478] INFO:  Iter 42/100 - Loss: -0.130 (delta=-0.025120)
[2025-07-13 21:53:13,513] INFO:  Iter 43/100 - Loss: -0.155 (delta=-0.025228)
[2025-07-13 21:53:13,548] INFO:  Iter 44/100 - Loss: -0.180 (delta=-0.025391)
[2025-07-13 21:53:13,585] INFO:  Iter 45/100 - Loss: -0.206 (delta=-0.025437)
[2025-07-13 21:53:13,623] INFO:  Iter 46/100 - Loss: -0.231 (delta=-0.025643)
[2025-07-13 21:53:13,659] INFO:  Iter 47/100 - Loss: -0.257 (delta=-0.025644)
[2025-07-13 21:53:13,692] INFO:  Iter 48/100 - Loss: -0.283 (delta=-0.025760)
[2025-07-13 21:53:13,727] INFO:  Iter 49/100 - Loss: -0.309 (delta=-0.025863)
[2025-07-13 21:53:13,762] INFO:  Iter 50/100 - Loss: -0.335 (delta=-0.025869)
[2025-07-13 21:53:13,796] INFO:  Iter 51/100 - Loss: -0.360 (delta=-0.025685)
[2025-07-13 21:53:13,828] INFO:  Iter 52/100 - Loss: -0.386 (delta=-0.026022)
[2025-07-13 21:53:13,859] INFO:  Iter 53/100 - Loss: -0.412 (delta=-0.025806)
[2025-07-13 21:53:13,891] INFO:  Iter 54/100 - Loss: -0.438 (delta=-0.026162)
[2025-07-13 21:53:13,924] INFO:  Iter 55/100 - Loss: -0.464 (delta=-0.025988)
[2025-07-13 21:53:13,959] INFO:  Iter 56/100 - Loss: -0.490 (delta=-0.026151)
[2025-07-13 21:53:13,997] INFO:  Iter 57/100 - Loss: -0.516 (delta=-0.026016)
[2025-07-13 21:53:14,075] INFO:  Iter 58/100 - Loss: -0.543 (delta=-0.026437)
[2025-07-13 21:53:14,116] INFO:  Iter 59/100 - Loss: -0.569 (delta=-0.026216)
[2025-07-13 21:53:14,153] INFO:  Iter 60/100 - Loss: -0.595 (delta=-0.026313)

Bayesian Digital Twins trained successfully.

In [ ]:
mro.bayesian_digital_twins # bayesian_digital_twins is trained for each cell_id

can save trained/updated `bayesian_digital_twins`

In [ ]:
saving_dir_relative_path = "data/mro_data/"

mro.save_bdt(saving_dir_relative_path) # True indicates save is successful

call `solve()` method to get optimized `HYST` and `TTT`

In [ ]:
# adjust n_epochs for better performance
hyst, ttt = mro.solve(n_epochs=100)

In [ ]:
from notebooks.radp_library import mro_plot_scatter, plot_sinr_db_by_ue, mro_score_3d_plot
from radp.digital_twin.utils.constants import RLF_THRESHOLD
from radp.digital_twin.utils.cell_selection import perform_attachment_hyst_ttt

attached_df = perform_attachment_hyst_ttt(mro.simulation_data, hyst, ttt, RLF_THRESHOLD)
mro_plot_scatter(attached_df, topology)

In [ ]:
mro_score_3d_plot(mro.score)

In [ ]:
ue_id = 0 # change this to the UE you want to plot
plot_sinr_db_by_ue(attached_df, mro.simulation_data, ue_id)

can load this `bayesian_digital_twins` later when needed

In [ ]:
mro.bayesian_digital_twins = {} # bayesian_digital_twins is empty again

pkl_file_path = "data/mro_data/digital_twins.pkl"
mro.load_bdt(pkl_file_path) # True indicates load is successful

In [ ]:
# Dummy solve call to avoid fantasy observation error: ensuring all test independent caches exist
mro.solve(n_epochs=2)

let's try updating the `bayesian_digital_twins` with new observations

In [ ]:
# 20 UEs x 100 ticks x 3 cells cartesian = 6000 rows
new_obeservations = pd.read_csv("data/mro_data/UE_data_with_rxpower_20UE_100ticks_update.csv") # change this to the data you want to use
input_data = new_obeservations.copy()

input_data.head()

In [ ]:
# update bdt with new observations, calling train_or_update_rf_twin() again
mro.train_or_update_rf_twins(input_data)

can solve with updated `bayesian_digital_twins`

In [ ]:
# adjust n_epochs for better performance
mro.solve(n_epochs=100)

# Showcasing **Reinforced MRO** Solving Approach

use the following example `topology` and `mobility_model_params` to initiate MRO.

In [ ]:
rl_mro = ReinforcedMRO(mobility_model_params, topology)

In [ ]:
print(f"bayesian_digital_twins: {rl_mro.bayesian_digital_twins}", end='\n\n') # bayesian_digital_twins is empty initially

pkl_file_path = "data/mro_data/digital_twins.pkl" # run previous section to have this file
rl_mro.load_bdt(pkl_file_path) # True indicates load is successful

In [ ]:
rl_mro.bayesian_digital_twins

- load `new_data` for training/updating `bayesian_digital_twins`

    - `new_data` should have received power data in cartesian df format. required cols ['latitude', 'longitude', 'cell_id', 'cell_rxpwr_dbm']

In [ ]:
# 20 UEs x 50 ticks x 3 cells cartesian = 3000 rows
ue_data_with_rxpower = pd.read_csv("data/mro_data/UE_data_with_rxpower_20UE_50ticks.csv")
input_data = ue_data_with_rxpower.copy()

input_data

In [ ]:
# Dummy solve call to avoid fantasy observation error: ensuring all test independent caches exist
rl_mro.solve(total_timesteps=2)

In [ ]:
# update bdt with new data
rl_mro.train_or_update_rf_twins(input_data)

Solve using updated `bayesian_digital_twins`

In [ ]:
# adjust total_timesteps for better performance
hyst, ttt = rl_mro.solve(total_timesteps=100)

In [ ]:
attached_df = perform_attachment_hyst_ttt(mro.simulation_data, hyst, ttt, RLF_THRESHOLD)
mro_plot_scatter(attached_df, topology)

In [ ]:
ue_id = 0 # change this to the UE you want to plot
plot_sinr_db_by_ue(attached_df, mro.simulation_data, ue_id)

# Showcasing **Bayesian or XGBoost MRO** Solving Approach

use the following example `topology` and `mobility_model_params` to initiate MRO.

In [7]:
mro = BayesianMRO(mobility_model_params, topology)

In [8]:
mro.train_or_update_rf_twins(input_data)

[2025-07-13 22:03:43,922] INFO:  Iter 1/100 - Loss: 0.784 (delta=inf)
[2025-07-13 22:03:43,959] INFO:  Iter 2/100 - Loss: 0.765 (delta=-0.019080)
[2025-07-13 22:03:43,993] INFO:  Iter 3/100 - Loss: 0.745 (delta=-0.019101)

No Bayesian Digital Twins available for update. Training from scratch.

[2025-07-13 22:03:44,036] INFO:  Iter 4/100 - Loss: 0.726 (delta=-0.019151)
[2025-07-13 22:03:44,095] INFO:  Iter 5/100 - Loss: 0.707 (delta=-0.019225)
[2025-07-13 22:03:44,164] INFO:  Iter 6/100 - Loss: 0.688 (delta=-0.019359)
[2025-07-13 22:03:44,227] INFO:  Iter 7/100 - Loss: 0.668 (delta=-0.019512)
[2025-07-13 22:03:44,268] INFO:  Iter 8/100 - Loss: 0.648 (delta=-0.019742)
[2025-07-13 22:03:44,303] INFO:  Iter 9/100 - Loss: 0.629 (delta=-0.019925)
[2025-07-13 22:03:44,334] INFO:  Iter 10/100 - Loss: 0.608 (delta=-0.020137)
[2025-07-13 22:03:44,368] INFO:  Iter 11/100 - Loss: 0.588 (delta=-0.020349)
[2025-07-13 22:03:44,401] INFO:  Iter 12/100 - Loss: 0.567 (delta=-0.020548)
[2025-07-13 22:03:44,433] INFO:  Iter 13/100 - Loss: 0.547 (delta=-0.020711)
[2025-07-13 22:03:44,466] INFO:  Iter 14/100 - Loss: 0.526 (delta=-0.020913)
[2025-07-13 22:03:44,499] INFO:  Iter 15/100 - Loss: 0.505 (delta=-0.021102)
[2025-07-13 22:03:44,534] INFO:  Iter 16/100 - Loss: 0.483 (delta=-0.021266)
[2025-07-13 22:03:44,571] INFO:  Iter 17/100 - Loss: 0.462 (delta=-0.021445)
[2025-07-13 22:03:44,610] INFO:  Iter 18/100 - Loss: 0.440 (delta=-0.021612)
[2025-07-13 22:03:44,647] INFO:  Iter 19/100 - Loss: 0.419 (delta=-0.021794)
[2025-07-13 22:03:44,685] INFO:  Iter 20/100 - Loss: 0.397 (delta=-0.021958)
[2025-07-13 22:03:44,722] INFO:  Iter 21/100 - Loss: 0.375 (delta=-0.022144)
[2025-07-13 22:03:44,758] INFO:  Iter 22/100 - Loss: 0.352 (delta=-0.022313)
[2025-07-13 22:03:44,795] INFO:  Iter 23/100 - Loss: 0.330 (delta=-0.022500)
[2025-07-13 22:03:44,835] INFO:  Iter 24/100 - Loss: 0.307 (delta=-0.022661)
[2025-07-13 22:03:44,872] INFO:  Iter 25/100 - Loss: 0.284 (delta=-0.022828)
[2025-07-13 22:03:44,909] INFO:  Iter 26/100 - Loss: 0.261 (delta=-0.022998)
[2025-07-13 22:03:44,947] INFO:  Iter 27/100 - Loss: 0.238 (delta=-0.023163)
[2025-07-13 22:03:44,984] INFO:  Iter 28/100 - Loss: 0.215 (delta=-0.023338)
[2025-07-13 22:03:45,023] INFO:  Iter 29/100 - Loss: 0.191 (delta=-0.023497)
[2025-07-13 22:03:45,064] INFO:  Iter 30/100 - Loss: 0.168 (delta=-0.023645)
[2025-07-13 22:03:45,102] INFO:  Iter 31/100 - Loss: 0.144 (delta=-0.023801)
[2025-07-13 22:03:45,137] INFO:  Iter 32/100 - Loss: 0.120 (delta=-0.023974)
[2025-07-13 22:03:45,172] INFO:  Iter 33/100 - Loss: 0.096 (delta=-0.024125)
[2025-07-13 22:03:45,208] INFO:  Iter 34/100 - Loss: 0.071 (delta=-0.024259)
[2025-07-13 22:03:45,240] INFO:  Iter 35/100 - Loss: 0.047 (delta=-0.024426)
[2025-07-13 22:03:45,277] INFO:  Iter 36/100 - Loss: 0.022 (delta=-0.024634)
[2025-07-13 22:03:45,312] INFO:  Iter 37/100 - Loss: -0.002 (delta=-0.024694)
[2025-07-13 22:03:45,349] INFO:  Iter 38/100 - Loss: -0.027 (delta=-0.024971)
[2025-07-13 22:03:45,388] INFO:  Iter 39/100 - Loss: -0.052 (delta=-0.025038)
[2025-07-13 22:03:45,427] INFO:  Iter 40/100 - Loss: -0.077 (delta=-0.025045)
[2025-07-13 22:03:45,465] INFO:  Iter 41/100 - Loss: -0.103 (delta=-0.025304)
[2025-07-13 22:03:45,504] INFO:  Iter 42/100 - Loss: -0.128 (delta=-0.025325)
[2025-07-13 22:03:45,539] INFO:  Iter 43/100 - Loss: -0.153 (delta=-0.025179)
[2025-07-13 22:03:45,574] INFO:  Iter 44/100 - Loss: -0.179 (delta=-0.025556)
[2025-07-13 22:03:45,609] INFO:  Iter 45/100 - Loss: -0.204 (delta=-0.025450)
[2025-07-13 22:03:45,644] INFO:  Iter 46/100 - Loss: -0.230 (delta=-0.025603)
[2025-07-13 22:03:45,678] INFO:  Iter 47/100 - Loss: -0.255 (delta=-0.025554)
[2025-07-13 22:03:45,712] INFO:  Iter 48/100 - Loss: -0.281 (delta=-0.025923)
[2025-07-13 22:03:45,746] INFO:  Iter 49/100 - Loss: -0.307 (delta=-0.026019)
[2025-07-13 22:03:45,779] INFO:  Iter 50/100 - Loss: -0.333 (delta=-0.025728)
[2025-07-13 22:03:45,813] INFO:  Iter 51/100 - Loss: -0.359 (delta=-0.026043)
[2025-07-13 22:03:45,848] INFO:  Iter 52/100 - Loss: -0.385 (delta=-0.026064)
[2025-07-13 22:03:45,887] INFO:  Iter 53/100 - Loss: -0.411 (delta=-0.026197)
[2025-07-13 22:03:45,926] INFO:  Iter 54/100 - Loss: -0.437 (delta=-0.026009)
[2025-07-13 22:03:45,963] INFO:  Iter 55/100 - Loss: -0.463 (delta=-0.026111)
[2025-07-13 22:03:46,003] INFO:  Iter 56/100 - Loss: -0.490 (delta=-0.026320)
[2025-07-13 22:03:46,040] INFO:  Iter 57/100 - Loss: -0.516 (delta=-0.026352)
[2025-07-13 22:03:46,079] INFO:  Iter 58/100 - Loss: -0.542 (delta=-0.026176)
[2025-07-13 22:03:46,118] INFO:  Iter 59/100 - Loss: -0.568 (delta=-0.026149)
[2025-07-13 22:03:46,156] INFO:  Iter 60/100 - Loss: -0.595 (delta=-0.026402)
[2025-07-13 22:03:46,198] INFO:  Iter 61/100 - Loss: -0.621 (delta=-0.026594)
[2025-07-13 22:03:46,240] INFO:  Iter 62/100 - Loss: -0.648 (delta=-0.026297)
[2025-07-13 22:03:46,281] INFO:  Iter 63/100 - Loss: -0.674 (delta=-0.026475)
[2025-07-13 22:03:46,320] INFO:  Iter 64/100 - Loss: -0.701 (delta=-0.026313)
[2025-07-13 22:03:46,358] INFO:  Iter 65/100 - Loss: -0.727 (delta=-0.026474)
[2025-07-13 22:03:46,394] INFO:  Iter 66/100 - Loss: -0.753 (delta=-0.026414)
[2025-07-13 22:03:46,429] INFO:  Iter 67/100 - Loss: -0.780 (delta=-0.026260)
[2025-07-13 22:03:46,463] INFO:  Iter 68/100 - Loss: -0.806 (delta=-0.026695)
[2025-07-13 22:03:46,497] INFO:  Iter 69/100 - Loss: -0.833 (delta=-0.026616)
[2025-07-13 22:03:46,531] INFO:  Iter 70/100 - Loss: -0.860 (delta=-0.026605)
[2025-07-13 22:03:46,566] INFO:  Iter 71/100 - Loss: -0.886 (delta=-0.026300)
[2025-07-13 22:03:46,600] INFO:  Iter 72/100 - Loss: -0.912 (delta=-0.026515)
[2025-07-13 22:03:46,634] INFO:  Iter 73/100 - Loss: -0.939 (delta=-0.026365)
[2025-07-13 22:03:46,671] INFO:  Iter 74/100 - Loss: -0.965 (delta=-0.026669)
[2025-07-13 22:03:46,706] INFO:  Iter 75/100 - Loss: -0.992 (delta=-0.026164)
[2025-07-13 22:03:46,741] INFO:  Iter 76/100 - Loss: -1.018 (delta=-0.026544)
[2025-07-13 22:03:46,774] INFO:  Iter 77/100 - Loss: -1.045 (delta=-0.026685)
[2025-07-13 22:03:46,808] INFO:  Iter 78/100 - Loss: -1.071 (delta=-0.026293)
[2025-07-13 22:03:46,841] INFO:  Iter 79/100 - Loss: -1.098 (delta=-0.026435)
[2025-07-13 22:03:46,874] INFO:  Iter 80/100 - Loss: -1.124 (delta=-0.026640)
[2025-07-13 22:03:46,909] INFO:  Iter 81/100 - Loss: -1.150 (delta=-0.026148)
[2025-07-13 22:03:46,944] INFO:  Iter 82/100 - Loss: -1.177 (delta=-0.026412)
[2025-07-13 22:03:46,979] INFO:  Iter 83/100 - Loss: -1.203 (delta=-0.026513)
[2025-07-13 22:03:47,013] INFO:  Iter 84/100 - Loss: -1.230 (delta=-0.026281)
[2025-07-13 22:03:47,047] INFO:  Iter 85/100 - Loss: -1.256 (delta=-0.026186)
[2025-07-13 22:03:47,081] INFO:  Iter 86/100 - Loss: -1.282 (delta=-0.026349)
[2025-07-13 22:03:47,115] INFO:  Iter 87/100 - Loss: -1.308 (delta=-0.026359)
[2025-07-13 22:03:47,148] INFO:  Iter 88/100 - Loss: -1.335 (delta=-0.026180)
[2025-07-13 22:03:47,181] INFO:  Iter 89/100 - Loss: -1.361 (delta=-0.026531)
[2025-07-13 22:03:47,214] INFO:  Iter 90/100 - Loss: -1.387 (delta=-0.026004)
[2025-07-13 22:03:47,248] INFO:  Iter 91/100 - Loss: -1.413 (delta=-0.026087)
[2025-07-13 22:03:47,281] INFO:  Iter 92/100 - Loss: -1.439 (delta=-0.025969)
[2025-07-13 22:03:47,315] INFO:  Iter 93/100 - Loss: -1.465 (delta=-0.026023)
[2025-07-13 22:03:47,350] INFO:  Iter 94/100 - Loss: -1.491 (delta=-0.025869)
[2025-07-13 22:03:47,384] INFO:  Iter 95/100 - Loss: -1.517 (delta=-0.025988)
[2025-07-13 22:03:47,419] INFO:  Iter 96/100 - Loss: -1.543 (delta=-0.026194)
[2025-07-13 22:03:47,454] INFO:  Iter 97/100 - Loss: nan (delta=nan)
[2025-07-13 22:03:47,487] INFO:  Iter 98/100 - Loss: -1.595 (delta=nan)
[2025-07-13 22:03:47,523] INFO:  Iter 99/100 - Loss: -1.621 (delta=-0.025566)
[2025-07-13 22:03:47,556] INFO:  Iter 100/100 - Loss: -1.647 (delta=-0.025801)
[2025-07-13 22:03:47,594] INFO:  Iter 1/100 - Loss: 0.761 (delta=inf)
[2025-07-13 22:03:47,628] INFO:  Iter 2/100 - Loss: 0.743 (delta=-0.018671)
[2025-07-13 22:03:47,662] INFO:  Iter 3/100 - Loss: 0.724 (delta=-0.018732)
[2025-07-13 22:03:47,696] INFO:  Iter 4/100 - Loss: 0.705 (delta=-0.018821)
[2025-07-13 22:03:47,730] INFO:  Iter 5/100 - Loss: 0.686 (delta=-0.018942)
[2025-07-13 22:03:47,764] INFO:  Iter 6/100 - Loss: 0.667 (delta=-0.019105)
[2025-07-13 22:03:47,796] INFO:  Iter 7/100 - Loss: 0.648 (delta=-0.019286)
[2025-07-13 22:03:47,831] INFO:  Iter 8/100 - Loss: 0.628 (delta=-0.019502)
[2025-07-13 22:03:47,865] INFO:  Iter 9/100 - Loss: 0.609 (delta=-0.019699)
[2025-07-13 22:03:47,898] INFO:  Iter 10/100 - Loss: 0.589 (delta=-0.019898)
[2025-07-13 22:03:47,932] INFO:  Iter 11/100 - Loss: 0.569 (delta=-0.020106)
[2025-07-13 22:03:47,965] INFO:  Iter 12/100 - Loss: 0.548 (delta=-0.020309)
[2025-07-13 22:03:47,999] INFO:  Iter 13/100 - Loss: 0.528 (delta=-0.020501)
[2025-07-13 22:03:48,033] INFO:  Iter 14/100 - Loss: 0.507 (delta=-0.020704)
[2025-07-13 22:03:48,071] INFO:  Iter 15/100 - Loss: 0.486 (delta=-0.020883)
[2025-07-13 22:03:48,109] INFO:  Iter 16/100 - Loss: 0.465 (delta=-0.021085)
[2025-07-13 22:03:48,148] INFO:  Iter 17/100 - Loss: 0.444 (delta=-0.021269)
[2025-07-13 22:03:48,187] INFO:  Iter 18/100 - Loss: 0.422 (delta=-0.021451)
[2025-07-13 22:03:48,227] INFO:  Iter 19/100 - Loss: 0.401 (delta=-0.021647)
[2025-07-13 22:03:48,267] INFO:  Iter 20/100 - Loss: 0.379 (delta=-0.021812)
[2025-07-13 22:03:48,307] INFO:  Iter 21/100 - Loss: 0.357 (delta=-0.022006)
[2025-07-13 22:03:48,382] INFO:  Iter 22/100 - Loss: 0.335 (delta=-0.022180)
[2025-07-13 22:03:48,421] INFO:  Iter 23/100 - Loss: 0.312 (delta=-0.022361)
[2025-07-13 22:03:48,460] INFO:  Iter 24/100 - Loss: 0.290 (delta=-0.022532)
[2025-07-13 22:03:48,497] INFO:  Iter 25/100 - Loss: 0.267 (delta=-0.022703)
[2025-07-13 22:03:48,537] INFO:  Iter 26/100 - Loss: 0.244 (delta=-0.022873)
[2025-07-13 22:03:48,576] INFO:  Iter 27/100 - Loss: 0.221 (delta=-0.023043)
[2025-07-13 22:03:48,618] INFO:  Iter 28/100 - Loss: 0.198 (delta=-0.023202)
[2025-07-13 22:03:48,656] INFO:  Iter 29/100 - Loss: 0.175 (delta=-0.023359)
[2025-07-13 22:03:48,693] INFO:  Iter 30/100 - Loss: 0.151 (delta=-0.023511)
[2025-07-13 22:03:48,730] INFO:  Iter 31/100 - Loss: 0.128 (delta=-0.023666)
[2025-07-13 22:03:48,770] INFO:  Iter 32/100 - Loss: 0.104 (delta=-0.023806)
[2025-07-13 22:03:48,804] INFO:  Iter 33/100 - Loss: 0.080 (delta=-0.023948)
[2025-07-13 22:03:48,839] INFO:  Iter 34/100 - Loss: 0.056 (delta=-0.024085)
[2025-07-13 22:03:48,874] INFO:  Iter 35/100 - Loss: 0.032 (delta=-0.024216)
[2025-07-13 22:03:48,907] INFO:  Iter 36/100 - Loss: 0.007 (delta=-0.024338)
[2025-07-13 22:03:48,941] INFO:  Iter 37/100 - Loss: -0.017 (delta=-0.024464)
[2025-07-13 22:03:48,973] INFO:  Iter 38/100 - Loss: -0.042 (delta=-0.024581)
[2025-07-13 22:03:49,006] INFO:  Iter 39/100 - Loss: -0.067 (delta=-0.024696)
[2025-07-13 22:03:49,040] INFO:  Iter 40/100 - Loss: -0.091 (delta=-0.024796)
[2025-07-13 22:03:49,074] INFO:  Iter 41/100 - Loss: -0.116 (delta=-0.024917)
[2025-07-13 22:03:49,106] INFO:  Iter 42/100 - Loss: -0.141 (delta=-0.025006)
[2025-07-13 22:03:49,140] INFO:  Iter 43/100 - Loss: -0.166 (delta=-0.025102)
[2025-07-13 22:03:49,178] INFO:  Iter 44/100 - Loss: -0.192 (delta=-0.025192)
[2025-07-13 22:03:49,213] INFO:  Iter 45/100 - Loss: -0.217 (delta=-0.025277)
[2025-07-13 22:03:49,247] INFO:  Iter 46/100 - Loss: -0.242 (delta=-0.025358)
[2025-07-13 22:03:49,280] INFO:  Iter 47/100 - Loss: -0.268 (delta=-0.025441)
[2025-07-13 22:03:49,314] INFO:  Iter 48/100 - Loss: -0.293 (delta=-0.025499)
[2025-07-13 22:03:49,348] INFO:  Iter 49/100 - Loss: -0.319 (delta=-0.025587)
[2025-07-13 22:03:49,382] INFO:  Iter 50/100 - Loss: -0.344 (delta=-0.025634)
[2025-07-13 22:03:49,415] INFO:  Iter 51/100 - Loss: -0.370 (delta=-0.025709)
[2025-07-13 22:03:49,449] INFO:  Iter 52/100 - Loss: -0.396 (delta=-0.025765)
[2025-07-13 22:03:49,482] INFO:  Iter 53/100 - Loss: -0.422 (delta=-0.025819)
[2025-07-13 22:03:49,515] INFO:  Iter 54/100 - Loss: -0.448 (delta=-0.025875)
[2025-07-13 22:03:49,549] INFO:  Iter 55/100 - Loss: -0.473 (delta=-0.025906)
[2025-07-13 22:03:49,582] INFO:  Iter 56/100 - Loss: -0.499 (delta=-0.025954)
[2025-07-13 22:03:49,615] INFO:  Iter 57/100 - Loss: -0.525 (delta=-0.025998)
[2025-07-13 22:03:49,649] INFO:  Iter 58/100 - Loss: -0.551 (delta=-0.026028)
[2025-07-13 22:03:49,682] INFO:  Iter 59/100 - Loss: -0.578 (delta=-0.026090)
[2025-07-13 22:03:49,716] INFO:  Iter 60/100 - Loss: -0.604 (delta=-0.026093)
[2025-07-13 22:03:49,749] INFO:  Iter 61/100 - Loss: -0.630 (delta=-0.026141)
[2025-07-13 22:03:49,781] INFO:  Iter 62/100 - Loss: -0.656 (delta=-0.026163)
[2025-07-13 22:03:49,816] INFO:  Iter 63/100 - Loss: -0.682 (delta=-0.026177)
[2025-07-13 22:03:49,850] INFO:  Iter 64/100 - Loss: -0.708 (delta=-0.026254)
[2025-07-13 22:03:49,883] INFO:  Iter 65/100 - Loss: -0.735 (delta=-0.026277)
[2025-07-13 22:03:49,916] INFO:  Iter 66/100 - Loss: -0.761 (delta=-0.026262)
[2025-07-13 22:03:49,948] INFO:  Iter 67/100 - Loss: -0.787 (delta=-0.026350)
[2025-07-13 22:03:49,982] INFO:  Iter 68/100 - Loss: -0.814 (delta=-0.026366)
[2025-07-13 22:03:50,015] INFO:  Iter 69/100 - Loss: -0.840 (delta=-0.026402)
[2025-07-13 22:03:50,048] INFO:  Iter 70/100 - Loss: -0.866 (delta=-0.026474)
[2025-07-13 22:03:50,082] INFO:  Iter 71/100 - Loss: -0.893 (delta=-0.026489)
[2025-07-13 22:03:50,115] INFO:  Iter 72/100 - Loss: -0.919 (delta=-0.026489)
[2025-07-13 22:03:50,148] INFO:  Iter 73/100 - Loss: -0.946 (delta=-0.026510)
[2025-07-13 22:03:50,181] INFO:  Iter 74/100 - Loss: -0.972 (delta=-0.026451)
[2025-07-13 22:03:50,214] INFO:  Iter 75/100 - Loss: -0.999 (delta=-0.026423)
[2025-07-13 22:03:50,248] INFO:  Iter 76/100 - Loss: -1.025 (delta=-0.026272)
[2025-07-13 22:03:50,281] INFO:  Iter 77/100 - Loss: -1.051 (delta=-0.026202)
[2025-07-13 22:03:50,316] INFO:  Iter 78/100 - Loss: -1.078 (delta=-0.026400)
[2025-07-13 22:03:50,349] INFO:  Iter 79/100 - Loss: -1.104 (delta=-0.026305)
[2025-07-13 22:03:50,383] INFO:  Iter 80/100 - Loss: -1.130 (delta=-0.026303)
[2025-07-13 22:03:50,418] INFO:  Iter 81/100 - Loss: -1.157 (delta=-0.026443)
[2025-07-13 22:03:50,451] INFO:  Iter 82/100 - Loss: -1.183 (delta=-0.026431)
[2025-07-13 22:03:50,486] INFO:  Iter 83/100 - Loss: -1.209 (delta=-0.026287)
[2025-07-13 22:03:50,520] INFO:  Iter 84/100 - Loss: -1.236 (delta=-0.026385)
[2025-07-13 22:03:50,554] INFO:  Iter 85/100 - Loss: -1.262 (delta=-0.026328)
[2025-07-13 22:03:50,588] INFO:  Iter 86/100 - Loss: -1.288 (delta=-0.026187)
[2025-07-13 22:03:50,623] INFO:  Iter 87/100 - Loss: -1.315 (delta=-0.026204)
[2025-07-13 22:03:50,657] INFO:  Iter 88/100 - Loss: -1.340 (delta=-0.025811)
[2025-07-13 22:03:50,690] INFO:  Iter 89/100 - Loss: -1.367 (delta=-0.026621)
[2025-07-13 22:03:50,723] INFO:  Iter 90/100 - Loss: -1.393 (delta=-0.026093)
[2025-07-13 22:03:50,756] INFO:  Iter 91/100 - Loss: -1.419 (delta=-0.026140)
[2025-07-13 22:03:50,790] INFO:  Iter 92/100 - Loss: -1.445 (delta=-0.026172)
[2025-07-13 22:03:50,824] INFO:  Iter 93/100 - Loss: nan (delta=nan)
[2025-07-13 22:03:50,857] INFO:  Iter 94/100 - Loss: nan (delta=nan)
[2025-07-13 22:03:50,892] INFO:  Iter 95/100 - Loss: -1.523 (delta=nan)
[2025-07-13 22:03:50,927] INFO:  Iter 96/100 - Loss: -1.550 (delta=-0.026034)
[2025-07-13 22:03:50,961] INFO:  Iter 97/100 - Loss: -1.575 (delta=-0.025883)
[2025-07-13 22:03:50,995] INFO:  Iter 98/100 - Loss: -1.601 (delta=-0.025940)
[2025-07-13 22:03:51,029] INFO:  Iter 99/100 - Loss: nan (delta=nan)
[2025-07-13 22:03:51,063] INFO:  Iter 100/100 - Loss: nan (delta=nan)
[2025-07-13 22:03:51,101] INFO:  Iter 1/100 - Loss: 0.778 (delta=inf)
[2025-07-13 22:03:51,133] INFO:  Iter 2/100 - Loss: 0.759 (delta=-0.019063)
[2025-07-13 22:03:51,166] INFO:  Iter 3/100 - Loss: 0.740 (delta=-0.019110)
[2025-07-13 22:03:51,200] INFO:  Iter 4/100 - Loss: 0.721 (delta=-0.019167)
[2025-07-13 22:03:51,234] INFO:  Iter 5/100 - Loss: 0.702 (delta=-0.019245)
[2025-07-13 22:03:51,266] INFO:  Iter 6/100 - Loss: 0.682 (delta=-0.019347)
[2025-07-13 22:03:51,298] INFO:  Iter 7/100 - Loss: 0.663 (delta=-0.019489)
[2025-07-13 22:03:51,331] INFO:  Iter 8/100 - Loss: 0.643 (delta=-0.019673)
[2025-07-13 22:03:51,365] INFO:  Iter 9/100 - Loss: 0.623 (delta=-0.019856)
[2025-07-13 22:03:51,399] INFO:  Iter 10/100 - Loss: 0.603 (delta=-0.020084)
[2025-07-13 22:03:51,431] INFO:  Iter 11/100 - Loss: 0.583 (delta=-0.020274)
[2025-07-13 22:03:51,465] INFO:  Iter 12/100 - Loss: 0.562 (delta=-0.020479)
[2025-07-13 22:03:51,499] INFO:  Iter 13/100 - Loss: 0.542 (delta=-0.020679)
[2025-07-13 22:03:51,537] INFO:  Iter 14/100 - Loss: 0.521 (delta=-0.020863)
[2025-07-13 22:03:51,572] INFO:  Iter 15/100 - Loss: 0.500 (delta=-0.021062)
[2025-07-13 22:03:51,605] INFO:  Iter 16/100 - Loss: 0.478 (delta=-0.021239)
[2025-07-13 22:03:51,638] INFO:  Iter 17/100 - Loss: 0.457 (delta=-0.021414)
[2025-07-13 22:03:51,671] INFO:  Iter 18/100 - Loss: 0.435 (delta=-0.021585)
[2025-07-13 22:03:51,704] INFO:  Iter 19/100 - Loss: 0.414 (delta=-0.021762)
[2025-07-13 22:03:51,738] INFO:  Iter 20/100 - Loss: 0.392 (delta=-0.021928)
[2025-07-13 22:03:51,771] INFO:  Iter 21/100 - Loss: 0.370 (delta=-0.022100)
[2025-07-13 22:03:51,805] INFO:  Iter 22/100 - Loss: 0.347 (delta=-0.022269)
[2025-07-13 22:03:51,840] INFO:  Iter 23/100 - Loss: 0.325 (delta=-0.022437)
[2025-07-13 22:03:51,873] INFO:  Iter 24/100 - Loss: 0.302 (delta=-0.022611)
[2025-07-13 22:03:51,906] INFO:  Iter 25/100 - Loss: 0.280 (delta=-0.022766)
[2025-07-13 22:03:51,940] INFO:  Iter 26/100 - Loss: 0.257 (delta=-0.022941)
[2025-07-13 22:03:51,974] INFO:  Iter 27/100 - Loss: 0.234 (delta=-0.023098)
[2025-07-13 22:03:52,006] INFO:  Iter 28/100 - Loss: 0.210 (delta=-0.023251)
[2025-07-13 22:03:52,040] INFO:  Iter 29/100 - Loss: 0.187 (delta=-0.023395)
[2025-07-13 22:03:52,074] INFO:  Iter 30/100 - Loss: 0.163 (delta=-0.023570)
[2025-07-13 22:03:52,107] INFO:  Iter 31/100 - Loss: 0.140 (delta=-0.023698)
[2025-07-13 22:03:52,140] INFO:  Iter 32/100 - Loss: 0.116 (delta=-0.023838)
[2025-07-13 22:03:52,174] INFO:  Iter 33/100 - Loss: 0.092 (delta=-0.023979)
[2025-07-13 22:03:52,207] INFO:  Iter 34/100 - Loss: 0.068 (delta=-0.024123)
[2025-07-13 22:03:52,240] INFO:  Iter 35/100 - Loss: 0.043 (delta=-0.024235)
[2025-07-13 22:03:52,273] INFO:  Iter 36/100 - Loss: 0.019 (delta=-0.024382)
[2025-07-13 22:03:52,307] INFO:  Iter 37/100 - Loss: -0.005 (delta=-0.024499)
[2025-07-13 22:03:52,341] INFO:  Iter 38/100 - Loss: -0.030 (delta=-0.024624)
[2025-07-13 22:03:52,378] INFO:  Iter 39/100 - Loss: -0.055 (delta=-0.024753)
[2025-07-13 22:03:52,412] INFO:  Iter 40/100 - Loss: -0.080 (delta=-0.024857)
[2025-07-13 22:03:52,447] INFO:  Iter 41/100 - Loss: -0.105 (delta=-0.025009)
[2025-07-13 22:03:52,486] INFO:  Iter 42/100 - Loss: -0.130 (delta=-0.025120)
[2025-07-13 22:03:52,521] INFO:  Iter 43/100 - Loss: -0.155 (delta=-0.025227)
[2025-07-13 22:03:52,555] INFO:  Iter 44/100 - Loss: -0.180 (delta=-0.025379)
[2025-07-13 22:03:52,589] INFO:  Iter 45/100 - Loss: -0.206 (delta=-0.025496)
[2025-07-13 22:03:52,622] INFO:  Iter 46/100 - Loss: -0.231 (delta=-0.025567)
[2025-07-13 22:03:52,657] INFO:  Iter 47/100 - Loss: -0.257 (delta=-0.025689)
[2025-07-13 22:03:52,696] INFO:  Iter 48/100 - Loss: -0.283 (delta=-0.025805)
[2025-07-13 22:03:52,735] INFO:  Iter 49/100 - Loss: -0.309 (delta=-0.025785)
[2025-07-13 22:03:52,772] INFO:  Iter 50/100 - Loss: -0.335 (delta=-0.025853)
[2025-07-13 22:03:52,807] INFO:  Iter 51/100 - Loss: -0.360 (delta=-0.025738)
[2025-07-13 22:03:52,839] INFO:  Iter 52/100 - Loss: -0.386 (delta=-0.026048)
[2025-07-13 22:03:52,873] INFO:  Iter 53/100 - Loss: -0.412 (delta=-0.025886)
[2025-07-13 22:03:52,907] INFO:  Iter 54/100 - Loss: -0.438 (delta=-0.026068)
[2025-07-13 22:03:52,941] INFO:  Iter 55/100 - Loss: -0.464 (delta=-0.025976)
[2025-07-13 22:03:52,974] INFO:  Iter 56/100 - Loss: -0.490 (delta=-0.026073)
[2025-07-13 22:03:53,013] INFO:  Iter 57/100 - Loss: -0.517 (delta=-0.026386)
[2025-07-13 22:03:53,050] INFO:  Iter 58/100 - Loss: -0.543 (delta=-0.025925)
[2025-07-13 22:03:53,088] INFO:  Iter 59/100 - Loss: -0.569 (delta=-0.026584)
[2025-07-13 22:03:53,126] INFO:  Iter 60/100 - Loss: -0.595 (delta=-0.026158)
[2025-07-13 22:03:53,164] INFO:  Iter 61/100 - Loss: -0.622 (delta=-0.026303)

Bayesian Digital Twins trained successfully.

In [9]:
mro.solve()

Optimized Hyst: 2.568939405978036,
Optimized TTT: 4

(2.568939405978036, 4)