# Notebook to fix PR issues

### Generate the UE data from mobility model first

In [1]:
import sys
from pathlib import Path
sys.path.append(f"{Path().absolute().parent}")

In [2]:
import pandas as pd
import scipy
import numpy as np
from radp_library import *
import matplotlib.pyplot as plt
import matplotlib.cm as cm
from radp.digital_twin.mobility.param_regression import get_predicted_alpha,preprocess_ue_data
from radp.digital_twin.utils.cell_selection import perform_attachment
from radp.digital_twin.rf.bayesian.bayesian_engine import (
    BayesianDigitalTwin,
    NormMethod,
)
from apps.mobility_robustness_optimization.simple_mro import SimpleMRO

/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/fastkml/config.py:39: UserWarning: Package `lxml` missing. Pretty print will be disabled
  warnings.warn("Package `lxml` missing. Pretty print will be disabled")  # noqa: B028

In [3]:
params = {
    "ue_tracks_generation": {
            "params": {
                "simulation_duration": 3600,
                "simulation_time_interval_seconds": 0.01,
                "num_ticks": 50,
                "num_batches": 1,
                "ue_class_distribution": {
                    "stationary": {
                        "count": 10,
                        "velocity": 0,
                        "velocity_variance": 1
                    },
                    "pedestrian": {
                        "count": 5,
                        "velocity": 2,
                        "velocity_variance": 1
                    },
                    "cyclist": {
                        "count": 5,
                        "velocity": 5,
                        "velocity_variance": 1
                    },
                    "car": {
                        "count": 12,
                        "velocity": 20,
                        "velocity_variance": 1
                    }
                },
                "lat_lon_boundaries": {
                    "min_lat": -90,
                    "max_lat": 90,
                    "min_lon": -180,
                    "max_lon": 180
                },
                "gauss_markov_params": {
                    "alpha": 0.5,
                    "variance": 0.8,
                    "rng_seed": 42,
                    "lon_x_dims": 100,
                    "lon_y_dims": 100,
                    "// TODO": "Account for supporting the user choosing the anchor_loc and cov_around_anchor.",
                    "// Current implementation": "the UE Tracks generator will not be using these values.",
                    "// anchor_loc": {},
                    "// cov_around_anchor": {}
            }
        }
    }
}

In [4]:
training_data = get_ue_data(params)
training_data.head()

   mock_ue_id         lon        lat  tick
0           0   48.510339 -16.462645     0
1           1   19.286613  63.617111     0
2           2   21.315702 -47.889952     0
3           3  -70.559364 -79.511709     0
4           4 -168.916011 -39.338640     0

In [3]:
topology = pd.read_csv('/Users/tanzimfarhan/Downloads/topology.csv')
topology.loc[topology['cell_id'] == 'cell_2', 'cell_lat'] = 0
topology.loc[topology['cell_id'] == 'cell_3', 'cell_lat'] = 90
topology.loc[topology['cell_id'] == 'cell_1', 'cell_lat'] = -90


topology.loc[topology['cell_id'] == 'cell_2', 'cell_lon'] = 0
topology.loc[topology['cell_id'] == 'cell_3', 'cell_lon'] = 180
topology.loc[topology['cell_id'] == 'cell_1', 'cell_lon'] = -180


topology.loc[topology['cell_id'] == 'cell_2', 'cell_carrier_freq_mhz'] = 2800
topology.loc[topology['cell_id'] == 'cell_3', 'cell_carrier_freq_mhz'] = 2800
topology.loc[topology['cell_id'] == 'cell_1', 'cell_carrier_freq_mhz'] = 2800

In [4]:
def _prepare_all_UEs_from_all_cells_df(
     data, topology
    ) -> pd.DataFrame:
        """
        Connects each user equipment (UE) entry to all cells in the topology for each tick,
        effectively creating a Cartesian product of UEs and cells, which includes data from both sources.
        """

        ue_data = data
        ue_data = ue_data.rename(columns={"lat": "latitude", "lon": "longitude"})
        topology_tmp = topology
        # Remove the 'cell_' prefix and convert cell_id to integer if needed
        if topology_tmp["cell_id"].dtype == object:
            topology_tmp["cell_id"] = (
                topology_tmp["cell_id"].str.replace("cell_", "").astype(int)
            )
        ue_data["key"] = 1
        topology_tmp["key"] = 1
        combined_df = pd.merge(ue_data, topology_tmp, on="key").drop("key", axis=1)
        print("Combined DataFrame:", combined_df)
        return combined_df

In [5]:
def _preprocess_ue_topology_data(data,topology) -> pd.DataFrame:
        full_data = _prepare_all_UEs_from_all_cells_df(data,topology)
        full_data["log_distance"] = full_data.apply(
            lambda row: GISTools.get_log_distance(
                row["latitude"], row["longitude"], row["cell_lat"], row["cell_lon"]
            ),
            axis=1,
        )

        full_data["cell_rxpwr_dbm"] = full_data.apply(
            lambda row: calculate_received_power(
                row["log_distance"], row["cell_carrier_freq_mhz"]
            ),
            axis=1,
        )

        return full_data

In [6]:
def _preprocess_ue_training_data(data,topology) -> pd.DataFrame:
        data = _preprocess_ue_topology_data(data,topology)
        train_per_cell_df = [x for _, x in data.groupby("cell_id")]
        n_cell = len(topology.index)

        metadata_df = pd.DataFrame(
            {
                "cell_id": [cell_id for cell_id in topology.cell_id],
                "idx": [i + 1 for i in range(n_cell)],
            }
        )
        idx_cell_id_mapping = dict(zip(metadata_df.idx, metadata_df.cell_id))
        desired_idxs = [1 + r for r in range(n_cell)]

        n_samples_train = []
        for df in train_per_cell_df:
            n_samples_train.append(df.shape[0])

        train_per_cell_df_processed = []
        for i in range(n_cell):
            train_per_cell_df_processed.append(
                get_percell_data(
                    data_in=train_per_cell_df[i],
                    choose_strongest_samples_percell=False,
                    n_samples=n_samples_train[i],
                )[0][0]
            )

        training_data = {}

        for i, df in enumerate(train_per_cell_df_processed):
            train_cell_id = idx_cell_id_mapping[i + 1]
            training_data[train_cell_id] = df

        for train_cell_id, training_data_idx in training_data.items():
            training_data_idx["cell_id"] = train_cell_id
            training_data_idx["cell_lat"] = topology[
                topology["cell_id"] == train_cell_id
            ]["cell_lat"].values[0]
            training_data_idx["cell_lon"] = topology[
                topology["cell_id"] == train_cell_id
            ]["cell_lon"].values[0]
            training_data_idx["cell_az_deg"] = topology[
                topology["cell_id"] == train_cell_id
            ]["cell_az_deg"].values[0]
            training_data_idx["cell_carrier_freq_mhz"] = topology[
                topology["cell_id"] == train_cell_id
            ]["cell_carrier_freq_mhz"].values[0]
            training_data_idx["relative_bearing"] = [
                GISTools.get_relative_bearing(
                    training_data_idx["cell_az_deg"].values[0],
                    training_data_idx["cell_lat"].values[0],
                    training_data_idx["cell_lon"].values[0],
                    lat,
                    lon,
                )
                for lat, lon in zip(
                    training_data_idx["latitude"], training_data_idx["longitude"]
                )
            ]

        return training_data

In [7]:
bayesian_digital_twins = {}

In [8]:
def _training(bayesian_digital_twins, maxiter: int, train_data: pd.DataFrame,topology: pd.DataFrame) -> List[float]:
        """
        Trains the Bayesian Digital Twins for each cell in the topology using the UE locations and features
        like log distance, relative bearing, and cell received power (Rx power).
        """
        training_data = _preprocess_ue_training_data(train_data,topology)
        loss_vs_iters = []
        for train_cell_id, training_data_idx in training_data.items():
            bayesian_digital_twins[train_cell_id] = BayesianDigitalTwin(
                data_in=[training_data_idx],
                x_columns=["log_distance", "relative_bearing"],
                y_columns=["cell_rxpwr_dbm"],
                norm_method=NormMethod.MINMAX,
            )
            bayesian_digital_twins[train_cell_id] = bayesian_digital_twins[
                train_cell_id
            ]
            loss_vs_iters.append(
                bayesian_digital_twins[train_cell_id].train_distributed_gpmodel(
                    maxiter=maxiter,
                )
            )
        return bayesian_digital_twins, loss_vs_iters

In [11]:
bayesian_digital_twins, loss_vs_iters = _training(
    bayesian_digital_twins,
    maxiter=100,
    train_data=training_data,
    topology=topology,
)

Combined DataFrame:       mock_ue_id   longitude   latitude  tick  cell_lat  cell_lon  cell_id  \
0              0   48.510339 -16.462645     0     -90.0    -180.0        1
1              0   48.510339 -16.462645     0       0.0       0.0        2
2              0   48.510339 -16.462645     0      90.0     180.0        3
3              1   19.286613  63.617111     0     -90.0    -180.0        1
4              1   19.286613  63.617111     0       0.0       0.0        2
...          ...         ...        ...   ...       ...       ...      ...
4795          30   89.100351 -11.651079    49       0.0       0.0        2
4796          30   89.100351 -11.651079    49      90.0     180.0        3
4797          31  146.478589  74.187621    49     -90.0    -180.0        1
4798          31  146.478589  74.187621    49       0.0       0.0        2
4799          31  146.478589  74.187621    49      90.0     180.0        3

      cell_az_deg  cell_carrier_freq_mhz
0               0                   2800
1             120                   2800
2             240                   2800
3               0                   2800
4             120                   2800
...           ...                    ...
4795          120                   2800
4796          240                   2800
4797            0                   2800
4798          120                   2800
4799          240                   2800

[4800 rows x 9 columns]

[2025-05-06 22:20:05,799] INFO:  Iter 1/100 - Loss: 0.771 (delta=inf)
[2025-05-06 22:20:05,824] INFO:  Iter 2/100 - Loss: 0.752 (delta=-0.018841)
[2025-05-06 22:20:05,849] INFO:  Iter 3/100 - Loss: 0.731 (delta=-0.020256)
[2025-05-06 22:20:05,880] INFO:  Iter 4/100 - Loss: 0.713 (delta=-0.018046)
[2025-05-06 22:20:05,919] INFO:  Iter 5/100 - Loss: 0.695 (delta=-0.018767)
[2025-05-06 22:20:05,953] INFO:  Iter 6/100 - Loss: 0.676 (delta=-0.018556)
[2025-05-06 22:20:05,989] INFO:  Iter 7/100 - Loss: 0.658 (delta=-0.017709)
[2025-05-06 22:20:06,023] INFO:  Iter 8/100 - Loss: 0.635 (delta=-0.023394)
[2025-05-06 22:20:06,058] INFO:  Iter 9/100 - Loss: 0.615 (delta=-0.019590)
[2025-05-06 22:20:06,088] INFO:  Iter 10/100 - Loss: 0.600 (delta=-0.015070)
[2025-05-06 22:20:06,120] INFO:  Iter 11/100 - Loss: 0.573 (delta=-0.027165)
[2025-05-06 22:20:06,164] INFO:  Iter 12/100 - Loss: 0.558 (delta=-0.014900)
[2025-05-06 22:20:06,194] INFO:  Iter 13/100 - Loss: 0.535 (delta=-0.022887)
[2025-05-06 22:20:06,219] INFO:  Iter 14/100 - Loss: 0.513 (delta=-0.021870)
[2025-05-06 22:20:06,244] INFO:  Iter 15/100 - Loss: 0.494 (delta=-0.019018)
[2025-05-06 22:20:06,269] INFO:  Iter 16/100 - Loss: 0.474 (delta=-0.020518)
[2025-05-06 22:20:06,294] INFO:  Iter 17/100 - Loss: 0.452 (delta=-0.021529)
[2025-05-06 22:20:06,318] INFO:  Iter 18/100 - Loss: 0.427 (delta=-0.025246)
[2025-05-06 22:20:06,342] INFO:  Iter 19/100 - Loss: 0.411 (delta=-0.016421)
[2025-05-06 22:20:06,365] INFO:  Iter 20/100 - Loss: 0.387 (delta=-0.023516)
[2025-05-06 22:20:06,389] INFO:  Iter 21/100 - Loss: 0.367 (delta=-0.020237)
[2025-05-06 22:20:06,412] INFO:  Iter 22/100 - Loss: 0.343 (delta=-0.023859)
[2025-05-06 22:20:06,435] INFO:  Iter 23/100 - Loss: 0.318 (delta=-0.025607)
[2025-05-06 22:20:06,457] INFO:  Iter 24/100 - Loss: 0.298 (delta=-0.019887)
[2025-05-06 22:20:06,480] INFO:  Iter 25/100 - Loss: 0.279 (delta=-0.019079)
[2025-05-06 22:20:06,503] INFO:  Iter 26/100 - Loss: 0.253 (delta=-0.025334)
[2025-05-06 22:20:06,526] INFO:  Iter 27/100 - Loss: 0.227 (delta=-0.026119)
[2025-05-06 22:20:06,550] INFO:  Iter 28/100 - Loss: 0.207 (delta=-0.020126)
[2025-05-06 22:20:06,573] INFO:  Iter 29/100 - Loss: 0.185 (delta=-0.022458)
[2025-05-06 22:20:06,596] INFO:  Iter 30/100 - Loss: 0.161 (delta=-0.024030)
[2025-05-06 22:20:06,620] INFO:  Iter 31/100 - Loss: 0.135 (delta=-0.025763)
[2025-05-06 22:20:06,643] INFO:  Iter 32/100 - Loss: 0.113 (delta=-0.021935)
[2025-05-06 22:20:06,670] INFO:  Iter 33/100 - Loss: 0.087 (delta=-0.026214)
[2025-05-06 22:20:06,699] INFO:  Iter 34/100 - Loss: 0.063 (delta=-0.023717)
[2025-05-06 22:20:06,728] INFO:  Iter 35/100 - Loss: 0.041 (delta=-0.022269)
[2025-05-06 22:20:06,760] INFO:  Iter 36/100 - Loss: 0.016 (delta=-0.024459)
[2025-05-06 22:20:06,794] INFO:  Iter 37/100 - Loss: -0.006 (delta=-0.021850)
[2025-05-06 22:20:06,826] INFO:  Iter 38/100 - Loss: -0.032 (delta=-0.026101)
[2025-05-06 22:20:06,858] INFO:  Iter 39/100 - Loss: -0.057 (delta=-0.024839)
[2025-05-06 22:20:06,888] INFO:  Iter 40/100 - Loss: -0.082 (delta=-0.025545)
[2025-05-06 22:20:06,914] INFO:  Iter 41/100 - Loss: -0.110 (delta=-0.027536)
[2025-05-06 22:20:06,939] INFO:  Iter 42/100 - Loss: -0.133 (delta=-0.023354)
[2025-05-06 22:20:06,963] INFO:  Iter 43/100 - Loss: -0.160 (delta=-0.026696)
[2025-05-06 22:20:07,024] INFO:  Iter 44/100 - Loss: -0.183 (delta=-0.023244)
[2025-05-06 22:20:07,049] INFO:  Iter 45/100 - Loss: -0.209 (delta=-0.026164)
[2025-05-06 22:20:07,072] INFO:  Iter 46/100 - Loss: -0.233 (delta=-0.023776)
[2025-05-06 22:20:07,096] INFO:  Iter 47/100 - Loss: -0.261 (delta=-0.028356)
[2025-05-06 22:20:07,120] INFO:  Iter 48/100 - Loss: -0.283 (delta=-0.022024)
[2025-05-06 22:20:07,144] INFO:  Iter 49/100 - Loss: -0.314 (delta=-0.030456)
[2025-05-06 22:20:07,166] INFO:  Iter 50/100 - Loss: -0.340 (delta=-0.026291)
[2025-05-06 22:20:07,188] INFO:  Iter 51/100 - Loss: -0.362 (delta=-0.021514)
[2025-05-06 22:20:07,210] INFO:  Iter 52/100 - Loss: -0.393 (delta=-0.031551)
[2025-05-06 22:20:07,233] INFO:  Iter 53/100 - Loss: -0.416 (delta=-0.022802)
[2025-05-06 22:20:07,255] INFO:  Iter 54/100 - Loss: -0.436 (delta=-0.019683)
[2025-05-06 22:20:07,278] INFO:  Iter 55/100 - Loss: -0.468 (delta=-0.032024)
[2025-05-06 22:20:07,302] INFO:  Iter 56/100 - Loss: -0.496 (delta=-0.028453)
[2025-05-06 22:20:07,325] INFO:  Iter 57/100 - Loss: -0.516 (delta=-0.020202)
[2025-05-06 22:20:07,348] INFO:  Iter 58/100 - Loss: -0.543 (delta=-0.026359)
[2025-05-06 22:20:07,375] INFO:  Iter 59/100 - Loss: -0.572 (delta=-0.029197)
[2025-05-06 22:20:07,411] INFO:  Iter 60/100 - Loss: -0.595 (delta=-0.023466)
[2025-05-06 22:20:07,446] INFO:  Iter 61/100 - Loss: -0.622 (delta=-0.026901)
[2025-05-06 22:20:07,480] INFO:  Iter 62/100 - Loss: -0.653 (delta=-0.030941)
[2025-05-06 22:20:07,517] INFO:  Iter 63/100 - Loss: -0.675 (delta=-0.022084)
[2025-05-06 22:20:07,549] INFO:  Iter 64/100 - Loss: -0.700 (delta=-0.025139)
[2025-05-06 22:20:07,585] INFO:  Iter 65/100 - Loss: -0.730 (delta=-0.029542)
[2025-05-06 22:20:07,613] INFO:  Iter 66/100 - Loss: -0.755 (delta=-0.025502)
[2025-05-06 22:20:07,641] INFO:  Iter 67/100 - Loss: -0.782 (delta=-0.027032)
[2025-05-06 22:20:07,666] INFO:  Iter 68/100 - Loss: -0.811 (delta=-0.028273)
[2025-05-06 22:20:07,691] INFO:  Iter 69/100 - Loss: -0.836 (delta=-0.025302)
[2025-05-06 22:20:07,716] INFO:  Iter 70/100 - Loss: -0.857 (delta=-0.021147)
[2025-05-06 22:20:07,742] INFO:  Iter 71/100 - Loss: -0.884 (delta=-0.027023)
[2025-05-06 22:20:07,777] INFO:  Iter 72/100 - Loss: -0.912 (delta=-0.027316)
[2025-05-06 22:20:07,809] INFO:  Iter 73/100 - Loss: -0.942 (delta=-0.030186)
[2025-05-06 22:20:07,844] INFO:  Iter 74/100 - Loss: -0.962 (delta=-0.020679)
[2025-05-06 22:20:07,871] INFO:  Iter 75/100 - Loss: -0.989 (delta=-0.026728)
[2025-05-06 22:20:07,894] INFO:  Iter 76/100 - Loss: -1.017 (delta=-0.028277)
[2025-05-06 22:20:07,919] INFO:  Iter 77/100 - Loss: -1.038 (delta=-0.020573)
[2025-05-06 22:20:07,944] INFO:  Iter 78/100 - Loss: -1.075 (delta=-0.036673)
[2025-05-06 22:20:07,971] INFO:  Iter 79/100 - Loss: -1.094 (delta=-0.019227)
[2025-05-06 22:20:08,002] INFO:  Iter 80/100 - Loss: -1.115 (delta=-0.021233)
[2025-05-06 22:20:08,028] INFO:  Iter 81/100 - Loss: -1.140 (delta=-0.024528)
[2025-05-06 22:20:08,052] INFO:  Iter 82/100 - Loss: -1.175 (delta=-0.035850)
[2025-05-06 22:20:08,078] INFO:  Iter 83/100 - Loss: -1.201 (delta=-0.026009)
[2025-05-06 22:20:08,108] INFO:  Iter 84/100 - Loss: -1.224 (delta=-0.022068)
[2025-05-06 22:20:08,138] INFO:  Iter 85/100 - Loss: -1.251 (delta=-0.026978)
[2025-05-06 22:20:08,168] INFO:  Iter 86/100 - Loss: -1.279 (delta=-0.028657)
[2025-05-06 22:20:08,201] INFO:  Iter 87/100 - Loss: -1.301 (delta=-0.021981)
[2025-05-06 22:20:08,235] INFO:  Iter 88/100 - Loss: -1.332 (delta=-0.031293)
[2025-05-06 22:20:08,265] INFO:  Iter 89/100 - Loss: -1.360 (delta=-0.027145)
[2025-05-06 22:20:08,299] INFO:  Iter 90/100 - Loss: -1.383 (delta=-0.023697)
[2025-05-06 22:20:08,341] INFO:  Iter 91/100 - Loss: -1.412 (delta=-0.028589)
[2025-05-06 22:20:08,412] INFO:  Iter 92/100 - Loss: -1.434 (delta=-0.022538)
[2025-05-06 22:20:08,444] INFO:  Iter 93/100 - Loss: -1.456 (delta=-0.021873)
[2025-05-06 22:20:08,478] INFO:  Iter 94/100 - Loss: -1.487 (delta=-0.031125)
[2025-05-06 22:20:08,512] INFO:  Iter 95/100 - Loss: -1.518 (delta=-0.030298)
[2025-05-06 22:20:08,551] INFO:  Iter 96/100 - Loss: -1.534 (delta=-0.016759)
[2025-05-06 22:20:08,589] INFO:  Iter 97/100 - Loss: -1.571 (delta=-0.036594)
[2025-05-06 22:20:08,626] INFO:  Iter 98/100 - Loss: -1.590 (delta=-0.018609)
[2025-05-06 22:20:08,665] INFO:  Iter 99/100 - Loss: -1.612 (delta=-0.022434)
[2025-05-06 22:20:08,705] INFO:  Iter 100/100 - Loss: -1.643 (delta=-0.030904)
[2025-05-06 22:20:08,747] INFO:  Iter 1/100 - Loss: 0.754 (delta=inf)
[2025-05-06 22:20:08,779] INFO:  Iter 2/100 - Loss: 0.736 (delta=-0.017859)
[2025-05-06 22:20:08,810] INFO:  Iter 3/100 - Loss: 0.720 (delta=-0.016288)
[2025-05-06 22:20:08,841] INFO:  Iter 4/100 - Loss: 0.700 (delta=-0.019124)
[2025-05-06 22:20:08,870] INFO:  Iter 5/100 - Loss: 0.681 (delta=-0.019232)
[2025-05-06 22:20:08,900] INFO:  Iter 6/100 - Loss: 0.661 (delta=-0.019964)
[2025-05-06 22:20:08,929] INFO:  Iter 7/100 - Loss: 0.641 (delta=-0.019945)
[2025-05-06 22:20:08,957] INFO:  Iter 8/100 - Loss: 0.619 (delta=-0.022006)
[2025-05-06 22:20:08,987] INFO:  Iter 9/100 - Loss: 0.601 (delta=-0.018052)
[2025-05-06 22:20:09,012] INFO:  Iter 10/100 - Loss: 0.585 (delta=-0.016490)
[2025-05-06 22:20:09,039] INFO:  Iter 11/100 - Loss: 0.565 (delta=-0.020032)
[2025-05-06 22:20:09,065] INFO:  Iter 12/100 - Loss: 0.546 (delta=-0.018549)
[2025-05-06 22:20:09,091] INFO:  Iter 13/100 - Loss: 0.521 (delta=-0.025085)
[2025-05-06 22:20:09,115] INFO:  Iter 14/100 - Loss: 0.503 (delta=-0.018213)
[2025-05-06 22:20:09,142] INFO:  Iter 15/100 - Loss: 0.480 (delta=-0.023061)
[2025-05-06 22:20:09,168] INFO:  Iter 16/100 - Loss: 0.461 (delta=-0.018815)
[2025-05-06 22:20:09,192] INFO:  Iter 17/100 - Loss: 0.441 (delta=-0.019745)
[2025-05-06 22:20:09,218] INFO:  Iter 18/100 - Loss: 0.419 (delta=-0.022686)
[2025-05-06 22:20:09,243] INFO:  Iter 19/100 - Loss: 0.399 (delta=-0.019812)
[2025-05-06 22:20:09,269] INFO:  Iter 20/100 - Loss: 0.377 (delta=-0.021749)
[2025-05-06 22:20:09,295] INFO:  Iter 21/100 - Loss: 0.350 (delta=-0.027098)
[2025-05-06 22:20:09,324] INFO:  Iter 22/100 - Loss: 0.332 (delta=-0.018018)
[2025-05-06 22:20:09,353] INFO:  Iter 23/100 - Loss: 0.309 (delta=-0.023329)
[2025-05-06 22:20:09,385] INFO:  Iter 24/100 - Loss: 0.286 (delta=-0.022304)
[2025-05-06 22:20:09,412] INFO:  Iter 25/100 - Loss: 0.264 (delta=-0.022303)
[2025-05-06 22:20:09,442] INFO:  Iter 26/100 - Loss: 0.239 (delta=-0.024613)
[2025-05-06 22:20:09,477] INFO:  Iter 27/100 - Loss: 0.218 (delta=-0.020943)
[2025-05-06 22:20:09,510] INFO:  Iter 28/100 - Loss: 0.193 (delta=-0.025624)
[2025-05-06 22:20:09,543] INFO:  Iter 29/100 - Loss: 0.166 (delta=-0.026291)
[2025-05-06 22:20:09,576] INFO:  Iter 30/100 - Loss: 0.147 (delta=-0.019946)
[2025-05-06 22:20:09,602] INFO:  Iter 31/100 - Loss: 0.124 (delta=-0.022078)
[2025-05-06 22:20:09,626] INFO:  Iter 32/100 - Loss: 0.103 (delta=-0.021882)
[2025-05-06 22:20:09,651] INFO:  Iter 33/100 - Loss: 0.078 (delta=-0.024935)
[2025-05-06 22:20:09,676] INFO:  Iter 34/100 - Loss: 0.050 (delta=-0.027990)
[2025-05-06 22:20:09,700] INFO:  Iter 35/100 - Loss: 0.026 (delta=-0.023735)
[2025-05-06 22:20:09,724] INFO:  Iter 36/100 - Loss: 0.007 (delta=-0.019169)
[2025-05-06 22:20:09,748] INFO:  Iter 37/100 - Loss: -0.023 (delta=-0.029295)
[2025-05-06 22:20:09,772] INFO:  Iter 38/100 - Loss: -0.046 (delta=-0.023012)
[2025-05-06 22:20:09,796] INFO:  Iter 39/100 - Loss: -0.074 (delta=-0.028037)
[2025-05-06 22:20:09,820] INFO:  Iter 40/100 - Loss: -0.099 (delta=-0.025396)
[2025-05-06 22:20:09,843] INFO:  Iter 41/100 - Loss: -0.121 (delta=-0.021703)
[2025-05-06 22:20:09,866] INFO:  Iter 42/100 - Loss: -0.147 (delta=-0.026490)
[2025-05-06 22:20:09,889] INFO:  Iter 43/100 - Loss: -0.170 (delta=-0.022457)
[2025-05-06 22:20:09,912] INFO:  Iter 44/100 - Loss: -0.193 (delta=-0.023085)
[2025-05-06 22:20:09,935] INFO:  Iter 45/100 - Loss: -0.221 (delta=-0.028094)
[2025-05-06 22:20:09,957] INFO:  Iter 46/100 - Loss: -0.247 (delta=-0.026060)
[2025-05-06 22:20:09,979] INFO:  Iter 47/100 - Loss: -0.274 (delta=-0.026852)
[2025-05-06 22:20:10,001] INFO:  Iter 48/100 - Loss: -0.296 (delta=-0.022025)
[2025-05-06 22:20:10,023] INFO:  Iter 49/100 - Loss: -0.317 (delta=-0.020847)
[2025-05-06 22:20:10,046] INFO:  Iter 50/100 - Loss: -0.347 (delta=-0.030267)
[2025-05-06 22:20:10,068] INFO:  Iter 51/100 - Loss: -0.373 (delta=-0.026251)
[2025-05-06 22:20:10,090] INFO:  Iter 52/100 - Loss: -0.400 (delta=-0.026690)
[2025-05-06 22:20:10,114] INFO:  Iter 53/100 - Loss: -0.421 (delta=-0.021373)
[2025-05-06 22:20:10,136] INFO:  Iter 54/100 - Loss: -0.451 (delta=-0.029660)
[2025-05-06 22:20:10,158] INFO:  Iter 55/100 - Loss: -0.480 (delta=-0.028754)
[2025-05-06 22:20:10,181] INFO:  Iter 56/100 - Loss: -0.504 (delta=-0.023941)
[2025-05-06 22:20:10,203] INFO:  Iter 57/100 - Loss: -0.531 (delta=-0.027348)
[2025-05-06 22:20:10,226] INFO:  Iter 58/100 - Loss: -0.556 (delta=-0.025239)
[2025-05-06 22:20:10,252] INFO:  Iter 59/100 - Loss: -0.583 (delta=-0.026658)
[2025-05-06 22:20:10,280] INFO:  Iter 60/100 - Loss: -0.606 (delta=-0.022910)
[2025-05-06 22:20:10,304] INFO:  Iter 61/100 - Loss: -0.637 (delta=-0.031735)
[2025-05-06 22:20:10,327] INFO:  Iter 62/100 - Loss: -0.657 (delta=-0.019722)
[2025-05-06 22:20:10,349] INFO:  Iter 63/100 - Loss: -0.691 (delta=-0.033987)
[2025-05-06 22:20:10,372] INFO:  Iter 64/100 - Loss: -0.714 (delta=-0.022531)
[2025-05-06 22:20:10,394] INFO:  Iter 65/100 - Loss: -0.734 (delta=-0.020135)
[2025-05-06 22:20:10,416] INFO:  Iter 66/100 - Loss: -0.765 (delta=-0.031287)
[2025-05-06 22:20:10,439] INFO:  Iter 67/100 - Loss: -0.792 (delta=-0.027309)
[2025-05-06 22:20:10,461] INFO:  Iter 68/100 - Loss: -0.819 (delta=-0.026641)
[2025-05-06 22:20:10,483] INFO:  Iter 69/100 - Loss: -0.846 (delta=-0.027117)
[2025-05-06 22:20:10,505] INFO:  Iter 70/100 - Loss: -0.875 (delta=-0.028894)
[2025-05-06 22:20:10,527] INFO:  Iter 71/100 - Loss: -0.900 (delta=-0.024671)
[2025-05-06 22:20:10,549] INFO:  Iter 72/100 - Loss: -0.922 (delta=-0.022173)
[2025-05-06 22:20:10,572] INFO:  Iter 73/100 - Loss: -0.945 (delta=-0.023526)
[2025-05-06 22:20:10,598] INFO:  Iter 74/100 - Loss: -0.973 (delta=-0.027108)
[2025-05-06 22:20:10,632] INFO:  Iter 75/100 - Loss: -1.007 (delta=-0.034928)
[2025-05-06 22:20:10,666] INFO:  Iter 76/100 - Loss: -1.030 (delta=-0.023031)
[2025-05-06 22:20:10,701] INFO:  Iter 77/100 - Loss: -1.053 (delta=-0.022058)
[2025-05-06 22:20:10,741] INFO:  Iter 78/100 - Loss: -1.077 (delta=-0.024819)
[2025-05-06 22:20:10,780] INFO:  Iter 79/100 - Loss: -1.108 (delta=-0.031006)
[2025-05-06 22:20:10,812] INFO:  Iter 80/100 - Loss: -1.130 (delta=-0.021378)
[2025-05-06 22:20:10,856] INFO:  Iter 81/100 - Loss: -1.156 (delta=-0.026461)
[2025-05-06 22:20:10,897] INFO:  Iter 82/100 - Loss: -1.191 (delta=-0.034885)
[2025-05-06 22:20:10,920] INFO:  Iter 83/100 - Loss: -1.208 (delta=-0.017056)
[2025-05-06 22:20:10,943] INFO:  Iter 84/100 - Loss: -1.239 (delta=-0.030509)
[2025-05-06 22:20:10,966] INFO:  Iter 85/100 - Loss: -1.260 (delta=-0.021466)
[2025-05-06 22:20:10,998] INFO:  Iter 86/100 - Loss: -1.289 (delta=-0.028479)
[2025-05-06 22:20:11,028] INFO:  Iter 87/100 - Loss: -1.311 (delta=-0.022009)
[2025-05-06 22:20:11,058] INFO:  Iter 88/100 - Loss: -1.343 (delta=-0.032809)
[2025-05-06 22:20:11,091] INFO:  Iter 89/100 - Loss: -1.365 (delta=-0.021990)
[2025-05-06 22:20:11,125] INFO:  Iter 90/100 - Loss: -1.384 (delta=-0.018096)
[2025-05-06 22:20:11,163] INFO:  Iter 91/100 - Loss: -1.423 (delta=-0.039097)
[2025-05-06 22:20:11,201] INFO:  Iter 92/100 - Loss: -1.453 (delta=-0.030427)
[2025-05-06 22:20:11,239] INFO:  Iter 93/100 - Loss: -1.470 (delta=-0.016713)
[2025-05-06 22:20:11,282] INFO:  Iter 94/100 - Loss: -1.497 (delta=-0.027562)
[2025-05-06 22:20:11,369] INFO:  Iter 95/100 - Loss: -1.518 (delta=-0.020692)
[2025-05-06 22:20:11,398] INFO:  Iter 96/100 - Loss: -1.546 (delta=-0.027763)
[2025-05-06 22:20:11,426] INFO:  Iter 97/100 - Loss: -1.577 (delta=-0.031582)
[2025-05-06 22:20:11,458] INFO:  Iter 98/100 - Loss: -1.597 (delta=-0.019179)
[2025-05-06 22:20:11,498] INFO:  Iter 99/100 - Loss: -1.623 (delta=-0.026677)
[2025-05-06 22:20:11,534] INFO:  Iter 100/100 - Loss: -1.649 (delta=-0.026067)
[2025-05-06 22:20:11,578] INFO:  Iter 1/100 - Loss: 0.753 (delta=inf)
[2025-05-06 22:20:11,610] INFO:  Iter 2/100 - Loss: 0.733 (delta=-0.019320)
[2025-05-06 22:20:11,645] INFO:  Iter 3/100 - Loss: 0.716 (delta=-0.017652)
[2025-05-06 22:20:11,674] INFO:  Iter 4/100 - Loss: 0.697 (delta=-0.018872)
[2025-05-06 22:20:11,701] INFO:  Iter 5/100 - Loss: 0.680 (delta=-0.016599)
[2025-05-06 22:20:11,729] INFO:  Iter 6/100 - Loss: 0.660 (delta=-0.020026)
[2025-05-06 22:20:11,756] INFO:  Iter 7/100 - Loss: 0.644 (delta=-0.016300)
[2025-05-06 22:20:11,782] INFO:  Iter 8/100 - Loss: 0.620 (delta=-0.023658)
[2025-05-06 22:20:11,807] INFO:  Iter 9/100 - Loss: 0.601 (delta=-0.019182)
[2025-05-06 22:20:11,833] INFO:  Iter 10/100 - Loss: 0.578 (delta=-0.022580)
[2025-05-06 22:20:11,858] INFO:  Iter 11/100 - Loss: 0.567 (delta=-0.011902)
[2025-05-06 22:20:11,883] INFO:  Iter 12/100 - Loss: 0.542 (delta=-0.024431)
[2025-05-06 22:20:11,910] INFO:  Iter 13/100 - Loss: 0.517 (delta=-0.024749)
[2025-05-06 22:20:11,934] INFO:  Iter 14/100 - Loss: 0.503 (delta=-0.014155)
[2025-05-06 22:20:11,958] INFO:  Iter 15/100 - Loss: 0.482 (delta=-0.021423)
[2025-05-06 22:20:11,984] INFO:  Iter 16/100 - Loss: 0.458 (delta=-0.023660)
[2025-05-06 22:20:12,013] INFO:  Iter 17/100 - Loss: 0.439 (delta=-0.019464)
[2025-05-06 22:20:12,043] INFO:  Iter 18/100 - Loss: 0.416 (delta=-0.022466)
[2025-05-06 22:20:12,072] INFO:  Iter 19/100 - Loss: 0.394 (delta=-0.022307)
[2025-05-06 22:20:12,108] INFO:  Iter 20/100 - Loss: 0.373 (delta=-0.021372)
[2025-05-06 22:20:12,140] INFO:  Iter 21/100 - Loss: 0.352 (delta=-0.020358)
[2025-05-06 22:20:12,167] INFO:  Iter 22/100 - Loss: 0.327 (delta=-0.024961)
[2025-05-06 22:20:12,195] INFO:  Iter 23/100 - Loss: 0.308 (delta=-0.019156)
[2025-05-06 22:20:12,221] INFO:  Iter 24/100 - Loss: 0.282 (delta=-0.026416)
[2025-05-06 22:20:12,247] INFO:  Iter 25/100 - Loss: 0.263 (delta=-0.018480)
[2025-05-06 22:20:12,368] INFO:  Iter 26/100 - Loss: 0.237 (delta=-0.025723)
[2025-05-06 22:20:12,420] INFO:  Iter 27/100 - Loss: 0.218 (delta=-0.019851)
[2025-05-06 22:20:12,448] INFO:  Iter 28/100 - Loss: 0.192 (delta=-0.025939)
[2025-05-06 22:20:12,472] INFO:  Iter 29/100 - Loss: 0.170 (delta=-0.021598)
[2025-05-06 22:20:12,499] INFO:  Iter 30/100 - Loss: 0.145 (delta=-0.025017)
[2025-05-06 22:20:12,522] INFO:  Iter 31/100 - Loss: 0.121 (delta=-0.024064)
[2025-05-06 22:20:12,546] INFO:  Iter 32/100 - Loss: 0.098 (delta=-0.022967)
[2025-05-06 22:20:12,570] INFO:  Iter 33/100 - Loss: 0.075 (delta=-0.022712)
[2025-05-06 22:20:12,597] INFO:  Iter 34/100 - Loss: 0.048 (delta=-0.027387)
[2025-05-06 22:20:12,621] INFO:  Iter 35/100 - Loss: 0.027 (delta=-0.020518)
[2025-05-06 22:20:12,646] INFO:  Iter 36/100 - Loss: -0.001 (delta=-0.028197)
[2025-05-06 22:20:12,671] INFO:  Iter 37/100 - Loss: -0.025 (delta=-0.024021)
[2025-05-06 22:20:12,697] INFO:  Iter 38/100 - Loss: -0.048 (delta=-0.022677)
[2025-05-06 22:20:12,725] INFO:  Iter 39/100 - Loss: -0.070 (delta=-0.022299)
[2025-05-06 22:20:12,755] INFO:  Iter 40/100 - Loss: -0.098 (delta=-0.027831)
[2025-05-06 22:20:12,784] INFO:  Iter 41/100 - Loss: -0.126 (delta=-0.028602)
[2025-05-06 22:20:12,813] INFO:  Iter 42/100 - Loss: -0.146 (delta=-0.019922)
[2025-05-06 22:20:12,846] INFO:  Iter 43/100 - Loss: -0.177 (delta=-0.030735)
[2025-05-06 22:20:12,873] INFO:  Iter 44/100 - Loss: -0.202 (delta=-0.025020)
[2025-05-06 22:20:12,899] INFO:  Iter 45/100 - Loss: -0.225 (delta=-0.022919)
[2025-05-06 22:20:12,926] INFO:  Iter 46/100 - Loss: -0.246 (delta=-0.020884)
[2025-05-06 22:20:12,951] INFO:  Iter 47/100 - Loss: -0.273 (delta=-0.027560)
[2025-05-06 22:20:12,975] INFO:  Iter 48/100 - Loss: -0.302 (delta=-0.028431)
[2025-05-06 22:20:13,002] INFO:  Iter 49/100 - Loss: -0.324 (delta=-0.022559)
[2025-05-06 22:20:13,026] INFO:  Iter 50/100 - Loss: -0.351 (delta=-0.026921)
[2025-05-06 22:20:13,052] INFO:  Iter 51/100 - Loss: -0.382 (delta=-0.030939)
[2025-05-06 22:20:13,076] INFO:  Iter 52/100 - Loss: -0.405 (delta=-0.023013)
[2025-05-06 22:20:13,102] INFO:  Iter 53/100 - Loss: -0.426 (delta=-0.021061)
[2025-05-06 22:20:13,129] INFO:  Iter 54/100 - Loss: -0.457 (delta=-0.031232)
[2025-05-06 22:20:13,156] INFO:  Iter 55/100 - Loss: -0.485 (delta=-0.027971)
[2025-05-06 22:20:13,181] INFO:  Iter 56/100 - Loss: -0.510 (delta=-0.024280)
[2025-05-06 22:20:13,205] INFO:  Iter 57/100 - Loss: -0.537 (delta=-0.027194)
[2025-05-06 22:20:13,230] INFO:  Iter 58/100 - Loss: -0.562 (delta=-0.024735)

In [12]:
bayesian_digital_twins

{1: <radp.digital_twin.rf.bayesian.bayesian_engine.BayesianDigitalTwin at 0x17da01890>,
 2: <radp.digital_twin.rf.bayesian.bayesian_engine.BayesianDigitalTwin at 0x3038425d0>,
 3: <radp.digital_twin.rf.bayesian.bayesian_engine.BayesianDigitalTwin at 0x3044d3750>}

In [22]:
params2 = {
    "ue_tracks_generation": {
            "params": {
                "simulation_duration": 3600,
                "simulation_time_interval_seconds": 0.01,
                "num_ticks": 50,
                "num_batches": 1,
                "ue_class_distribution": {
                    "stationary": {
                        "count": 10,
                        "velocity": 0,
                        "velocity_variance": 1
                    },
                    "pedestrian": {
                        "count": 5,
                        "velocity": 2,
                        "velocity_variance": 1
                    },
                    "cyclist": {
                        "count": 7,
                        "velocity": 5,
                        "velocity_variance": 1
                    },
                    "car": {
                        "count": 10,
                        "velocity": 20,
                        "velocity_variance": 1
                    }
                },
                "lat_lon_boundaries": {
                    "min_lat": -90,
                    "max_lat": 90,
                    "min_lon": -180,
                    "max_lon": 180
                },
                "gauss_markov_params": {
                    "alpha": 0.8,
                    "variance": 0.5,
                    "rng_seed": 42,
                    "lon_x_dims": 100,
                    "lon_y_dims": 100,
                    "// TODO": "Account for supporting the user choosing the anchor_loc and cov_around_anchor.",
                    "// Current implementation": "the UE Tracks generator will not be using these values.",
                    "// anchor_loc": {},
                    "// cov_around_anchor": {}
            }
        }
    }
}

In [23]:
def _preprocess_prediction_data(pred_data,topology) -> pd.DataFrame:
        data = _prepare_all_UEs_from_all_cells_df(pred_data,topology)

        data["log_distance"] = data.apply(
            lambda row: GISTools.get_log_distance(
                row["latitude"], row["longitude"], row["cell_lat"], row["cell_lon"]
            ),
            axis=1,
        )
        data["cell_rxpwr_dbm"] = data.apply(
            lambda row: calculate_received_power(
                row["log_distance"], row["cell_carrier_freq_mhz"]
            ),
            axis=1,
        )

        data["relative_bearing"] = data.apply(
            lambda row: GISTools.get_relative_bearing(
                row["cell_az_deg"],
                row["cell_lat"],
                row["cell_lon"],
                row["latitude"],
                row["longitude"],
            ),
            axis=1,
        )
        return data

In [24]:
# Prediction
def _predictions(pred_data,topology,bayesian_digital_twins) -> Tuple[pd.DataFrame, pd.DataFrame]:
        """
        Predicts the received power for each User Equipment (UE) at different locations and ticks using Bayesian Digital Twins.
        It then determines the best cell for each UE to attach based on the predicted power values.
        """
        prediction_data = _preprocess_prediction_data(pred_data,topology)
        full_prediction_df = pd.DataFrame()

        # Loop over each 'tick'
        for tick, tick_df in prediction_data.groupby("tick"):
            # Loop over each 'cell_id' within the current 'tick'
            for cell_id, cell_df in tick_df.groupby("cell_id"):
                # Check if the Bayesian model for this cell_id exists
                if cell_id in bayesian_digital_twins:
                    # Perform the Bayesian prediction
                    pred_means_percell, _ = bayesian_digital_twins[
                        cell_id
                    ].predict_distributed_gpmodel(prediction_dfs=[cell_df])

                    # Assuming 'pred_means_percell' returns a list of predictions corresponding to the DataFrame index
                    cell_df["pred_means"] = pred_means_percell[0]

                    # Include additional necessary columns for the final DataFrame
                    cell_df["tick"] = tick
                    cell_df["cell_id"] = cell_id

                    # Append the predictions to the full DataFrame
                    full_prediction_df = pd.concat(
                        [full_prediction_df, cell_df], ignore_index=True
                    )
                else:
                    # Handle missing models, e.g., log a warning or initialize a default model
                    print(
                        f"No model available for cell_id {cell_id}, skipping prediction."
                    )

        full_prediction_df = full_prediction_df.rename(
            columns={"latitude": "loc_y", "longitude": "loc_x"}
        )
        predicted = perform_attachment(full_prediction_df, topology)

        return predicted, full_prediction_df

In [25]:
prediction_data = get_ue_data(params2)

In [26]:
predictions, full_prediction_df = _predictions(
    pred_data=prediction_data,
    topology=topology,
    bayesian_digital_twins = bayesian_digital_twins
)

Combined DataFrame:       mock_ue_id   longitude   latitude  tick  cell_lat  cell_lon  cell_id  \
0              0   48.510339 -16.462645     0     -90.0    -180.0        1
1              0   48.510339 -16.462645     0       0.0       0.0        2
2              0   48.510339 -16.462645     0      90.0     180.0        3
3              1   19.286613  63.617111     0     -90.0    -180.0        1
4              1   19.286613  63.617111     0       0.0       0.0        2
...          ...         ...        ...   ...       ...       ...      ...
4795          30  -64.060471  70.447505    49       0.0       0.0        2
4796          30  -64.060471  70.447505    49      90.0     180.0        3
4797          31 -152.742476  51.756565    49     -90.0    -180.0        1
4798          31 -152.742476  51.756565    49       0.0       0.0        2
4799          31 -152.742476  51.756565    49      90.0     180.0        3

      cell_az_deg  cell_carrier_freq_mhz
0               0                   2800
1             120                   2800
2             240                   2800
3               0                   2800
4             120                   2800
...           ...                    ...
4795          120                   2800
4796          240                   2800
4797            0                   2800
4798          120                   2800
4799          240                   2800

[4800 rows x 9 columns]

/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/gpytorch/distributions/multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(

### Disect all the codes from MRO and put it to radp_library.py

In [9]:
bayesian_digital_twins = {}

In [10]:
update_data = pd.read_csv('/Users/tanzimfarhan/Downloads/combined_data_dump.csv')
update_data

       latitude   longitude  cell_rxpower_dbm
0     59.806764  -22.625309        100.788266
1     59.806764  -22.625309        100.788266
2     59.806764  -22.625309        100.788266
3     54.857584  119.764151         99.608310
4     54.857584  119.764151         99.608310
...         ...         ...               ...
5995 -26.656397  -16.480045         99.734971
5996 -26.656397  -16.480045         99.734971
5997  63.970820   34.222834        100.191265
5998  63.970820   34.222834        100.191265
5999  63.970820   34.222834        100.191265

[6000 rows x 3 columns]

In [11]:
def _preprocess_ue_update_data(update_data,topology) -> pd.DataFrame:
        data = _prepare_all_UEs_from_all_cells_df(update_data,topology)
        data["log_distance"] = data.apply(
            lambda row: GISTools.get_log_distance(
                row["latitude"], row["longitude"], row["cell_lat"], row["cell_lon"]
            ),
            axis=1,
        )

        update_per_cell_df = [x for _, x in data.groupby("cell_id")]
        n_cell = len(topology.index)

        metadata_df = pd.DataFrame(
            {
                "cell_id": [cell_id for cell_id in topology.cell_id],
                "idx": [i + 1 for i in range(n_cell)],
            }
        )
        idx_cell_id_mapping = dict(zip(metadata_df.idx, metadata_df.cell_id))

        n_samples_update = []
        for df in update_per_cell_df:
            n_samples_update.append(df.shape[0])

        update_per_cell_df_processed = []
        for i in range(n_cell):
            update_per_cell_df_processed.append(
                get_percell_data(
                    data_in=update_per_cell_df[i],
                    choose_strongest_samples_percell=False,
                    n_samples=n_samples_update[i],
                )[0][0]
            )

        update_data = {}

        for i, df in enumerate(update_per_cell_df_processed):
            update_cell_id = idx_cell_id_mapping[i + 1]
            update_data[update_cell_id] = df

        for update_cell_id, update_data_idx in update_data.items():
            update_data_idx["cell_id"] = update_cell_id
            update_data_idx["cell_lat"] = topology[
                topology["cell_id"] == update_cell_id
            ]["cell_lat"].values[0]
            update_data_idx["cell_lon"] = topology[
                topology["cell_id"] == update_cell_id
            ]["cell_lon"].values[0]
            update_data_idx["cell_az_deg"] = topology[
                topology["cell_id"] == update_cell_id
            ]["cell_az_deg"].values[0]
            update_data_idx["cell_carrier_freq_mhz"] = topology[
                topology["cell_id"] == update_cell_id
            ]["cell_carrier_freq_mhz"].values[0]
            update_data_idx["relative_bearing"] = [
                GISTools.get_relative_bearing(
                    update_data_idx["cell_az_deg"].values[0],
                    update_data_idx["cell_lat"].values[0],
                    update_data_idx["cell_lon"].values[0],
                    lat,
                    lon,
                )
                for lat, lon in zip(
                    update_data_idx["latitude"], update_data_idx["longitude"]
                )
            ]
        return update_data

In [16]:
def train_or_update_rf_twin(new_data: pd.DataFrame,topology: pd.DataFrame, bayesian_digital_twins):
        try:
            if not isinstance(new_data, pd.DataFrame):
                raise TypeError("The input 'new_data' must be a pandas DataFrame.")
            
            new_data = new_data.rename(
                columns={"cell_rxpower_dbm": "cell_rxpwr_dbm"}
            )
            expected_columns = {"longitude", "latitude", "cell_rxpwr_dbm"}
            if not expected_columns.issubset(new_data.columns):
                raise ValueError(
                    f"The input DataFrame must contain the following columns: {expected_columns}"
                )

            if bayesian_digital_twins:
                update_data = new_data
                updated_data = _preprocess_ue_update_data(update_data, topology)
                updated_data_list = list(updated_data.values())
                print("Updated_List ",updated_data_list)

                for data_idx, update_data_df in enumerate(updated_data_list):
                    update_cell_id = data_idx + 1
                    if update_cell_id in bayesian_digital_twins:
                        bayesian_digital_twins[
                            update_cell_id
                        ].update_trained_gpmodel([update_data_df])
            else:
                print(
                    "No Bayesian Digital Twins available for update. Training from scratch."
                )
                new_data = new_data.drop(
                    columns=["cell_rxpower_dbm"], errors="ignore"
                )
                _training(bayesian_digital_twins,maxiter=100, train_data=new_data,topology = topology)
        except TypeError as te:
            print(f"TypeError: {te}")
        except ValueError as ve:
            print(f"ValueError: {ve}")
        except KeyError as ke:
            print(f"KeyError: {ke}")
        except Exception as e:
            print(f"An unexpected error occurred: {e}")

In [13]:
updates = train_or_update_rf_twin(update_data,topology,bayesian_digital_twins)

No Bayesian Digital Twins available for update. Training from scratch.
Combined DataFrame:         latitude  longitude  cell_rxpwr_dbm  cell_lat  cell_lon  cell_id  \
0      59.806764 -22.625309      100.788266     -90.0    -180.0        1
1      59.806764 -22.625309      100.788266       0.0       0.0        2
2      59.806764 -22.625309      100.788266      90.0     180.0        3
3      59.806764 -22.625309      100.788266     -90.0    -180.0        1
4      59.806764 -22.625309      100.788266       0.0       0.0        2
...          ...        ...             ...       ...       ...      ...
17995  63.970820  34.222834      100.191265       0.0       0.0        2
17996  63.970820  34.222834      100.191265      90.0     180.0        3
17997  63.970820  34.222834      100.191265     -90.0    -180.0        1
17998  63.970820  34.222834      100.191265       0.0       0.0        2
17999  63.970820  34.222834      100.191265      90.0     180.0        3

       cell_az_deg  cell_carrier_freq_mhz
0                0                   2800
1              120                   2800
2              240                   2800
3                0                   2800
4              120                   2800
...            ...                    ...
17995          120                   2800
17996          240                   2800
17997            0                   2800
17998          120                   2800
17999          240                   2800

[18000 rows x 8 columns]

[2025-05-06 22:49:35,365] INFO:  Iter 1/100 - Loss: 0.758 (delta=inf)
[2025-05-06 22:49:35,846] INFO:  Iter 2/100 - Loss: 0.739 (delta=-0.018518)
[2025-05-06 22:49:36,264] INFO:  Iter 3/100 - Loss: 0.721 (delta=-0.018669)
[2025-05-06 22:49:36,694] INFO:  Iter 4/100 - Loss: 0.702 (delta=-0.018836)
[2025-05-06 22:49:37,108] INFO:  Iter 5/100 - Loss: 0.683 (delta=-0.019022)
[2025-05-06 22:49:37,519] INFO:  Iter 6/100 - Loss: 0.664 (delta=-0.019220)
[2025-05-06 22:49:38,073] INFO:  Iter 7/100 - Loss: 0.644 (delta=-0.019418)
[2025-05-06 22:49:38,499] INFO:  Iter 8/100 - Loss: 0.625 (delta=-0.019617)
[2025-05-06 22:49:38,904] INFO:  Iter 9/100 - Loss: 0.605 (delta=-0.019824)
[2025-05-06 22:49:39,318] INFO:  Iter 10/100 - Loss: 0.585 (delta=-0.020026)
[2025-05-06 22:49:39,877] INFO:  Iter 11/100 - Loss: 0.565 (delta=-0.020224)
[2025-05-06 22:49:40,282] INFO:  Iter 12/100 - Loss: 0.544 (delta=-0.020427)
[2025-05-06 22:49:40,687] INFO:  Iter 13/100 - Loss: 0.523 (delta=-0.020639)
[2025-05-06 22:49:41,093] INFO:  Iter 14/100 - Loss: 0.503 (delta=-0.020848)
[2025-05-06 22:49:41,516] INFO:  Iter 15/100 - Loss: 0.482 (delta=-0.021048)
[2025-05-06 22:49:42,061] INFO:  Iter 16/100 - Loss: 0.460 (delta=-0.021244)
[2025-05-06 22:49:42,625] INFO:  Iter 17/100 - Loss: 0.439 (delta=-0.021461)
[2025-05-06 22:49:43,032] INFO:  Iter 18/100 - Loss: 0.417 (delta=-0.021658)
[2025-05-06 22:49:43,638] INFO:  Iter 19/100 - Loss: 0.395 (delta=-0.021800)
[2025-05-06 22:49:44,049] INFO:  Iter 20/100 - Loss: 0.373 (delta=-0.022023)
[2025-05-06 22:49:44,482] INFO:  Iter 21/100 - Loss: 0.351 (delta=-0.022159)
[2025-05-06 22:49:44,908] INFO:  Iter 22/100 - Loss: 0.329 (delta=-0.022336)
[2025-05-06 22:49:45,329] INFO:  Iter 23/100 - Loss: 0.306 (delta=-0.022557)
[2025-05-06 22:49:45,775] INFO:  Iter 24/100 - Loss: 0.284 (delta=-0.022763)
[2025-05-06 22:49:46,333] INFO:  Iter 25/100 - Loss: 0.261 (delta=-0.022848)
[2025-05-06 22:49:46,807] INFO:  Iter 26/100 - Loss: 0.238 (delta=-0.023108)
[2025-05-06 22:49:47,374] INFO:  Iter 27/100 - Loss: 0.214 (delta=-0.023217)
[2025-05-06 22:49:47,819] INFO:  Iter 28/100 - Loss: 0.191 (delta=-0.023431)
[2025-05-06 22:49:48,233] INFO:  Iter 29/100 - Loss: 0.167 (delta=-0.023542)
[2025-05-06 22:49:48,661] INFO:  Iter 30/100 - Loss: 0.144 (delta=-0.023688)
[2025-05-06 22:49:49,073] INFO:  Iter 31/100 - Loss: 0.120 (delta=-0.023792)
[2025-05-06 22:49:49,503] INFO:  Iter 32/100 - Loss: 0.096 (delta=-0.024052)
[2025-05-06 22:49:49,916] INFO:  Iter 33/100 - Loss: 0.072 (delta=-0.024133)
[2025-05-06 22:49:50,334] INFO:  Iter 34/100 - Loss: 0.048 (delta=-0.024236)
[2025-05-06 22:49:50,739] INFO:  Iter 35/100 - Loss: 0.023 (delta=-0.024419)
[2025-05-06 22:49:51,149] INFO:  Iter 36/100 - Loss: -0.001 (delta=-0.024513)
[2025-05-06 22:49:51,553] INFO:  Iter 37/100 - Loss: -0.026 (delta=-0.024620)
[2025-05-06 22:49:51,957] INFO:  Iter 38/100 - Loss: -0.051 (delta=-0.024790)
[2025-05-06 22:49:52,377] INFO:  Iter 39/100 - Loss: -0.076 (delta=-0.024857)
[2025-05-06 22:49:52,781] INFO:  Iter 40/100 - Loss: -0.101 (delta=-0.025052)
[2025-05-06 22:49:53,188] INFO:  Iter 41/100 - Loss: -0.126 (delta=-0.025115)
[2025-05-06 22:49:53,590] INFO:  Iter 42/100 - Loss: -0.151 (delta=-0.025146)
[2025-05-06 22:49:53,992] INFO:  Iter 43/100 - Loss: -0.176 (delta=-0.025256)
[2025-05-06 22:49:54,405] INFO:  Iter 44/100 - Loss: -0.202 (delta=-0.025417)
[2025-05-06 22:49:54,806] INFO:  Iter 45/100 - Loss: -0.227 (delta=-0.025455)
[2025-05-06 22:49:55,210] INFO:  Iter 46/100 - Loss: -0.253 (delta=-0.025487)
[2025-05-06 22:49:55,623] INFO:  Iter 47/100 - Loss: -0.278 (delta=-0.025696)
[2025-05-06 22:49:56,024] INFO:  Iter 48/100 - Loss: -0.304 (delta=-0.025693)
[2025-05-06 22:49:56,434] INFO:  Iter 49/100 - Loss: -0.330 (delta=-0.025629)
[2025-05-06 22:49:56,838] INFO:  Iter 50/100 - Loss: -0.356 (delta=-0.025953)
[2025-05-06 22:49:57,249] INFO:  Iter 51/100 - Loss: -0.381 (delta=-0.025891)
[2025-05-06 22:49:57,655] INFO:  Iter 52/100 - Loss: -0.407 (delta=-0.025927)
[2025-05-06 22:49:58,057] INFO:  Iter 53/100 - Loss: -0.433 (delta=-0.025934)
[2025-05-06 22:49:58,465] INFO:  Iter 54/100 - Loss: -0.459 (delta=-0.026155)
[2025-05-06 22:49:58,865] INFO:  Iter 55/100 - Loss: -0.486 (delta=-0.026121)
[2025-05-06 22:49:59,271] INFO:  Iter 56/100 - Loss: -0.512 (delta=-0.026171)
[2025-05-06 22:49:59,672] INFO:  Iter 57/100 - Loss: -0.538 (delta=-0.026220)
[2025-05-06 22:50:00,082] INFO:  Iter 58/100 - Loss: -0.564 (delta=-0.026209)
[2025-05-06 22:50:00,489] INFO:  Iter 59/100 - Loss: -0.591 (delta=-0.026305)
[2025-05-06 22:50:00,893] INFO:  Iter 60/100 - Loss: -0.617 (delta=-0.026142)
[2025-05-06 22:50:01,298] INFO:  Iter 61/100 - Loss: -0.643 (delta=-0.026253)
[2025-05-06 22:50:01,703] INFO:  Iter 62/100 - Loss: -0.669 (delta=-0.026480)
[2025-05-06 22:50:02,103] INFO:  Iter 63/100 - Loss: -0.696 (delta=-0.026425)
[2025-05-06 22:50:02,512] INFO:  Iter 64/100 - Loss: -0.722 (delta=-0.026200)
[2025-05-06 22:50:02,915] INFO:  Iter 65/100 - Loss: -0.749 (delta=-0.026675)
[2025-05-06 22:50:03,325] INFO:  Iter 66/100 - Loss: -0.775 (delta=-0.026161)
[2025-05-06 22:50:03,727] INFO:  Iter 67/100 - Loss: -0.801 (delta=-0.026533)
[2025-05-06 22:50:04,130] INFO:  Iter 68/100 - Loss: -0.828 (delta=-0.026561)
[2025-05-06 22:50:04,533] INFO:  Iter 69/100 - Loss: -0.854 (delta=-0.026212)
[2025-05-06 22:50:04,940] INFO:  Iter 70/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:05,346] INFO:  Iter 71/100 - Loss: -0.907 (delta=nan)
[2025-05-06 22:50:05,747] INFO:  Iter 72/100 - Loss: -0.934 (delta=-0.026432)
[2025-05-06 22:50:06,150] INFO:  Iter 73/100 - Loss: -0.960 (delta=-0.026282)
[2025-05-06 22:50:06,559] INFO:  Iter 74/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:06,959] INFO:  Iter 75/100 - Loss: -1.013 (delta=nan)
[2025-05-06 22:50:07,368] INFO:  Iter 76/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:08,102] INFO:  Iter 77/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:08,533] INFO:  Iter 78/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:08,936] INFO:  Iter 79/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:09,354] INFO:  Iter 80/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:09,830] INFO:  Iter 81/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:10,359] INFO:  Iter 82/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:10,813] INFO:  Iter 83/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:11,217] INFO:  Iter 84/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:11,622] INFO:  Iter 85/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:12,027] INFO:  Iter 86/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:12,659] INFO:  Iter 87/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:13,125] INFO:  Iter 88/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:13,566] INFO:  Iter 89/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:14,014] INFO:  Iter 90/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:14,456] INFO:  Iter 91/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:15,059] INFO:  Iter 92/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:15,487] INFO:  Iter 93/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:15,949] INFO:  Iter 94/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:16,375] INFO:  Iter 95/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:16,827] INFO:  Iter 96/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:17,330] INFO:  Iter 97/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:17,873] INFO:  Iter 98/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:18,284] INFO:  Iter 99/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:18,713] INFO:  Iter 100/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:19,172] INFO:  Iter 1/100 - Loss: 0.747 (delta=inf)
[2025-05-06 22:50:19,594] INFO:  Iter 2/100 - Loss: 0.729 (delta=-0.018271)
[2025-05-06 22:50:20,005] INFO:  Iter 3/100 - Loss: 0.710 (delta=-0.018454)
[2025-05-06 22:50:20,414] INFO:  Iter 4/100 - Loss: 0.691 (delta=-0.018647)
[2025-05-06 22:50:20,833] INFO:  Iter 5/100 - Loss: 0.673 (delta=-0.018842)
[2025-05-06 22:50:21,245] INFO:  Iter 6/100 - Loss: 0.654 (delta=-0.019048)
[2025-05-06 22:50:21,664] INFO:  Iter 7/100 - Loss: 0.634 (delta=-0.019246)
[2025-05-06 22:50:22,073] INFO:  Iter 8/100 - Loss: 0.615 (delta=-0.019445)
[2025-05-06 22:50:22,482] INFO:  Iter 9/100 - Loss: 0.595 (delta=-0.019645)
[2025-05-06 22:50:22,894] INFO:  Iter 10/100 - Loss: 0.575 (delta=-0.019842)
[2025-05-06 22:50:23,311] INFO:  Iter 11/100 - Loss: 0.555 (delta=-0.020045)
[2025-05-06 22:50:23,726] INFO:  Iter 12/100 - Loss: 0.535 (delta=-0.020245)
[2025-05-06 22:50:24,130] INFO:  Iter 13/100 - Loss: 0.515 (delta=-0.020444)
[2025-05-06 22:50:24,528] INFO:  Iter 14/100 - Loss: 0.494 (delta=-0.020648)
[2025-05-06 22:50:24,942] INFO:  Iter 15/100 - Loss: 0.473 (delta=-0.020843)
[2025-05-06 22:50:25,368] INFO:  Iter 16/100 - Loss: 0.452 (delta=-0.021043)
[2025-05-06 22:50:25,816] INFO:  Iter 17/100 - Loss: 0.431 (delta=-0.021240)
[2025-05-06 22:50:26,289] INFO:  Iter 18/100 - Loss: 0.409 (delta=-0.021434)
[2025-05-06 22:50:26,772] INFO:  Iter 19/100 - Loss: 0.388 (delta=-0.021624)
[2025-05-06 22:50:27,264] INFO:  Iter 20/100 - Loss: 0.366 (delta=-0.021817)
[2025-05-06 22:50:27,661] INFO:  Iter 21/100 - Loss: 0.344 (delta=-0.022008)
[2025-05-06 22:50:28,079] INFO:  Iter 22/100 - Loss: 0.322 (delta=-0.022204)
[2025-05-06 22:50:28,504] INFO:  Iter 23/100 - Loss: 0.299 (delta=-0.022380)
[2025-05-06 22:50:28,924] INFO:  Iter 24/100 - Loss: 0.277 (delta=-0.022566)
[2025-05-06 22:50:29,334] INFO:  Iter 25/100 - Loss: 0.254 (delta=-0.022757)
[2025-05-06 22:50:29,747] INFO:  Iter 26/100 - Loss: 0.231 (delta=-0.022929)
[2025-05-06 22:50:30,153] INFO:  Iter 27/100 - Loss: 0.208 (delta=-0.023108)
[2025-05-06 22:50:30,574] INFO:  Iter 28/100 - Loss: 0.185 (delta=-0.023265)
[2025-05-06 22:50:31,034] INFO:  Iter 29/100 - Loss: 0.161 (delta=-0.023384)
[2025-05-06 22:50:31,476] INFO:  Iter 30/100 - Loss: 0.138 (delta=-0.023594)
[2025-05-06 22:50:32,265] INFO:  Iter 31/100 - Loss: 0.114 (delta=-0.023686)
[2025-05-06 22:50:32,751] INFO:  Iter 32/100 - Loss: 0.090 (delta=-0.023900)
[2025-05-06 22:50:33,162] INFO:  Iter 33/100 - Loss: 0.066 (delta=-0.024021)
[2025-05-06 22:50:33,603] INFO:  Iter 34/100 - Loss: 0.042 (delta=-0.024183)
[2025-05-06 22:50:34,092] INFO:  Iter 35/100 - Loss: 0.018 (delta=-0.024285)
[2025-05-06 22:50:34,534] INFO:  Iter 36/100 - Loss: -0.007 (delta=-0.024405)
[2025-05-06 22:50:34,990] INFO:  Iter 37/100 - Loss: -0.031 (delta=-0.024596)
[2025-05-06 22:50:35,483] INFO:  Iter 38/100 - Loss: -0.056 (delta=-0.024660)
[2025-05-06 22:50:35,964] INFO:  Iter 39/100 - Loss: -0.081 (delta=-0.024811)
[2025-05-06 22:50:36,381] INFO:  Iter 40/100 - Loss: -0.106 (delta=-0.024878)
[2025-05-06 22:50:36,976] INFO:  Iter 41/100 - Loss: -0.131 (delta=-0.025022)
[2025-05-06 22:50:37,382] INFO:  Iter 42/100 - Loss: -0.156 (delta=-0.025097)
[2025-05-06 22:50:38,007] INFO:  Iter 43/100 - Loss: -0.181 (delta=-0.025248)
[2025-05-06 22:50:38,409] INFO:  Iter 44/100 - Loss: -0.206 (delta=-0.025298)
[2025-05-06 22:50:38,811] INFO:  Iter 45/100 - Loss: -0.232 (delta=-0.025338)
[2025-05-06 22:50:39,210] INFO:  Iter 46/100 - Loss: -0.257 (delta=-0.025498)
[2025-05-06 22:50:39,618] INFO:  Iter 47/100 - Loss: -0.283 (delta=-0.025619)
[2025-05-06 22:50:40,023] INFO:  Iter 48/100 - Loss: -0.308 (delta=-0.025672)
[2025-05-06 22:50:40,446] INFO:  Iter 49/100 - Loss: -0.334 (delta=-0.025705)
[2025-05-06 22:50:41,076] INFO:  Iter 50/100 - Loss: -0.360 (delta=-0.025751)
[2025-05-06 22:50:41,472] INFO:  Iter 51/100 - Loss: -0.386 (delta=-0.025854)
[2025-05-06 22:50:41,883] INFO:  Iter 52/100 - Loss: -0.412 (delta=-0.025845)
[2025-05-06 22:50:42,282] INFO:  Iter 53/100 - Loss: -0.438 (delta=-0.026010)
[2025-05-06 22:50:42,687] INFO:  Iter 54/100 - Loss: -0.464 (delta=-0.026043)
[2025-05-06 22:50:43,131] INFO:  Iter 55/100 - Loss: -0.490 (delta=-0.026021)
[2025-05-06 22:50:43,572] INFO:  Iter 56/100 - Loss: -0.516 (delta=-0.026145)
[2025-05-06 22:50:44,004] INFO:  Iter 57/100 - Loss: -0.542 (delta=-0.026156)
[2025-05-06 22:50:44,418] INFO:  Iter 58/100 - Loss: -0.568 (delta=-0.026164)
[2025-05-06 22:50:44,851] INFO:  Iter 59/100 - Loss: -0.594 (delta=-0.026194)
[2025-05-06 22:50:45,391] INFO:  Iter 60/100 - Loss: -0.621 (delta=-0.026303)
[2025-05-06 22:50:45,801] INFO:  Iter 61/100 - Loss: -0.647 (delta=-0.026331)
[2025-05-06 22:50:46,200] INFO:  Iter 62/100 - Loss: -0.673 (delta=-0.026267)
[2025-05-06 22:50:46,613] INFO:  Iter 63/100 - Loss: -0.700 (delta=-0.026396)
[2025-05-06 22:50:47,024] INFO:  Iter 64/100 - Loss: -0.726 (delta=-0.026420)
[2025-05-06 22:50:47,428] INFO:  Iter 65/100 - Loss: -0.752 (delta=-0.026353)
[2025-05-06 22:50:47,841] INFO:  Iter 66/100 - Loss: -0.779 (delta=-0.026382)
[2025-05-06 22:50:48,243] INFO:  Iter 67/100 - Loss: -0.805 (delta=-0.026349)
[2025-05-06 22:50:48,648] INFO:  Iter 68/100 - Loss: -0.832 (delta=-0.026534)
[2025-05-06 22:50:49,055] INFO:  Iter 69/100 - Loss: -0.858 (delta=-0.026407)
[2025-05-06 22:50:49,459] INFO:  Iter 70/100 - Loss: -0.884 (delta=-0.026462)
[2025-05-06 22:50:49,882] INFO:  Iter 71/100 - Loss: -0.911 (delta=-0.026403)
[2025-05-06 22:50:50,284] INFO:  Iter 72/100 - Loss: -0.937 (delta=-0.026487)
[2025-05-06 22:50:50,688] INFO:  Iter 73/100 - Loss: -0.964 (delta=-0.026418)
[2025-05-06 22:50:51,091] INFO:  Iter 74/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:51,491] INFO:  Iter 75/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:51,901] INFO:  Iter 76/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:52,342] INFO:  Iter 77/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:52,756] INFO:  Iter 78/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:53,161] INFO:  Iter 79/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:53,560] INFO:  Iter 80/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:53,975] INFO:  Iter 81/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:54,378] INFO:  Iter 82/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:54,783] INFO:  Iter 83/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:55,184] INFO:  Iter 84/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:55,591] INFO:  Iter 85/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:56,231] INFO:  Iter 86/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:56,630] INFO:  Iter 87/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:57,268] INFO:  Iter 88/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:57,917] INFO:  Iter 89/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:58,366] INFO:  Iter 90/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:58,989] INFO:  Iter 91/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:59,431] INFO:  Iter 92/100 - Loss: nan (delta=nan)
[2025-05-06 22:50:59,962] INFO:  Iter 93/100 - Loss: nan (delta=nan)
[2025-05-06 22:51:00,397] INFO:  Iter 94/100 - Loss: nan (delta=nan)
[2025-05-06 22:51:00,831] INFO:  Iter 95/100 - Loss: nan (delta=nan)
[2025-05-06 22:51:01,283] INFO:  Iter 96/100 - Loss: nan (delta=nan)
[2025-05-06 22:51:01,722] INFO:  Iter 97/100 - Loss: nan (delta=nan)
[2025-05-06 22:51:02,182] INFO:  Iter 98/100 - Loss: nan (delta=nan)
[2025-05-06 22:51:02,677] INFO:  Iter 99/100 - Loss: nan (delta=nan)
[2025-05-06 22:51:03,118] INFO:  Iter 100/100 - Loss: nan (delta=nan)
[2025-05-06 22:51:03,543] INFO:  Iter 1/100 - Loss: 0.755 (delta=inf)
[2025-05-06 22:51:03,946] INFO:  Iter 2/100 - Loss: 0.736 (delta=-0.018480)
[2025-05-06 22:51:04,353] INFO:  Iter 3/100 - Loss: 0.718 (delta=-0.018624)
[2025-05-06 22:51:04,780] INFO:  Iter 4/100 - Loss: 0.699 (delta=-0.018785)
[2025-05-06 22:51:05,184] INFO:  Iter 5/100 - Loss: 0.680 (delta=-0.018963)
[2025-05-06 22:51:05,591] INFO:  Iter 6/100 - Loss: 0.661 (delta=-0.019160)
[2025-05-06 22:51:06,001] INFO:  Iter 7/100 - Loss: 0.642 (delta=-0.019368)
[2025-05-06 22:51:06,403] INFO:  Iter 8/100 - Loss: 0.622 (delta=-0.019555)
[2025-05-06 22:51:06,810] INFO:  Iter 9/100 - Loss: 0.602 (delta=-0.019766)
[2025-05-06 22:51:07,214] INFO:  Iter 10/100 - Loss: 0.582 (delta=-0.019953)
[2025-05-06 22:51:07,619] INFO:  Iter 11/100 - Loss: 0.562 (delta=-0.020146)
[2025-05-06 22:51:08,029] INFO:  Iter 12/100 - Loss: 0.542 (delta=-0.020350)
[2025-05-06 22:51:08,433] INFO:  Iter 13/100 - Loss: 0.521 (delta=-0.020543)
[2025-05-06 22:51:08,838] INFO:  Iter 14/100 - Loss: 0.500 (delta=-0.020749)
[2025-05-06 22:51:09,244] INFO:  Iter 15/100 - Loss: 0.480 (delta=-0.020928)
[2025-05-06 22:51:09,648] INFO:  Iter 16/100 - Loss: 0.458 (delta=-0.021143)
[2025-05-06 22:51:10,081] INFO:  Iter 17/100 - Loss: 0.437 (delta=-0.021338)
[2025-05-06 22:51:10,483] INFO:  Iter 18/100 - Loss: 0.416 (delta=-0.021526)
[2025-05-06 22:51:10,935] INFO:  Iter 19/100 - Loss: 0.394 (delta=-0.021735)
[2025-05-06 22:51:11,340] INFO:  Iter 20/100 - Loss: 0.372 (delta=-0.021938)
[2025-05-06 22:51:11,748] INFO:  Iter 21/100 - Loss: 0.350 (delta=-0.022136)
[2025-05-06 22:51:12,149] INFO:  Iter 22/100 - Loss: 0.327 (delta=-0.022350)
[2025-05-06 22:51:12,831] INFO:  Iter 23/100 - Loss: 0.305 (delta=-0.022495)
[2025-05-06 22:51:13,225] INFO:  Iter 24/100 - Loss: 0.282 (delta=-0.022711)
[2025-05-06 22:51:13,617] INFO:  Iter 25/100 - Loss: 0.259 (delta=-0.022912)
[2025-05-06 22:51:14,018] INFO:  Iter 26/100 - Loss: 0.236 (delta=-0.022979)
[2025-05-06 22:51:14,430] INFO:  Iter 27/100 - Loss: 0.213 (delta=-0.023169)
[2025-05-06 22:51:14,875] INFO:  Iter 28/100 - Loss: 0.190 (delta=-0.023315)
[2025-05-06 22:51:15,283] INFO:  Iter 29/100 - Loss: 0.166 (delta=-0.023608)
[2025-05-06 22:51:15,688] INFO:  Iter 30/100 - Loss: 0.143 (delta=-0.023603)
[2025-05-06 22:51:16,098] INFO:  Iter 31/100 - Loss: 0.119 (delta=-0.023700)
[2025-05-06 22:51:16,503] INFO:  Iter 32/100 - Loss: 0.095 (delta=-0.024078)
[2025-05-06 22:51:16,930] INFO:  Iter 33/100 - Loss: 0.071 (delta=-0.024099)
[2025-05-06 22:51:17,334] INFO:  Iter 34/100 - Loss: 0.047 (delta=-0.024203)
[2025-05-06 22:51:17,738] INFO:  Iter 35/100 - Loss: 0.022 (delta=-0.024417)
[2025-05-06 22:51:18,142] INFO:  Iter 36/100 - Loss: -0.002 (delta=-0.024440)
[2025-05-06 22:51:18,546] INFO:  Iter 37/100 - Loss: -0.027 (delta=-0.024615)
[2025-05-06 22:51:18,981] INFO:  Iter 38/100 - Loss: -0.052 (delta=-0.024873)
[2025-05-06 22:51:19,398] INFO:  Iter 39/100 - Loss: -0.077 (delta=-0.024819)
[2025-05-06 22:51:19,846] INFO:  Iter 40/100 - Loss: -0.102 (delta=-0.024988)
[2025-05-06 22:51:20,274] INFO:  Iter 41/100 - Loss: -0.127 (delta=-0.024884)
[2025-05-06 22:51:20,702] INFO:  Iter 42/100 - Loss: -0.152 (delta=-0.025303)
[2025-05-06 22:51:21,384] INFO:  Iter 43/100 - Loss: -0.177 (delta=-0.025162)
[2025-05-06 22:51:21,804] INFO:  Iter 44/100 - Loss: -0.202 (delta=-0.025415)
[2025-05-06 22:51:22,224] INFO:  Iter 45/100 - Loss: -0.228 (delta=-0.025498)
[2025-05-06 22:51:22,637] INFO:  Iter 46/100 - Loss: -0.253 (delta=-0.025527)
[2025-05-06 22:51:23,074] INFO:  Iter 47/100 - Loss: -0.279 (delta=-0.025589)
[2025-05-06 22:51:23,492] INFO:  Iter 48/100 - Loss: -0.305 (delta=-0.025700)
[2025-05-06 22:51:23,920] INFO:  Iter 49/100 - Loss: -0.330 (delta=-0.025769)
[2025-05-06 22:51:24,345] INFO:  Iter 50/100 - Loss: -0.356 (delta=-0.025805)
[2025-05-06 22:51:24,759] INFO:  Iter 51/100 - Loss: -0.382 (delta=-0.025891)
[2025-05-06 22:51:25,189] INFO:  Iter 52/100 - Loss: -0.408 (delta=-0.025977)
[2025-05-06 22:51:25,598] INFO:  Iter 53/100 - Loss: -0.434 (delta=-0.025886)
[2025-05-06 22:51:26,016] INFO:  Iter 54/100 - Loss: -0.460 (delta=-0.026087)
[2025-05-06 22:51:26,427] INFO:  Iter 55/100 - Loss: -0.486 (delta=-0.026196)
[2025-05-06 22:51:26,857] INFO:  Iter 56/100 - Loss: -0.513 (delta=-0.026219)
[2025-05-06 22:51:27,288] INFO:  Iter 57/100 - Loss: -0.539 (delta=-0.026033)
[2025-05-06 22:51:27,706] INFO:  Iter 58/100 - Loss: -0.565 (delta=-0.026314)
[2025-05-06 22:51:28,120] INFO:  Iter 59/100 - Loss: -0.591 (delta=-0.026200)
[2025-05-06 22:51:28,542] INFO:  Iter 60/100 - Loss: -0.617 (delta=-0.026160)
[2025-05-06 22:51:28,979] INFO:  Iter 61/100 - Loss: -0.644 (delta=-0.026439)
[2025-05-06 22:51:29,399] INFO:  Iter 62/100 - Loss: -0.670 (delta=-0.026345)
[2025-05-06 22:51:29,820] INFO:  Iter 63/100 - Loss: -0.696 (delta=-0.026400)
[2025-05-06 22:51:30,234] INFO:  Iter 64/100 - Loss: -0.723 (delta=-0.026330)

In [18]:
bayesian_digital_twins

{1: <radp.digital_twin.rf.bayesian.bayesian_engine.BayesianDigitalTwin at 0x15ab24c10>,
 2: <radp.digital_twin.rf.bayesian.bayesian_engine.BayesianDigitalTwin at 0x169bf2f50>,
 3: <radp.digital_twin.rf.bayesian.bayesian_engine.BayesianDigitalTwin at 0x15f3920d0>}

In [27]:
# Training from scratch done now will update the exisitng BDT
update_not_from_scratch = train_or_update_rf_twin(update_data,topology,bayesian_digital_twins)

Combined DataFrame:         latitude  longitude  cell_rxpwr_dbm  cell_lat  cell_lon  cell_id  \
0      59.806764 -22.625309      100.788266     -90.0    -180.0        1
1      59.806764 -22.625309      100.788266       0.0       0.0        2
2      59.806764 -22.625309      100.788266      90.0     180.0        3
3      59.806764 -22.625309      100.788266     -90.0    -180.0        1
4      59.806764 -22.625309      100.788266       0.0       0.0        2
...          ...        ...             ...       ...       ...      ...
17995  63.970820  34.222834      100.191265       0.0       0.0        2
17996  63.970820  34.222834      100.191265      90.0     180.0        3
17997  63.970820  34.222834      100.191265     -90.0    -180.0        1
17998  63.970820  34.222834      100.191265       0.0       0.0        2
17999  63.970820  34.222834      100.191265      90.0     180.0        3

       cell_az_deg  cell_carrier_freq_mhz
0                0                   2800
1              120                   2800
2              240                   2800
3                0                   2800
4              120                   2800
...            ...                    ...
17995          120                   2800
17996          240                   2800
17997            0                   2800
17998          120                   2800
17999          240                   2800

[18000 rows x 8 columns]
Updated_List  [       latitude   longitude  cell_rxpwr_dbm  cell_lat  cell_lon  cell_id  \
0     59.579072  -12.913963      100.467071     -90.0    -180.0        1
1     57.624328   44.480489       99.921368     -90.0    -180.0        1
2     35.044060   85.283046      100.323001     -90.0    -180.0        1
3     44.169977  119.187328       99.871474     -90.0    -180.0        1
4     20.445885   23.983914       99.834834     -90.0    -180.0        1
...         ...         ...             ...       ...       ...      ...
5995 -36.838452  -99.644900       99.090123     -90.0    -180.0        1
5996  65.440241   46.484399      100.350526     -90.0    -180.0        1
5997   6.824297  -15.327791       99.224567     -90.0    -180.0        1
5998  -7.345566  -79.625791       99.671939     -90.0    -180.0        1
5999 -60.730916   53.149479      100.131296     -90.0    -180.0        1

      cell_az_deg  cell_carrier_freq_mhz  log_distance  relative_bearing
0               0                   2800     16.627979        167.086037
1               0                   2800     16.614825        224.480489
2               0                   2800     16.448820        265.283046
3               0                   2800     16.519261        299.187328
4               0                   2800     16.324680        203.983914
...           ...                    ...           ...               ...
5995            0                   2800     15.593489         80.355100
5996            0                   2800     16.666415        226.484399
5997            0                   2800     16.193052        164.672209
5998            0                   2800     16.034822        100.374209
5999            0                   2800     14.996686        233.149479

[6000 rows x 10 columns],        latitude   longitude  cell_rxpwr_dbm  cell_lat  cell_lon  cell_id  \
0     59.579072  -12.913963      100.467071       0.0       0.0        2
1     57.624328   44.480489       99.921368       0.0       0.0        2
2     35.044060   85.283046      100.323001       0.0       0.0        2
3     44.169977  119.187328       99.871474       0.0       0.0        2
4     20.445885   23.983914       99.834834       0.0       0.0        2
...         ...         ...             ...       ...       ...      ...
5995 -36.838452  -99.644900       99.090123       0.0       0.0        2
5996  65.440241   46.484399      100.350526       0.0       0.0        2
5997   6.824297  -15.327791       99.224567       0.0       0.0        2
5998  -7.345566  -79.625791       99.671939       0.0       0.0        2
5999 -60.730916   53.149479      100.131296       0.0       0.0        2

      cell_az_deg  cell_carrier_freq_mhz  log_distance  relative_bearing
0             120                   2800     15.721580        232.523842
1             120                   2800     15.832863        263.952667
2             120                   2800     16.076123        294.864505
3             120                   2800     16.324939        281.945975
4             120                   2800     15.057953        287.474103
...           ...                    ...           ...               ...
5995          120                   2800     16.202116        112.769389
5996          120                   2800     15.915668        258.335228
5997          120                   2800     14.438254        174.357301
5998          120                   2800     15.998572        142.533724
5999          120                   2800     15.909921         35.844466

[6000 rows x 10 columns],        latitude   longitude  cell_rxpwr_dbm  cell_lat  cell_lon  cell_id  \
0     59.579072  -12.913963      100.467071      90.0     180.0        3
1     57.624328   44.480489       99.921368      90.0     180.0        3
2     35.044060   85.283046      100.323001      90.0     180.0        3
3     44.169977  119.187328       99.871474      90.0     180.0        3
4     20.445885   23.983914       99.834834      90.0     180.0        3
...         ...         ...             ...       ...       ...      ...
5995 -36.838452  -99.644900       99.090123      90.0     180.0        3
5996  65.440241   46.484399      100.350526      90.0     180.0        3
5997   6.824297  -15.327791       99.224567      90.0     180.0        3
5998  -7.345566  -79.625791       99.671939      90.0     180.0        3
5999 -60.730916   53.149479      100.131296      90.0     180.0        3

      cell_az_deg  cell_carrier_freq_mhz  log_distance  relative_bearing
0             240                   2800     15.035285        132.913963
1             240                   2800     15.097561         75.519511
2             240                   2800     15.626686         34.716954
3             240                   2800     15.445093          0.812672
4             240                   2800     15.862259         96.016086
...           ...                    ...           ...               ...
5995          240                   2800     16.463068        219.644900
5996          240                   2800     14.821264         73.515601
5997          240                   2800     16.041109        135.327791
5998          240                   2800     16.198421        199.625791
5999          240                   2800     16.635650         66.850521

[6000 rows x 10 columns]]

/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-06 to the diagonal
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-05 to the diagonal
  warnings.warn(
/Users/tanzimfarhan/Desktop/Maveric/maveric/.venv/lib/python3.11/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-04 to the diagonal
  warnings.warn(

An unexpected error occurred: Matrix not positive definite after repeatedly adding jitter up to 1.0e-04.