# Notebook to fix PR issues

### Generate the UE data from mobility model first

In [1]:
import sys
from pathlib import Path
sys.path.append(f"{Path().absolute().parent}")

In [2]:
import pandas as pd
import scipy
import numpy as np
from radp_library import *
import matplotlib.pyplot as plt
import matplotlib.cm as cm
from radp.digital_twin.mobility.param_regression import get_predicted_alpha,preprocess_ue_data
from radp.digital_twin.utils.cell_selection import perform_attachment
from radp.digital_twin.rf.bayesian.bayesian_engine import (
    BayesianDigitalTwin,
    NormMethod,
)
from apps.mobility_robustness_optimization.simple_mro import SimpleMRO

In [3]:
params = {
    "ue_tracks_generation": {
            "params": {
                "simulation_duration": 3600,
                "simulation_time_interval_seconds": 0.01,
                "num_ticks": 50,
                "num_batches": 1,
                "ue_class_distribution": {
                    "stationary": {
                        "count": 10,
                        "velocity": 0,
                        "velocity_variance": 1
                    },
                    "pedestrian": {
                        "count": 5,
                        "velocity": 2,
                        "velocity_variance": 1
                    },
                    "cyclist": {
                        "count": 5,
                        "velocity": 5,
                        "velocity_variance": 1
                    },
                    "car": {
                        "count": 12,
                        "velocity": 20,
                        "velocity_variance": 1
                    }
                },
                "lat_lon_boundaries": {
                    "min_lat": -90,
                    "max_lat": 90,
                    "min_lon": -180,
                    "max_lon": 180
                },
                "gauss_markov_params": {
                    "alpha": 0.5,
                    "variance": 0.8,
                    "rng_seed": 42,
                    "lon_x_dims": 100,
                    "lon_y_dims": 100,
                    "// TODO": "Account for supporting the user choosing the anchor_loc and cov_around_anchor.",
                    "// Current implementation": "the UE Tracks generator will not be using these values.",
                    "// anchor_loc": {},
                    "// cov_around_anchor": {}
            }
        }
    }
}

In [4]:
training_data = get_ue_data(params)
training_data.head()

   mock_ue_id         lon        lat  tick
0           0   48.510339 -16.462645     0
1           1   19.286613  63.617111     0
2           2   21.315702 -47.889952     0
3           3  -70.559364 -79.511709     0
4           4 -168.916011 -39.338640     0

In [3]:
topology = pd.read_csv('data/sim_data/topology.csv')
topology.loc[topology['cell_id'] == 'cell_2', 'cell_lat'] = 0
topology.loc[topology['cell_id'] == 'cell_3', 'cell_lat'] = 90
topology.loc[topology['cell_id'] == 'cell_1', 'cell_lat'] = -90


topology.loc[topology['cell_id'] == 'cell_2', 'cell_lon'] = 0
topology.loc[topology['cell_id'] == 'cell_3', 'cell_lon'] = 180
topology.loc[topology['cell_id'] == 'cell_1', 'cell_lon'] = -180


topology.loc[topology['cell_id'] == 'cell_2', 'cell_carrier_freq_mhz'] = 2800
topology.loc[topology['cell_id'] == 'cell_3', 'cell_carrier_freq_mhz'] = 2800
topology.loc[topology['cell_id'] == 'cell_1', 'cell_carrier_freq_mhz'] = 2800

In [3]:
def _prepare_all_UEs_from_all_cells_df(
     data, topology
    ) -> pd.DataFrame:
        """
        Connects each user equipment (UE) entry to all cells in the topology for each tick,
        effectively creating a Cartesian product of UEs and cells, which includes data from both sources.
        """

        ue_data = data
        ue_data = ue_data.rename(columns={"lat": "latitude", "lon": "longitude"})
        topology_tmp = topology
        
        """" 
        As 'ue_data' and 'topology_tmp' both have columns 'cell_id', we encounter a name conflict when merging 
        with column 'Key' (merge key is not set to cell_id). In order to resolve this, pandas adds a suffix to 
        the conflicting columns as 'cell_id_x' and 'cell_id_y'  
        """  
        if 'cell_id' in ue_data.columns:
            ue_data = ue_data.drop(columns = ['cell_id'])
        
        # Remove the 'cell_' prefix and convert cell_id to integer if needed
        if topology_tmp["cell_id"].dtype == object:
            topology_tmp["cell_id"] = (
                topology_tmp["cell_id"].str.replace("cell_", "").astype(int)
            )
        
        ue_data["key"] = 1
        topology_tmp["key"] = 1
        combined_df = pd.merge(ue_data, topology_tmp, on="key").drop("key", axis=1)
        print("Combined DataFrame:", combined_df)
        return combined_df

In [4]:
def _preprocess_ue_topology_data(data,topology) -> pd.DataFrame:
        full_data = _prepare_all_UEs_from_all_cells_df(data,topology)
        full_data["log_distance"] = full_data.apply(
            lambda row: GISTools.get_log_distance(
                row["latitude"], row["longitude"], row["cell_lat"], row["cell_lon"]
            ),
            axis=1,
        )

        full_data["cell_rxpwr_dbm"] = full_data.apply(
            lambda row: calculate_received_power(
                row["log_distance"], row["cell_carrier_freq_mhz"]
            ),
            axis=1,
        )

        return full_data

In [5]:
def _preprocess_ue_training_data(data,topology) -> pd.DataFrame:
        data = _preprocess_ue_topology_data(data,topology)
        train_per_cell_df = [x for _, x in data.groupby("cell_id")]
        n_cell = len(topology.index)

        metadata_df = pd.DataFrame(
            {
                "cell_id": [cell_id for cell_id in topology.cell_id],
                "idx": [i + 1 for i in range(n_cell)],
            }
        )
        idx_cell_id_mapping = dict(zip(metadata_df.idx, metadata_df.cell_id))
        desired_idxs = [1 + r for r in range(n_cell)]

        n_samples_train = []
        for df in train_per_cell_df:
            n_samples_train.append(df.shape[0])

        train_per_cell_df_processed = []
        for i in range(n_cell):
            train_per_cell_df_processed.append(
                get_percell_data(
                    data_in=train_per_cell_df[i],
                    choose_strongest_samples_percell=False,
                    n_samples=n_samples_train[i],
                )[0][0]
            )

        training_data = {}

        for i, df in enumerate(train_per_cell_df_processed):
            train_cell_id = idx_cell_id_mapping[i + 1]
            training_data[train_cell_id] = df

        for train_cell_id, training_data_idx in training_data.items():
            training_data_idx["cell_id"] = train_cell_id
            training_data_idx["cell_lat"] = topology[
                topology["cell_id"] == train_cell_id
            ]["cell_lat"].values[0]
            training_data_idx["cell_lon"] = topology[
                topology["cell_id"] == train_cell_id
            ]["cell_lon"].values[0]
            training_data_idx["cell_az_deg"] = topology[
                topology["cell_id"] == train_cell_id
            ]["cell_az_deg"].values[0]
            training_data_idx["cell_carrier_freq_mhz"] = topology[
                topology["cell_id"] == train_cell_id
            ]["cell_carrier_freq_mhz"].values[0]
            training_data_idx["relative_bearing"] = [
                GISTools.get_relative_bearing(
                    training_data_idx["cell_az_deg"].values[0],
                    training_data_idx["cell_lat"].values[0],
                    training_data_idx["cell_lon"].values[0],
                    lat,
                    lon,
                )
                for lat, lon in zip(
                    training_data_idx["latitude"], training_data_idx["longitude"]
                )
            ]

        return training_data

In [6]:
bayesian_digital_twins = {}

In [6]:
def _training(bayesian_digital_twins, maxiter: int, train_data: pd.DataFrame,topology: pd.DataFrame) -> List[float]:
        """
        Trains the Bayesian Digital Twins for each cell in the topology using the UE locations and features
        like log distance, relative bearing, and cell received power (Rx power).
        """
        training_data = _preprocess_ue_training_data(train_data,topology)
        loss_vs_iters = []
        for train_cell_id, training_data_idx in training_data.items():
            bayesian_digital_twins[train_cell_id] = BayesianDigitalTwin(
                data_in=[training_data_idx],
                x_columns=["log_distance", "relative_bearing"],
                y_columns=["cell_rxpwr_dbm"],
                norm_method=NormMethod.MINMAX,
            )
            bayesian_digital_twins[train_cell_id] = bayesian_digital_twins[
                train_cell_id
            ]
            loss_vs_iters.append(
                bayesian_digital_twins[train_cell_id].train_distributed_gpmodel(
                    maxiter=maxiter,
                )
            )
        return bayesian_digital_twins, loss_vs_iters

In [13]:
bayesian_digital_twins, loss_vs_iters = _training(
    bayesian_digital_twins,
    maxiter=100,
    train_data=training_data,
    topology=topology,
)

Combined DataFrame:       mock_ue_id   longitude   latitude  tick  cell_lat  cell_lon  cell_id  \
0              0   48.510339 -16.462645     0     -90.0    -180.0        1
1              0   48.510339 -16.462645     0       0.0       0.0        2
2              0   48.510339 -16.462645     0      90.0     180.0        3
3              1   19.286613  63.617111     0     -90.0    -180.0        1
4              1   19.286613  63.617111     0       0.0       0.0        2
...          ...         ...        ...   ...       ...       ...      ...
4795          30   89.100351 -11.651079    49       0.0       0.0        2
4796          30   89.100351 -11.651079    49      90.0     180.0        3
4797          31  146.478589  74.187621    49     -90.0    -180.0        1
4798          31  146.478589  74.187621    49       0.0       0.0        2
4799          31  146.478589  74.187621    49      90.0     180.0        3

      cell_az_deg  cell_carrier_freq_mhz
0               0                   2800
1             120                   2800
2             240                   2800
3               0                   2800
4             120                   2800
...           ...                    ...
4795          120                   2800
4796          240                   2800
4797            0                   2800
4798          120                   2800
4799          240                   2800

[4800 rows x 9 columns]

[2025-05-07 14:45:46,036] INFO:  Iter 1/100 - Loss: 0.770 (delta=inf)
[2025-05-07 14:45:46,070] INFO:  Iter 2/100 - Loss: 0.750 (delta=-0.019613)
[2025-05-07 14:45:46,111] INFO:  Iter 3/100 - Loss: 0.731 (delta=-0.018802)
[2025-05-07 14:45:46,145] INFO:  Iter 4/100 - Loss: 0.713 (delta=-0.017859)
[2025-05-07 14:45:46,174] INFO:  Iter 5/100 - Loss: 0.694 (delta=-0.019280)
[2025-05-07 14:45:46,209] INFO:  Iter 6/100 - Loss: 0.675 (delta=-0.019566)
[2025-05-07 14:45:46,239] INFO:  Iter 7/100 - Loss: 0.658 (delta=-0.016846)
[2025-05-07 14:45:46,271] INFO:  Iter 8/100 - Loss: 0.639 (delta=-0.018843)
[2025-05-07 14:45:46,304] INFO:  Iter 9/100 - Loss: 0.617 (delta=-0.021821)
[2025-05-07 14:45:46,338] INFO:  Iter 10/100 - Loss: 0.597 (delta=-0.019510)
[2025-05-07 14:45:46,371] INFO:  Iter 11/100 - Loss: 0.575 (delta=-0.022858)
[2025-05-07 14:45:46,403] INFO:  Iter 12/100 - Loss: 0.555 (delta=-0.019504)
[2025-05-07 14:45:46,435] INFO:  Iter 13/100 - Loss: 0.535 (delta=-0.020242)
[2025-05-07 14:45:46,465] INFO:  Iter 14/100 - Loss: 0.513 (delta=-0.022044)
[2025-05-07 14:45:46,502] INFO:  Iter 15/100 - Loss: 0.493 (delta=-0.020251)
[2025-05-07 14:45:46,536] INFO:  Iter 16/100 - Loss: 0.477 (delta=-0.015856)
[2025-05-07 14:45:46,572] INFO:  Iter 17/100 - Loss: 0.451 (delta=-0.025619)
[2025-05-07 14:45:46,606] INFO:  Iter 18/100 - Loss: 0.435 (delta=-0.016379)
[2025-05-07 14:45:46,639] INFO:  Iter 19/100 - Loss: 0.407 (delta=-0.027904)
[2025-05-07 14:45:46,671] INFO:  Iter 20/100 - Loss: 0.386 (delta=-0.021175)
[2025-05-07 14:45:46,707] INFO:  Iter 21/100 - Loss: 0.366 (delta=-0.019965)
[2025-05-07 14:45:46,739] INFO:  Iter 22/100 - Loss: 0.345 (delta=-0.020755)
[2025-05-07 14:45:46,773] INFO:  Iter 23/100 - Loss: 0.319 (delta=-0.026237)
[2025-05-07 14:45:46,808] INFO:  Iter 24/100 - Loss: 0.302 (delta=-0.016258)
[2025-05-07 14:45:46,840] INFO:  Iter 25/100 - Loss: 0.272 (delta=-0.030220)
[2025-05-07 14:45:46,873] INFO:  Iter 26/100 - Loss: 0.250 (delta=-0.022221)
[2025-05-07 14:45:46,904] INFO:  Iter 27/100 - Loss: 0.229 (delta=-0.020922)
[2025-05-07 14:45:46,935] INFO:  Iter 28/100 - Loss: 0.208 (delta=-0.020592)
[2025-05-07 14:45:46,966] INFO:  Iter 29/100 - Loss: 0.187 (delta=-0.021466)
[2025-05-07 14:45:47,000] INFO:  Iter 30/100 - Loss: 0.158 (delta=-0.028988)
[2025-05-07 14:45:47,035] INFO:  Iter 31/100 - Loss: 0.133 (delta=-0.024893)
[2025-05-07 14:45:47,066] INFO:  Iter 32/100 - Loss: 0.111 (delta=-0.021998)
[2025-05-07 14:45:47,100] INFO:  Iter 33/100 - Loss: 0.090 (delta=-0.020711)
[2025-05-07 14:45:47,129] INFO:  Iter 34/100 - Loss: 0.067 (delta=-0.023205)
[2025-05-07 14:45:47,162] INFO:  Iter 35/100 - Loss: 0.039 (delta=-0.028479)
[2025-05-07 14:45:47,189] INFO:  Iter 36/100 - Loss: 0.012 (delta=-0.026347)
[2025-05-07 14:45:47,224] INFO:  Iter 37/100 - Loss: -0.007 (delta=-0.018936)
[2025-05-07 14:45:47,253] INFO:  Iter 38/100 - Loss: -0.033 (delta=-0.026048)
[2025-05-07 14:45:47,286] INFO:  Iter 39/100 - Loss: -0.062 (delta=-0.029309)
[2025-05-07 14:45:47,321] INFO:  Iter 40/100 - Loss: -0.085 (delta=-0.023318)
[2025-05-07 14:45:47,350] INFO:  Iter 41/100 - Loss: -0.108 (delta=-0.023123)
[2025-05-07 14:45:47,374] INFO:  Iter 42/100 - Loss: -0.130 (delta=-0.021839)
[2025-05-07 14:45:47,414] INFO:  Iter 43/100 - Loss: -0.159 (delta=-0.029072)
[2025-05-07 14:45:47,449] INFO:  Iter 44/100 - Loss: -0.186 (delta=-0.026592)
[2025-05-07 14:45:47,478] INFO:  Iter 45/100 - Loss: -0.206 (delta=-0.020441)
[2025-05-07 14:45:47,512] INFO:  Iter 46/100 - Loss: -0.232 (delta=-0.025335)
[2025-05-07 14:45:47,541] INFO:  Iter 47/100 - Loss: -0.261 (delta=-0.029692)
[2025-05-07 14:45:47,570] INFO:  Iter 48/100 - Loss: -0.287 (delta=-0.025613)
[2025-05-07 14:45:47,599] INFO:  Iter 49/100 - Loss: -0.315 (delta=-0.027935)
[2025-05-07 14:45:47,632] INFO:  Iter 50/100 - Loss: -0.331 (delta=-0.016075)
[2025-05-07 14:45:47,667] INFO:  Iter 51/100 - Loss: -0.362 (delta=-0.030942)
[2025-05-07 14:45:47,695] INFO:  Iter 52/100 - Loss: -0.393 (delta=-0.030811)
[2025-05-07 14:45:47,732] INFO:  Iter 53/100 - Loss: -0.418 (delta=-0.025113)
[2025-05-07 14:45:47,761] INFO:  Iter 54/100 - Loss: -0.442 (delta=-0.024027)
[2025-05-07 14:45:47,791] INFO:  Iter 55/100 - Loss: -0.472 (delta=-0.030563)
[2025-05-07 14:45:47,826] INFO:  Iter 56/100 - Loss: -0.489 (delta=-0.016532)
[2025-05-07 14:45:47,853] INFO:  Iter 57/100 - Loss: -0.514 (delta=-0.024922)
[2025-05-07 14:45:47,882] INFO:  Iter 58/100 - Loss: -0.546 (delta=-0.032006)
[2025-05-07 14:45:47,916] INFO:  Iter 59/100 - Loss: -0.572 (delta=-0.026001)
[2025-05-07 14:45:47,951] INFO:  Iter 60/100 - Loss: -0.601 (delta=-0.029138)
[2025-05-07 14:45:47,980] INFO:  Iter 61/100 - Loss: -0.620 (delta=-0.018968)
[2025-05-07 14:45:48,012] INFO:  Iter 62/100 - Loss: -0.651 (delta=-0.030855)
[2025-05-07 14:45:48,041] INFO:  Iter 63/100 - Loss: -0.675 (delta=-0.024486)
[2025-05-07 14:45:48,070] INFO:  Iter 64/100 - Loss: -0.701 (delta=-0.025804)
[2025-05-07 14:45:48,103] INFO:  Iter 65/100 - Loss: -0.722 (delta=-0.021345)
[2025-05-07 14:45:48,132] INFO:  Iter 66/100 - Loss: -0.756 (delta=-0.033505)
[2025-05-07 14:45:48,163] INFO:  Iter 67/100 - Loss: -0.786 (delta=-0.029822)
[2025-05-07 14:45:48,191] INFO:  Iter 68/100 - Loss: -0.805 (delta=-0.019537)
[2025-05-07 14:45:48,229] INFO:  Iter 69/100 - Loss: -0.837 (delta=-0.031245)
[2025-05-07 14:45:48,261] INFO:  Iter 70/100 - Loss: -0.860 (delta=-0.023315)
[2025-05-07 14:45:48,291] INFO:  Iter 71/100 - Loss: -0.885 (delta=-0.024798)
[2025-05-07 14:45:48,320] INFO:  Iter 72/100 - Loss: -0.917 (delta=-0.032440)
[2025-05-07 14:45:48,349] INFO:  Iter 73/100 - Loss: -0.940 (delta=-0.022542)
[2025-05-07 14:45:48,384] INFO:  Iter 74/100 - Loss: -0.968 (delta=-0.028583)
[2025-05-07 14:45:48,415] INFO:  Iter 75/100 - Loss: -0.994 (delta=-0.025715)
[2025-05-07 14:45:48,447] INFO:  Iter 76/100 - Loss: -1.019 (delta=-0.025220)
[2025-05-07 14:45:48,478] INFO:  Iter 77/100 - Loss: -1.049 (delta=-0.030210)
[2025-05-07 14:45:48,507] INFO:  Iter 78/100 - Loss: -1.071 (delta=-0.021161)
[2025-05-07 14:45:48,539] INFO:  Iter 79/100 - Loss: -1.096 (delta=-0.025454)
[2025-05-07 14:45:48,570] INFO:  Iter 80/100 - Loss: -1.124 (delta=-0.028138)
[2025-05-07 14:45:48,599] INFO:  Iter 81/100 - Loss: -1.155 (delta=-0.030504)
[2025-05-07 14:45:48,638] INFO:  Iter 82/100 - Loss: -1.179 (delta=-0.023894)
[2025-05-07 14:45:48,670] INFO:  Iter 83/100 - Loss: -1.201 (delta=-0.022315)
[2025-05-07 14:45:48,703] INFO:  Iter 84/100 - Loss: -1.227 (delta=-0.025666)
[2025-05-07 14:45:48,732] INFO:  Iter 85/100 - Loss: -1.254 (delta=-0.027223)
[2025-05-07 14:45:48,770] INFO:  Iter 86/100 - Loss: -1.278 (delta=-0.024423)
[2025-05-07 14:45:48,803] INFO:  Iter 87/100 - Loss: -1.304 (delta=-0.025846)
[2025-05-07 14:45:48,832] INFO:  Iter 88/100 - Loss: -1.332 (delta=-0.027519)
[2025-05-07 14:45:48,865] INFO:  Iter 89/100 - Loss: -1.361 (delta=-0.029769)
[2025-05-07 14:45:48,907] INFO:  Iter 90/100 - Loss: -1.381 (delta=-0.019866)
[2025-05-07 14:45:48,940] INFO:  Iter 91/100 - Loss: -1.414 (delta=-0.032537)
[2025-05-07 14:45:48,972] INFO:  Iter 92/100 - Loss: -1.439 (delta=-0.025421)
[2025-05-07 14:45:49,005] INFO:  Iter 93/100 - Loss: -1.458 (delta=-0.018599)
[2025-05-07 14:45:49,042] INFO:  Iter 94/100 - Loss: -1.487 (delta=-0.029707)
[2025-05-07 14:45:49,077] INFO:  Iter 95/100 - Loss: -1.517 (delta=-0.029388)
[2025-05-07 14:45:49,112] INFO:  Iter 96/100 - Loss: -1.547 (delta=-0.029831)
[2025-05-07 14:45:49,149] INFO:  Iter 97/100 - Loss: -1.569 (delta=-0.022148)
[2025-05-07 14:45:49,188] INFO:  Iter 98/100 - Loss: -1.590 (delta=-0.021399)
[2025-05-07 14:45:49,228] INFO:  Iter 99/100 - Loss: -1.619 (delta=-0.029030)
[2025-05-07 14:45:49,262] INFO:  Iter 100/100 - Loss: -1.643 (delta=-0.023522)
[2025-05-07 14:45:49,312] INFO:  Iter 1/100 - Loss: 0.755 (delta=inf)
[2025-05-07 14:45:49,349] INFO:  Iter 2/100 - Loss: 0.740 (delta=-0.015290)
[2025-05-07 14:45:49,387] INFO:  Iter 3/100 - Loss: 0.721 (delta=-0.018938)
[2025-05-07 14:45:49,420] INFO:  Iter 4/100 - Loss: 0.698 (delta=-0.022387)
[2025-05-07 14:45:49,454] INFO:  Iter 5/100 - Loss: 0.679 (delta=-0.019766)
[2025-05-07 14:45:49,487] INFO:  Iter 6/100 - Loss: 0.664 (delta=-0.014801)
[2025-05-07 14:45:49,520] INFO:  Iter 7/100 - Loss: 0.642 (delta=-0.021827)
[2025-05-07 14:45:49,553] INFO:  Iter 8/100 - Loss: 0.625 (delta=-0.016810)
[2025-05-07 14:45:49,587] INFO:  Iter 9/100 - Loss: 0.606 (delta=-0.018876)
[2025-05-07 14:45:49,624] INFO:  Iter 10/100 - Loss: 0.582 (delta=-0.024472)
[2025-05-07 14:45:49,659] INFO:  Iter 11/100 - Loss: 0.564 (delta=-0.017906)
[2025-05-07 14:45:49,691] INFO:  Iter 12/100 - Loss: 0.540 (delta=-0.023549)
[2025-05-07 14:45:49,724] INFO:  Iter 13/100 - Loss: 0.523 (delta=-0.017019)
[2025-05-07 14:45:49,759] INFO:  Iter 14/100 - Loss: 0.506 (delta=-0.017291)
[2025-05-07 14:45:49,791] INFO:  Iter 15/100 - Loss: 0.478 (delta=-0.028112)
[2025-05-07 14:45:49,828] INFO:  Iter 16/100 - Loss: 0.462 (delta=-0.016262)
[2025-05-07 14:45:49,862] INFO:  Iter 17/100 - Loss: 0.443 (delta=-0.019076)
[2025-05-07 14:45:49,896] INFO:  Iter 18/100 - Loss: 0.418 (delta=-0.024524)
[2025-05-07 14:45:49,929] INFO:  Iter 19/100 - Loss: 0.399 (delta=-0.018990)
[2025-05-07 14:45:49,967] INFO:  Iter 20/100 - Loss: 0.375 (delta=-0.023834)
[2025-05-07 14:45:50,001] INFO:  Iter 21/100 - Loss: 0.352 (delta=-0.023646)
[2025-05-07 14:45:50,036] INFO:  Iter 22/100 - Loss: 0.330 (delta=-0.021920)
[2025-05-07 14:45:50,075] INFO:  Iter 23/100 - Loss: 0.309 (delta=-0.021153)
[2025-05-07 14:45:50,112] INFO:  Iter 24/100 - Loss: 0.284 (delta=-0.025063)
[2025-05-07 14:45:50,145] INFO:  Iter 25/100 - Loss: 0.265 (delta=-0.018937)
[2025-05-07 14:45:50,178] INFO:  Iter 26/100 - Loss: 0.240 (delta=-0.024316)
[2025-05-07 14:45:50,212] INFO:  Iter 27/100 - Loss: 0.217 (delta=-0.022993)
[2025-05-07 14:45:50,246] INFO:  Iter 28/100 - Loss: 0.193 (delta=-0.024308)
[2025-05-07 14:45:50,275] INFO:  Iter 29/100 - Loss: 0.172 (delta=-0.021256)
[2025-05-07 14:45:50,303] INFO:  Iter 30/100 - Loss: 0.150 (delta=-0.021490)
[2025-05-07 14:45:50,338] INFO:  Iter 31/100 - Loss: 0.127 (delta=-0.023683)
[2025-05-07 14:45:50,368] INFO:  Iter 32/100 - Loss: 0.098 (delta=-0.028479)
[2025-05-07 14:45:50,400] INFO:  Iter 33/100 - Loss: 0.073 (delta=-0.025045)
[2025-05-07 14:45:50,430] INFO:  Iter 34/100 - Loss: 0.053 (delta=-0.019909)
[2025-05-07 14:45:50,460] INFO:  Iter 35/100 - Loss: 0.029 (delta=-0.024333)
[2025-05-07 14:45:50,491] INFO:  Iter 36/100 - Loss: 0.003 (delta=-0.025473)
[2025-05-07 14:45:50,522] INFO:  Iter 37/100 - Loss: -0.020 (delta=-0.022948)
[2025-05-07 14:45:50,550] INFO:  Iter 38/100 - Loss: -0.042 (delta=-0.022702)
[2025-05-07 14:45:50,580] INFO:  Iter 39/100 - Loss: -0.068 (delta=-0.026000)
[2025-05-07 14:45:50,610] INFO:  Iter 40/100 - Loss: -0.096 (delta=-0.027658)
[2025-05-07 14:45:50,640] INFO:  Iter 41/100 - Loss: -0.121 (delta=-0.025085)
[2025-05-07 14:45:50,674] INFO:  Iter 42/100 - Loss: -0.143 (delta=-0.021953)
[2025-05-07 14:45:50,705] INFO:  Iter 43/100 - Loss: -0.168 (delta=-0.024983)
[2025-05-07 14:45:50,738] INFO:  Iter 44/100 - Loss: -0.195 (delta=-0.026613)
[2025-05-07 14:45:50,772] INFO:  Iter 45/100 - Loss: -0.217 (delta=-0.022270)
[2025-05-07 14:45:50,805] INFO:  Iter 46/100 - Loss: -0.240 (delta=-0.023002)
[2025-05-07 14:45:50,839] INFO:  Iter 47/100 - Loss: -0.269 (delta=-0.028975)
[2025-05-07 14:45:50,871] INFO:  Iter 48/100 - Loss: -0.295 (delta=-0.025664)
[2025-05-07 14:45:50,903] INFO:  Iter 49/100 - Loss: -0.324 (delta=-0.029100)
[2025-05-07 14:45:50,933] INFO:  Iter 50/100 - Loss: -0.347 (delta=-0.023657)
[2025-05-07 14:45:50,965] INFO:  Iter 51/100 - Loss: -0.373 (delta=-0.025569)
[2025-05-07 14:45:50,995] INFO:  Iter 52/100 - Loss: -0.401 (delta=-0.028222)
[2025-05-07 14:45:51,027] INFO:  Iter 53/100 - Loss: -0.427 (delta=-0.025781)
[2025-05-07 14:45:51,061] INFO:  Iter 54/100 - Loss: -0.454 (delta=-0.027481)
[2025-05-07 14:45:51,094] INFO:  Iter 55/100 - Loss: -0.480 (delta=-0.025413)
[2025-05-07 14:45:51,127] INFO:  Iter 56/100 - Loss: -0.506 (delta=-0.026184)
[2025-05-07 14:45:51,162] INFO:  Iter 57/100 - Loss: -0.529 (delta=-0.023481)
[2025-05-07 14:45:51,196] INFO:  Iter 58/100 - Loss: -0.558 (delta=-0.028664)
[2025-05-07 14:45:51,232] INFO:  Iter 59/100 - Loss: -0.579 (delta=-0.021086)
[2025-05-07 14:45:51,264] INFO:  Iter 60/100 - Loss: -0.609 (delta=-0.029751)
[2025-05-07 14:45:51,297] INFO:  Iter 61/100 - Loss: -0.632 (delta=-0.023415)
[2025-05-07 14:45:51,329] INFO:  Iter 62/100 - Loss: -0.658 (delta=-0.026048)
[2025-05-07 14:45:51,365] INFO:  Iter 63/100 - Loss: -0.684 (delta=-0.025605)
[2025-05-07 14:45:51,401] INFO:  Iter 64/100 - Loss: -0.713 (delta=-0.028499)
[2025-05-07 14:45:51,431] INFO:  Iter 65/100 - Loss: -0.738 (delta=-0.025810)
[2025-05-07 14:45:51,462] INFO:  Iter 66/100 - Loss: -0.767 (delta=-0.028888)
[2025-05-07 14:45:51,491] INFO:  Iter 67/100 - Loss: -0.792 (delta=-0.024594)
[2025-05-07 14:45:51,520] INFO:  Iter 68/100 - Loss: -0.813 (delta=-0.020951)
[2025-05-07 14:45:51,555] INFO:  Iter 69/100 - Loss: -0.841 (delta=-0.028176)
[2025-05-07 14:45:51,586] INFO:  Iter 70/100 - Loss: -0.871 (delta=-0.030544)
[2025-05-07 14:45:51,616] INFO:  Iter 71/100 - Loss: -0.895 (delta=-0.023726)
[2025-05-07 14:45:51,650] INFO:  Iter 72/100 - Loss: -0.929 (delta=-0.033462)
[2025-05-07 14:45:51,687] INFO:  Iter 73/100 - Loss: -0.949 (delta=-0.020136)
[2025-05-07 14:45:51,719] INFO:  Iter 74/100 - Loss: -0.979 (delta=-0.030083)
[2025-05-07 14:45:51,749] INFO:  Iter 75/100 - Loss: -1.005 (delta=-0.025955)
[2025-05-07 14:45:51,785] INFO:  Iter 76/100 - Loss: -1.028 (delta=-0.022945)
[2025-05-07 14:45:51,816] INFO:  Iter 77/100 - Loss: -1.054 (delta=-0.026128)
[2025-05-07 14:45:51,853] INFO:  Iter 78/100 - Loss: -1.078 (delta=-0.024556)
[2025-05-07 14:45:51,883] INFO:  Iter 79/100 - Loss: -1.108 (delta=-0.029414)
[2025-05-07 14:45:51,912] INFO:  Iter 80/100 - Loss: -1.124 (delta=-0.015669)
[2025-05-07 14:45:51,941] INFO:  Iter 81/100 - Loss: -1.161 (delta=-0.037349)
[2025-05-07 14:45:51,974] INFO:  Iter 82/100 - Loss: -1.187 (delta=-0.025697)
[2025-05-07 14:45:52,004] INFO:  Iter 83/100 - Loss: -1.208 (delta=-0.021731)
[2025-05-07 14:45:52,038] INFO:  Iter 84/100 - Loss: -1.240 (delta=-0.032109)
[2025-05-07 14:45:52,072] INFO:  Iter 85/100 - Loss: -1.261 (delta=-0.020795)
[2025-05-07 14:45:52,105] INFO:  Iter 86/100 - Loss: -1.288 (delta=-0.026388)
[2025-05-07 14:45:52,140] INFO:  Iter 87/100 - Loss: -1.315 (delta=-0.026999)
[2025-05-07 14:45:52,174] INFO:  Iter 88/100 - Loss: -1.338 (delta=-0.023391)
[2025-05-07 14:45:52,203] INFO:  Iter 89/100 - Loss: -1.370 (delta=-0.031858)
[2025-05-07 14:45:52,237] INFO:  Iter 90/100 - Loss: -1.389 (delta=-0.019011)
[2025-05-07 14:45:52,270] INFO:  Iter 91/100 - Loss: -1.426 (delta=-0.036729)
[2025-05-07 14:45:52,302] INFO:  Iter 92/100 - Loss: -1.449 (delta=-0.023833)
[2025-05-07 14:45:52,333] INFO:  Iter 93/100 - Loss: -1.466 (delta=-0.016640)
[2025-05-07 14:45:52,366] INFO:  Iter 94/100 - Loss: -1.500 (delta=-0.033814)
[2025-05-07 14:45:52,401] INFO:  Iter 95/100 - Loss: -1.527 (delta=-0.027142)
[2025-05-07 14:45:52,435] INFO:  Iter 96/100 - Loss: -1.537 (delta=-0.009959)
[2025-05-07 14:45:52,465] INFO:  Iter 97/100 - Loss: -1.572 (delta=-0.034841)
[2025-05-07 14:45:52,495] INFO:  Iter 98/100 - Loss: -1.596 (delta=-0.024388)
[2025-05-07 14:45:52,528] INFO:  Iter 99/100 - Loss: -1.628 (delta=-0.032003)
[2025-05-07 14:45:52,560] INFO:  Iter 100/100 - Loss: -1.648 (delta=-0.019980)
[2025-05-07 14:45:52,606] INFO:  Iter 1/100 - Loss: 0.756 (delta=inf)
[2025-05-07 14:45:52,638] INFO:  Iter 2/100 - Loss: 0.734 (delta=-0.021462)
[2025-05-07 14:45:52,670] INFO:  Iter 3/100 - Loss: 0.719 (delta=-0.014866)
[2025-05-07 14:45:52,699] INFO:  Iter 4/100 - Loss: 0.698 (delta=-0.021341)
[2025-05-07 14:45:52,728] INFO:  Iter 5/100 - Loss: 0.680 (delta=-0.017634)
[2025-05-07 14:45:52,764] INFO:  Iter 6/100 - Loss: 0.660 (delta=-0.020686)
[2025-05-07 14:45:52,796] INFO:  Iter 7/100 - Loss: 0.641 (delta=-0.018405)
[2025-05-07 14:45:52,826] INFO:  Iter 8/100 - Loss: 0.621 (delta=-0.020337)
[2025-05-07 14:45:52,855] INFO:  Iter 9/100 - Loss: 0.605 (delta=-0.015597)
[2025-05-07 14:45:52,886] INFO:  Iter 10/100 - Loss: 0.583 (delta=-0.022049)
[2025-05-07 14:45:52,916] INFO:  Iter 11/100 - Loss: 0.561 (delta=-0.022607)
[2025-05-07 14:45:52,945] INFO:  Iter 12/100 - Loss: 0.543 (delta=-0.018014)
[2025-05-07 14:45:52,974] INFO:  Iter 13/100 - Loss: 0.521 (delta=-0.021660)
[2025-05-07 14:45:53,003] INFO:  Iter 14/100 - Loss: 0.503 (delta=-0.018182)
[2025-05-07 14:45:53,038] INFO:  Iter 15/100 - Loss: 0.479 (delta=-0.024084)
[2025-05-07 14:45:53,066] INFO:  Iter 16/100 - Loss: 0.459 (delta=-0.019669)
[2025-05-07 14:45:53,095] INFO:  Iter 17/100 - Loss: 0.438 (delta=-0.021163)
[2025-05-07 14:45:53,124] INFO:  Iter 18/100 - Loss: 0.418 (delta=-0.019775)
[2025-05-07 14:45:53,159] INFO:  Iter 19/100 - Loss: 0.393 (delta=-0.024815)
[2025-05-07 14:45:53,186] INFO:  Iter 20/100 - Loss: 0.373 (delta=-0.020573)
[2025-05-07 14:45:53,216] INFO:  Iter 21/100 - Loss: 0.348 (delta=-0.024796)
[2025-05-07 14:45:53,245] INFO:  Iter 22/100 - Loss: 0.328 (delta=-0.019482)
[2025-05-07 14:45:53,280] INFO:  Iter 23/100 - Loss: 0.306 (delta=-0.022214)
[2025-05-07 14:45:53,310] INFO:  Iter 24/100 - Loss: 0.282 (delta=-0.024004)
[2025-05-07 14:45:53,341] INFO:  Iter 25/100 - Loss: 0.262 (delta=-0.019818)
[2025-05-07 14:45:53,374] INFO:  Iter 26/100 - Loss: 0.242 (delta=-0.020559)
[2025-05-07 14:45:53,408] INFO:  Iter 27/100 - Loss: 0.212 (delta=-0.029578)
[2025-05-07 14:45:53,439] INFO:  Iter 28/100 - Loss: 0.193 (delta=-0.019114)
[2025-05-07 14:45:53,470] INFO:  Iter 29/100 - Loss: 0.169 (delta=-0.023830)
[2025-05-07 14:45:53,499] INFO:  Iter 30/100 - Loss: 0.146 (delta=-0.023680)
[2025-05-07 14:45:53,528] INFO:  Iter 31/100 - Loss: 0.123 (delta=-0.022843)
[2025-05-07 14:45:53,561] INFO:  Iter 32/100 - Loss: 0.096 (delta=-0.026690)
[2025-05-07 14:45:53,586] INFO:  Iter 33/100 - Loss: 0.078 (delta=-0.017903)
[2025-05-07 14:45:53,622] INFO:  Iter 34/100 - Loss: 0.052 (delta=-0.025895)
[2025-05-07 14:45:53,654] INFO:  Iter 35/100 - Loss: 0.025 (delta=-0.027237)
[2025-05-07 14:45:53,685] INFO:  Iter 36/100 - Loss: 0.003 (delta=-0.022089)
[2025-05-07 14:45:53,716] INFO:  Iter 37/100 - Loss: -0.023 (delta=-0.025694)
[2025-05-07 14:45:53,745] INFO:  Iter 38/100 - Loss: -0.044 (delta=-0.021787)
[2025-05-07 14:45:53,774] INFO:  Iter 39/100 - Loss: -0.073 (delta=-0.028742)
[2025-05-07 14:45:53,803] INFO:  Iter 40/100 - Loss: -0.098 (delta=-0.025106)
[2025-05-07 14:45:53,832] INFO:  Iter 41/100 - Loss: -0.123 (delta=-0.024332)
[2025-05-07 14:45:53,868] INFO:  Iter 42/100 - Loss: -0.147 (delta=-0.024304)
[2025-05-07 14:45:53,899] INFO:  Iter 43/100 - Loss: -0.173 (delta=-0.025858)
[2025-05-07 14:45:53,929] INFO:  Iter 44/100 - Loss: -0.195 (delta=-0.022273)
[2025-05-07 14:45:53,968] INFO:  Iter 45/100 - Loss: -0.223 (delta=-0.027646)
[2025-05-07 14:45:53,999] INFO:  Iter 46/100 - Loss: -0.248 (delta=-0.025095)
[2025-05-07 14:45:54,032] INFO:  Iter 47/100 - Loss: -0.275 (delta=-0.026769)
[2025-05-07 14:45:54,062] INFO:  Iter 48/100 - Loss: -0.298 (delta=-0.023271)
[2025-05-07 14:45:54,091] INFO:  Iter 49/100 - Loss: -0.326 (delta=-0.027878)
[2025-05-07 14:45:54,123] INFO:  Iter 50/100 - Loss: -0.349 (delta=-0.022912)
[2025-05-07 14:45:54,154] INFO:  Iter 51/100 - Loss: -0.376 (delta=-0.027613)
[2025-05-07 14:45:54,185] INFO:  Iter 52/100 - Loss: -0.404 (delta=-0.027427)
[2025-05-07 14:45:54,215] INFO:  Iter 53/100 - Loss: -0.427 (delta=-0.023248)
[2025-05-07 14:45:54,245] INFO:  Iter 54/100 - Loss: -0.454 (delta=-0.027436)
[2025-05-07 14:45:54,274] INFO:  Iter 55/100 - Loss: -0.477 (delta=-0.022568)
[2025-05-07 14:45:54,303] INFO:  Iter 56/100 - Loss: -0.507 (delta=-0.029852)
[2025-05-07 14:45:54,337] INFO:  Iter 57/100 - Loss: -0.537 (delta=-0.029952)
[2025-05-07 14:45:54,370] INFO:  Iter 58/100 - Loss: -0.561 (delta=-0.024145)

In [14]:
bayesian_digital_twins

{1: <radp.digital_twin.rf.bayesian.bayesian_engine.BayesianDigitalTwin at 0x24dd9f45d20>,
 2: <radp.digital_twin.rf.bayesian.bayesian_engine.BayesianDigitalTwin at 0x24dbbf6b730>,
 3: <radp.digital_twin.rf.bayesian.bayesian_engine.BayesianDigitalTwin at 0x24dbbb811b0>}

In [15]:
params2 = {
    "ue_tracks_generation": {
            "params": {
                "simulation_duration": 3600,
                "simulation_time_interval_seconds": 0.01,
                "num_ticks": 50,
                "num_batches": 1,
                "ue_class_distribution": {
                    "stationary": {
                        "count": 10,
                        "velocity": 0,
                        "velocity_variance": 1
                    },
                    "pedestrian": {
                        "count": 5,
                        "velocity": 2,
                        "velocity_variance": 1
                    },
                    "cyclist": {
                        "count": 7,
                        "velocity": 5,
                        "velocity_variance": 1
                    },
                    "car": {
                        "count": 10,
                        "velocity": 20,
                        "velocity_variance": 1
                    }
                },
                "lat_lon_boundaries": {
                    "min_lat": -90,
                    "max_lat": 90,
                    "min_lon": -180,
                    "max_lon": 180
                },
                "gauss_markov_params": {
                    "alpha": 0.8,
                    "variance": 0.5,
                    "rng_seed": 42,
                    "lon_x_dims": 100,
                    "lon_y_dims": 100,
                    "// TODO": "Account for supporting the user choosing the anchor_loc and cov_around_anchor.",
                    "// Current implementation": "the UE Tracks generator will not be using these values.",
                    "// anchor_loc": {},
                    "// cov_around_anchor": {}
            }
        }
    }
}

In [7]:
def _preprocess_prediction_data(pred_data,topology) -> pd.DataFrame:
        data = _prepare_all_UEs_from_all_cells_df(pred_data,topology)

        data["log_distance"] = data.apply(
            lambda row: GISTools.get_log_distance(
                row["latitude"], row["longitude"], row["cell_lat"], row["cell_lon"]
            ),
            axis=1,
        )
        data["cell_rxpwr_dbm"] = data.apply(
            lambda row: calculate_received_power(
                row["log_distance"], row["cell_carrier_freq_mhz"]
            ),
            axis=1,
        )

        data["relative_bearing"] = data.apply(
            lambda row: GISTools.get_relative_bearing(
                row["cell_az_deg"],
                row["cell_lat"],
                row["cell_lon"],
                row["latitude"],
                row["longitude"],
            ),
            axis=1,
        )
        return data

In [8]:
# Prediction
def _predictions(pred_data,topology,bayesian_digital_twins) -> Tuple[pd.DataFrame, pd.DataFrame]:
        """
        Predicts the received power for each User Equipment (UE) at different locations and ticks using Bayesian Digital Twins.
        It then determines the best cell for each UE to attach based on the predicted power values.
        """
        prediction_data = _preprocess_prediction_data(pred_data,topology)
        full_prediction_df = pd.DataFrame()

        # Loop over each 'tick'
        for tick, tick_df in prediction_data.groupby("tick"):
            # Loop over each 'cell_id' within the current 'tick'
            for cell_id, cell_df in tick_df.groupby("cell_id"):
                # Check if the Bayesian model for this cell_id exists
                if cell_id in bayesian_digital_twins:
                    # Perform the Bayesian prediction
                    pred_means_percell, _ = bayesian_digital_twins[
                        cell_id
                    ].predict_distributed_gpmodel(prediction_dfs=[cell_df])

                    # Assuming 'pred_means_percell' returns a list of predictions corresponding to the DataFrame index
                    cell_df["pred_means"] = pred_means_percell[0]

                    # Include additional necessary columns for the final DataFrame
                    cell_df["tick"] = tick
                    cell_df["cell_id"] = cell_id

                    # Append the predictions to the full DataFrame
                    full_prediction_df = pd.concat(
                        [full_prediction_df, cell_df], ignore_index=True
                    )
                else:
                    # Handle missing models, e.g., log a warning or initialize a default model
                    print(
                        f"No model available for cell_id {cell_id}, skipping prediction."
                    )

        full_prediction_df = full_prediction_df.rename(
            columns={"latitude": "loc_y", "longitude": "loc_x"}
        )
        predicted = perform_attachment(full_prediction_df, topology)

        return predicted, full_prediction_df

In [18]:
prediction_data = get_ue_data(params2)

In [19]:
predictions, full_prediction_df = _predictions(
    pred_data=prediction_data,
    topology=topology,
    bayesian_digital_twins = bayesian_digital_twins
)

Combined DataFrame:       mock_ue_id   longitude   latitude  tick  cell_lat  cell_lon  cell_id  \
0              0   48.510339 -16.462645     0     -90.0    -180.0        1
1              0   48.510339 -16.462645     0       0.0       0.0        2
2              0   48.510339 -16.462645     0      90.0     180.0        3
3              1   19.286613  63.617111     0     -90.0    -180.0        1
4              1   19.286613  63.617111     0       0.0       0.0        2
...          ...         ...        ...   ...       ...       ...      ...
4795          30  -64.060471  70.447505    49       0.0       0.0        2
4796          30  -64.060471  70.447505    49      90.0     180.0        3
4797          31 -152.742476  51.756565    49     -90.0    -180.0        1
4798          31 -152.742476  51.756565    49       0.0       0.0        2
4799          31 -152.742476  51.756565    49      90.0     180.0        3

      cell_az_deg  cell_carrier_freq_mhz
0               0                   2800
1             120                   2800
2             240                   2800
3               0                   2800
4             120                   2800
...           ...                    ...
4795          120                   2800
4796          240                   2800
4797            0                   2800
4798          120                   2800
4799          240                   2800

[4800 rows x 9 columns]

### Disect all the codes from MRO and put it to radp_library.py

In [9]:
bdt = {}

In [10]:
update_data = pd.read_csv('data/sim_data/combined_data_dump.csv')
update_data.head()

    latitude   longitude  cell_rxpower_dbm
0  59.806764  -22.625309        100.788266
1  59.806764  -22.625309        100.788266
2  59.806764  -22.625309        100.788266
3  54.857584  119.764151         99.608310
4  54.857584  119.764151         99.608310

## Attaching real **rxpower_dbm** data

In [11]:
topology = pd.read_csv('data/sim_data/topology.csv')
topology.loc[topology['cell_id'] == 'cell_2', 'cell_lat'] = 0
topology.loc[topology['cell_id'] == 'cell_3', 'cell_lat'] = 90
topology.loc[topology['cell_id'] == 'cell_1', 'cell_lat'] = -90


topology.loc[topology['cell_id'] == 'cell_2', 'cell_lon'] = 0
topology.loc[topology['cell_id'] == 'cell_3', 'cell_lon'] = 180
topology.loc[topology['cell_id'] == 'cell_1', 'cell_lon'] = -180


topology.loc[topology['cell_id'] == 'cell_2', 'cell_carrier_freq_mhz'] = 2800
topology.loc[topology['cell_id'] == 'cell_3', 'cell_carrier_freq_mhz'] = 2800
topology.loc[topology['cell_id'] == 'cell_1', 'cell_carrier_freq_mhz'] = 2800

In [12]:
real_rxdmb_data = pd.read_csv('data/sim_data/cell_rxpwr_debug.csv')
real_rxdmb_data.head()

,mock_ue_id,longitude,latitude,tick,cell_lat,cell_lon,cell_id,cell_az_deg,cell_carrier_freq_mhz,log_distance,cell_rxpwr_dbm,relative_bearing
0,5,-43.264737,-30.862211,20,-90.0,-180.0,cell_1,0,2100,15.700024,-99.812392,136.735263
1,10,54.978193,-55.259842,59,-90.0,-180.0,cell_1,0,2100,15.168050,-99.512981,234.978193
2,12,-98.676642,40.779019,56,-90.0,-180.0,cell_1,0,2100,16.493663,-100.240728,81.323358
3,11,5.606533,12.413489,36,-90.0,-180.0,cell_1,0,2100,16.249172,-100.111011,185.606533
4,14,-134.815655,-58.151045,87,-90.0,-180.0,cell_1,0,2100,15.081159,-99.463080,45.184345

In [13]:
update_data = real_rxdmb_data.copy()
update_data.drop(columns=['mock_ue_id', 'tick', 'cell_lat', 'cell_lon', 'cell_az_deg', 'cell_carrier_freq_mhz', 'log_distance', 'relative_bearing'], inplace=True)
# update_data = update_data[['']]
update_data.head()

    longitude   latitude cell_id  cell_rxpwr_dbm
0  -43.264737 -30.862211  cell_1      -99.812392
1   54.978193 -55.259842  cell_1      -99.512981
2  -98.676642  40.779019  cell_1     -100.240728
3    5.606533  12.413489  cell_1     -100.111011
4 -134.815655 -58.151045  cell_1      -99.463080

In [14]:
def _preprocess_ue_update_data(update_data,topology) -> pd.DataFrame:
        data = _prepare_all_UEs_from_all_cells_df(update_data,topology)
        data["log_distance"] = data.apply(
            lambda row: GISTools.get_log_distance(
                row["latitude"], row["longitude"], row["cell_lat"], row["cell_lon"]
            ),
            axis=1,
        )

        update_per_cell_df = [x for _, x in data.groupby("cell_id")]
        n_cell = len(topology.index)

        metadata_df = pd.DataFrame(
            {
                "cell_id": [cell_id for cell_id in topology.cell_id],
                "idx": [i + 1 for i in range(n_cell)],
            }
        )
        idx_cell_id_mapping = dict(zip(metadata_df.idx, metadata_df.cell_id))

        n_samples_update = []
        for df in update_per_cell_df:
            n_samples_update.append(df.shape[0])

        update_per_cell_df_processed = []
        for i in range(n_cell):
            update_per_cell_df_processed.append(
                get_percell_data(
                    data_in=update_per_cell_df[i],
                    choose_strongest_samples_percell=False,
                    n_samples=n_samples_update[i],
                )[0][0]
            )

        update_data = {}

        for i, df in enumerate(update_per_cell_df_processed):
            update_cell_id = idx_cell_id_mapping[i + 1]
            update_data[update_cell_id] = df

        for update_cell_id, update_data_idx in update_data.items():
            update_data_idx["cell_id"] = update_cell_id
            update_data_idx["cell_lat"] = topology[
                topology["cell_id"] == update_cell_id
            ]["cell_lat"].values[0]
            update_data_idx["cell_lon"] = topology[
                topology["cell_id"] == update_cell_id
            ]["cell_lon"].values[0]
            update_data_idx["cell_az_deg"] = topology[
                topology["cell_id"] == update_cell_id
            ]["cell_az_deg"].values[0]
            update_data_idx["cell_carrier_freq_mhz"] = topology[
                topology["cell_id"] == update_cell_id
            ]["cell_carrier_freq_mhz"].values[0]
            update_data_idx["relative_bearing"] = [
                GISTools.get_relative_bearing(
                    update_data_idx["cell_az_deg"].values[0],
                    update_data_idx["cell_lat"].values[0],
                    update_data_idx["cell_lon"].values[0],
                    lat,
                    lon,
                )
                for lat, lon in zip(
                    update_data_idx["latitude"], update_data_idx["longitude"]
                )
            ]
        return update_data

In [ ]:
def train_or_update_rf_twin(new_data: pd.DataFrame,topology: pd.DataFrame, bayesian_digital_twins):
        try:
            if not isinstance(new_data, pd.DataFrame):
                raise TypeError("The input 'new_data' must be a pandas DataFrame.")
            
            new_data = new_data.rename(
                columns={"cell_rxpower_dbm": "cell_rxpwr_dbm"}
            )
            expected_columns = {"longitude", "latitude", "cell_rxpwr_dbm"}
            if not expected_columns.issubset(new_data.columns):
                raise ValueError(
                    f"The input DataFrame must contain the following columns: {expected_columns}"
                )

            if bayesian_digital_twins:
                update_data = new_data
                updated_data = _preprocess_ue_update_data(update_data, topology)
                updated_data_list = list(updated_data.values())
                print("Updated_List ",updated_data_list)

                for data_idx, update_data_df in enumerate(updated_data_list):
                    update_cell_id = data_idx + 1
                    if update_cell_id in bayesian_digital_twins:
                        print(f"Updating cell {update_cell_id} with {len(update_data_df)} samples.")
                        bayesian_digital_twins[
                            update_cell_id
                        ].update_trained_gpmodel([update_data_df])
            else:
                print(
                    "No Bayesian Digital Twins available for update. Training from scratch."
                )
                new_data = new_data.drop(
                    columns=["cell_rxpower_dbm"], errors="ignore"
                )
                _training(bayesian_digital_twins,maxiter=100, train_data=new_data,topology = topology)
        
            # return bayesian_digital_twins
        
        except TypeError as te:
            print(f"TypeError: {te}")
        except ValueError as ve:
            print(f"ValueError: {ve}")
        except KeyError as ke:
            print(f"KeyError: {ke}")
        except Exception as e:
            print(f"An unexpected error occurred: {e}")

In [16]:
bdt

{}

In [17]:
updates = train_or_update_rf_twin(update_data,topology,bdt)

No Bayesian Digital Twins available for update. Training from scratch.
Combined DataFrame:        longitude   latitude  cell_rxpwr_dbm  cell_lat  cell_lon  cell_id  \
0     -43.264737 -30.862211      -99.812392     -90.0    -180.0        1
1     -43.264737 -30.862211      -99.812392       0.0       0.0        2
2     -43.264737 -30.862211      -99.812392      90.0     180.0        3
3      54.978193 -55.259842      -99.512981     -90.0    -180.0        1
4      54.978193 -55.259842      -99.512981       0.0       0.0        2
...          ...        ...             ...       ...       ...      ...
17995  89.254786 -82.596233     -100.385621       0.0       0.0        2
17996  89.254786 -82.596233     -100.385621      90.0     180.0        3
17997  20.088340 -55.786882     -100.297751     -90.0    -180.0        1
17998  20.088340 -55.786882     -100.297751       0.0       0.0        2
17999  20.088340 -55.786882     -100.297751      90.0     180.0        3

       cell_az_deg  cell_carrier_freq_mhz
0                0                   2800
1              120                   2800
2              240                   2800
3                0                   2800
4              120                   2800
...            ...                    ...
17995          120                   2800
17996          240                   2800
17997            0                   2800
17998          120                   2800
17999          240                   2800

[18000 rows x 8 columns]

[2025-05-07 16:53:40,223] INFO:  Iter 1/100 - Loss: 0.758 (delta=inf)
[2025-05-07 16:53:41,271] INFO:  Iter 2/100 - Loss: 0.739 (delta=-0.018517)
[2025-05-07 16:53:42,167] INFO:  Iter 3/100 - Loss: 0.721 (delta=-0.018668)
[2025-05-07 16:53:43,156] INFO:  Iter 4/100 - Loss: 0.702 (delta=-0.018836)
[2025-05-07 16:53:44,335] INFO:  Iter 5/100 - Loss: 0.683 (delta=-0.019023)
[2025-05-07 16:53:44,887] INFO:  Iter 6/100 - Loss: 0.664 (delta=-0.019215)
[2025-05-07 16:53:45,702] INFO:  Iter 7/100 - Loss: 0.644 (delta=-0.019419)
[2025-05-07 16:53:46,224] INFO:  Iter 8/100 - Loss: 0.625 (delta=-0.019624)
[2025-05-07 16:53:46,934] INFO:  Iter 9/100 - Loss: 0.605 (delta=-0.019817)
[2025-05-07 16:53:47,475] INFO:  Iter 10/100 - Loss: 0.585 (delta=-0.020020)
[2025-05-07 16:53:47,931] INFO:  Iter 11/100 - Loss: 0.565 (delta=-0.020228)
[2025-05-07 16:53:48,440] INFO:  Iter 12/100 - Loss: 0.544 (delta=-0.020430)
[2025-05-07 16:53:48,989] INFO:  Iter 13/100 - Loss: 0.523 (delta=-0.020638)
[2025-05-07 16:53:49,532] INFO:  Iter 14/100 - Loss: 0.503 (delta=-0.020839)
[2025-05-07 16:53:50,134] INFO:  Iter 15/100 - Loss: 0.482 (delta=-0.021050)
[2025-05-07 16:53:50,617] INFO:  Iter 16/100 - Loss: 0.460 (delta=-0.021264)
[2025-05-07 16:53:51,139] INFO:  Iter 17/100 - Loss: 0.439 (delta=-0.021448)
[2025-05-07 16:53:51,739] INFO:  Iter 18/100 - Loss: 0.417 (delta=-0.021647)
[2025-05-07 16:53:52,338] INFO:  Iter 19/100 - Loss: 0.395 (delta=-0.021805)
[2025-05-07 16:53:52,872] INFO:  Iter 20/100 - Loss: 0.373 (delta=-0.022012)
[2025-05-07 16:53:53,457] INFO:  Iter 21/100 - Loss: 0.351 (delta=-0.022187)
[2025-05-07 16:53:54,100] INFO:  Iter 22/100 - Loss: 0.329 (delta=-0.022368)
[2025-05-07 16:53:54,567] INFO:  Iter 23/100 - Loss: 0.306 (delta=-0.022506)
[2025-05-07 16:53:55,184] INFO:  Iter 24/100 - Loss: 0.284 (delta=-0.022803)
[2025-05-07 16:53:55,739] INFO:  Iter 25/100 - Loss: 0.261 (delta=-0.022857)
[2025-05-07 16:53:56,289] INFO:  Iter 26/100 - Loss: 0.238 (delta=-0.023048)
[2025-05-07 16:53:56,813] INFO:  Iter 27/100 - Loss: 0.214 (delta=-0.023213)
[2025-05-07 16:53:57,355] INFO:  Iter 28/100 - Loss: 0.191 (delta=-0.023430)
[2025-05-07 16:53:57,832] INFO:  Iter 29/100 - Loss: 0.167 (delta=-0.023567)
[2025-05-07 16:53:58,443] INFO:  Iter 30/100 - Loss: 0.144 (delta=-0.023687)
[2025-05-07 16:53:59,017] INFO:  Iter 31/100 - Loss: 0.120 (delta=-0.023837)
[2025-05-07 16:53:59,507] INFO:  Iter 32/100 - Loss: 0.096 (delta=-0.023998)
[2025-05-07 16:54:00,089] INFO:  Iter 33/100 - Loss: 0.072 (delta=-0.024136)
[2025-05-07 16:54:00,601] INFO:  Iter 34/100 - Loss: 0.048 (delta=-0.024213)
[2025-05-07 16:54:01,152] INFO:  Iter 35/100 - Loss: 0.023 (delta=-0.024476)
[2025-05-07 16:54:01,674] INFO:  Iter 36/100 - Loss: -0.001 (delta=-0.024483)
[2025-05-07 16:54:02,172] INFO:  Iter 37/100 - Loss: -0.026 (delta=-0.024632)
[2025-05-07 16:54:03,034] INFO:  Iter 38/100 - Loss: -0.051 (delta=-0.024794)
[2025-05-07 16:54:03,553] INFO:  Iter 39/100 - Loss: -0.076 (delta=-0.024894)
[2025-05-07 16:54:04,138] INFO:  Iter 40/100 - Loss: -0.101 (delta=-0.024968)
[2025-05-07 16:54:04,687] INFO:  Iter 41/100 - Loss: -0.126 (delta=-0.025131)
[2025-05-07 16:54:05,236] INFO:  Iter 42/100 - Loss: -0.151 (delta=-0.025188)
[2025-05-07 16:54:05,767] INFO:  Iter 43/100 - Loss: -0.176 (delta=-0.025178)
[2025-05-07 16:54:06,408] INFO:  Iter 44/100 - Loss: -0.202 (delta=-0.025427)
[2025-05-07 16:54:06,960] INFO:  Iter 45/100 - Loss: -0.227 (delta=-0.025416)
[2025-05-07 16:54:07,850] INFO:  Iter 46/100 - Loss: -0.253 (delta=-0.025648)
[2025-05-07 16:54:08,301] INFO:  Iter 47/100 - Loss: -0.278 (delta=-0.025608)
[2025-05-07 16:54:08,888] INFO:  Iter 48/100 - Loss: -0.304 (delta=-0.025639)
[2025-05-07 16:54:09,366] INFO:  Iter 49/100 - Loss: -0.330 (delta=-0.025822)
[2025-05-07 16:54:09,801] INFO:  Iter 50/100 - Loss: -0.356 (delta=-0.025836)
[2025-05-07 16:54:10,425] INFO:  Iter 51/100 - Loss: -0.381 (delta=-0.025871)
[2025-05-07 16:54:10,989] INFO:  Iter 52/100 - Loss: -0.407 (delta=-0.025974)
[2025-05-07 16:54:11,505] INFO:  Iter 53/100 - Loss: -0.433 (delta=-0.026025)
[2025-05-07 16:54:12,084] INFO:  Iter 54/100 - Loss: -0.459 (delta=-0.026003)
[2025-05-07 16:54:12,655] INFO:  Iter 55/100 - Loss: -0.485 (delta=-0.025966)
[2025-05-07 16:54:13,272] INFO:  Iter 56/100 - Loss: -0.512 (delta=-0.026324)
[2025-05-07 16:54:13,792] INFO:  Iter 57/100 - Loss: -0.538 (delta=-0.026140)
[2025-05-07 16:54:14,339] INFO:  Iter 58/100 - Loss: -0.564 (delta=-0.026285)
[2025-05-07 16:54:14,922] INFO:  Iter 59/100 - Loss: -0.590 (delta=-0.026282)
[2025-05-07 16:54:15,476] INFO:  Iter 60/100 - Loss: -0.617 (delta=-0.026283)
[2025-05-07 16:54:16,022] INFO:  Iter 61/100 - Loss: -0.643 (delta=-0.026394)
[2025-05-07 16:54:16,588] INFO:  Iter 62/100 - Loss: -0.669 (delta=-0.026301)
[2025-05-07 16:54:17,156] INFO:  Iter 63/100 - Loss: -0.696 (delta=-0.026346)
[2025-05-07 16:54:17,722] INFO:  Iter 64/100 - Loss: -0.722 (delta=-0.026367)
[2025-05-07 16:54:18,227] INFO:  Iter 65/100 - Loss: -0.749 (delta=-0.026511)
[2025-05-07 16:54:18,771] INFO:  Iter 66/100 - Loss: -0.775 (delta=-0.026276)
[2025-05-07 16:54:19,280] INFO:  Iter 67/100 - Loss: -0.801 (delta=-0.026429)
[2025-05-07 16:54:19,855] INFO:  Iter 68/100 - Loss: -0.828 (delta=-0.026370)
[2025-05-07 16:54:20,389] INFO:  Iter 69/100 - Loss: -0.854 (delta=-0.026609)
[2025-05-07 16:54:20,892] INFO:  Iter 70/100 - Loss: -0.881 (delta=-0.026520)
[2025-05-07 16:54:21,355] INFO:  Iter 71/100 - Loss: -0.907 (delta=-0.026405)
[2025-05-07 16:54:21,939] INFO:  Iter 72/100 - Loss: -0.934 (delta=-0.026571)
[2025-05-07 16:54:22,589] INFO:  Iter 73/100 - Loss: -0.960 (delta=-0.026354)
[2025-05-07 16:54:23,107] INFO:  Iter 74/100 - Loss: -0.987 (delta=-0.026377)
[2025-05-07 16:54:23,953] INFO:  Iter 75/100 - Loss: -1.013 (delta=-0.026683)
[2025-05-07 16:54:24,420] INFO:  Iter 76/100 - Loss: -1.040 (delta=-0.026476)
[2025-05-07 16:54:24,948] INFO:  Iter 77/100 - Loss: -1.066 (delta=-0.026253)
[2025-05-07 16:54:25,455] INFO:  Iter 78/100 - Loss: -1.093 (delta=-0.026513)
[2025-05-07 16:54:26,082] INFO:  Iter 79/100 - Loss: -1.119 (delta=-0.026588)
[2025-05-07 16:54:26,674] INFO:  Iter 80/100 - Loss: -1.145 (delta=-0.026265)
[2025-05-07 16:54:27,172] INFO:  Iter 81/100 - Loss: -1.172 (delta=-0.026375)
[2025-05-07 16:54:27,755] INFO:  Iter 82/100 - Loss: -1.198 (delta=-0.026369)
[2025-05-07 16:54:28,339] INFO:  Iter 83/100 - Loss: -1.225 (delta=-0.026452)
[2025-05-07 16:54:28,939] INFO:  Iter 84/100 - Loss: -1.251 (delta=-0.026061)
[2025-05-07 16:54:29,439] INFO:  Iter 85/100 - Loss: -1.277 (delta=-0.026645)
[2025-05-07 16:54:29,963] INFO:  Iter 86/100 - Loss: -1.304 (delta=-0.026273)
[2025-05-07 16:54:30,472] INFO:  Iter 87/100 - Loss: -1.330 (delta=-0.026519)
[2025-05-07 16:54:30,905] INFO:  Iter 88/100 - Loss: -1.356 (delta=-0.026035)
[2025-05-07 16:54:31,472] INFO:  Iter 89/100 - Loss: -1.382 (delta=-0.026335)
[2025-05-07 16:54:31,906] INFO:  Iter 90/100 - Loss: -1.408 (delta=-0.026048)
[2025-05-07 16:54:32,439] INFO:  Iter 91/100 - Loss: -1.435 (delta=-0.026465)
[2025-05-07 16:54:33,005] INFO:  Iter 92/100 - Loss: -1.461 (delta=-0.026055)
[2025-05-07 16:54:33,670] INFO:  Iter 93/100 - Loss: -1.487 (delta=-0.026145)
[2025-05-07 16:54:34,305] INFO:  Iter 94/100 - Loss: -1.513 (delta=-0.026200)
[2025-05-07 16:54:34,855] INFO:  Iter 95/100 - Loss: -1.539 (delta=-0.026054)
[2025-05-07 16:54:35,322] INFO:  Iter 96/100 - Loss: -1.565 (delta=-0.025601)
[2025-05-07 16:54:36,172] INFO:  Iter 97/100 - Loss: -1.591 (delta=-0.026374)
[2025-05-07 16:54:36,671] INFO:  Iter 98/100 - Loss: -1.617 (delta=-0.025711)
[2025-05-07 16:54:37,139] INFO:  Iter 99/100 - Loss: -1.643 (delta=-0.026101)
[2025-05-07 16:54:37,668] INFO:  Iter 100/100 - Loss: -1.669 (delta=-0.025748)
[2025-05-07 16:54:38,124] INFO:  Iter 1/100 - Loss: 0.747 (delta=inf)
[2025-05-07 16:54:38,630] INFO:  Iter 2/100 - Loss: 0.729 (delta=-0.018267)
[2025-05-07 16:54:39,188] INFO:  Iter 3/100 - Loss: 0.710 (delta=-0.018456)
[2025-05-07 16:54:39,655] INFO:  Iter 4/100 - Loss: 0.691 (delta=-0.018647)
[2025-05-07 16:54:40,224] INFO:  Iter 5/100 - Loss: 0.673 (delta=-0.018845)
[2025-05-07 16:54:40,743] INFO:  Iter 6/100 - Loss: 0.654 (delta=-0.019045)
[2025-05-07 16:54:41,390] INFO:  Iter 7/100 - Loss: 0.634 (delta=-0.019247)
[2025-05-07 16:54:42,091] INFO:  Iter 8/100 - Loss: 0.615 (delta=-0.019442)
[2025-05-07 16:54:42,650] INFO:  Iter 9/100 - Loss: 0.595 (delta=-0.019644)
[2025-05-07 16:54:43,283] INFO:  Iter 10/100 - Loss: 0.575 (delta=-0.019846)
[2025-05-07 16:54:43,735] INFO:  Iter 11/100 - Loss: 0.555 (delta=-0.020044)
[2025-05-07 16:54:44,236] INFO:  Iter 12/100 - Loss: 0.535 (delta=-0.020244)
[2025-05-07 16:54:44,781] INFO:  Iter 13/100 - Loss: 0.515 (delta=-0.020446)
[2025-05-07 16:54:45,370] INFO:  Iter 14/100 - Loss: 0.494 (delta=-0.020643)
[2025-05-07 16:54:45,870] INFO:  Iter 15/100 - Loss: 0.473 (delta=-0.020846)
[2025-05-07 16:54:46,423] INFO:  Iter 16/100 - Loss: 0.452 (delta=-0.021041)
[2025-05-07 16:54:47,136] INFO:  Iter 17/100 - Loss: 0.431 (delta=-0.021241)
[2025-05-07 16:54:47,740] INFO:  Iter 18/100 - Loss: 0.409 (delta=-0.021432)
[2025-05-07 16:54:48,404] INFO:  Iter 19/100 - Loss: 0.388 (delta=-0.021628)
[2025-05-07 16:54:49,020] INFO:  Iter 20/100 - Loss: 0.366 (delta=-0.021819)
[2025-05-07 16:54:49,670] INFO:  Iter 21/100 - Loss: 0.344 (delta=-0.022012)
[2025-05-07 16:54:50,204] INFO:  Iter 22/100 - Loss: 0.322 (delta=-0.022195)
[2025-05-07 16:54:50,757] INFO:  Iter 23/100 - Loss: 0.299 (delta=-0.022387)
[2025-05-07 16:54:51,316] INFO:  Iter 24/100 - Loss: 0.277 (delta=-0.022567)
[2025-05-07 16:54:51,987] INFO:  Iter 25/100 - Loss: 0.254 (delta=-0.022744)
[2025-05-07 16:54:52,503] INFO:  Iter 26/100 - Loss: 0.231 (delta=-0.022934)
[2025-05-07 16:54:53,137] INFO:  Iter 27/100 - Loss: 0.208 (delta=-0.023097)
[2025-05-07 16:54:53,701] INFO:  Iter 28/100 - Loss: 0.185 (delta=-0.023292)
[2025-05-07 16:54:54,220] INFO:  Iter 29/100 - Loss: 0.161 (delta=-0.023410)
[2025-05-07 16:54:54,786] INFO:  Iter 30/100 - Loss: 0.138 (delta=-0.023534)
[2025-05-07 16:54:55,386] INFO:  Iter 31/100 - Loss: 0.114 (delta=-0.023681)
[2025-05-07 16:54:55,953] INFO:  Iter 32/100 - Loss: 0.090 (delta=-0.023898)
[2025-05-07 16:54:56,664] INFO:  Iter 33/100 - Loss: 0.066 (delta=-0.024020)
[2025-05-07 16:54:57,203] INFO:  Iter 34/100 - Loss: 0.042 (delta=-0.024204)
[2025-05-07 16:54:57,932] INFO:  Iter 35/100 - Loss: 0.018 (delta=-0.024295)
[2025-05-07 16:54:58,442] INFO:  Iter 36/100 - Loss: -0.007 (delta=-0.024417)
[2025-05-07 16:54:59,237] INFO:  Iter 37/100 - Loss: -0.031 (delta=-0.024581)
[2025-05-07 16:55:00,070] INFO:  Iter 38/100 - Loss: -0.056 (delta=-0.024650)
[2025-05-07 16:55:00,587] INFO:  Iter 39/100 - Loss: -0.081 (delta=-0.024789)
[2025-05-07 16:55:01,153] INFO:  Iter 40/100 - Loss: -0.106 (delta=-0.024916)
[2025-05-07 16:55:01,654] INFO:  Iter 41/100 - Loss: -0.131 (delta=-0.025008)
[2025-05-07 16:55:02,304] INFO:  Iter 42/100 - Loss: -0.156 (delta=-0.025122)
[2025-05-07 16:55:03,113] INFO:  Iter 43/100 - Loss: -0.181 (delta=-0.025223)
[2025-05-07 16:55:03,656] INFO:  Iter 44/100 - Loss: -0.206 (delta=-0.025324)
[2025-05-07 16:55:04,187] INFO:  Iter 45/100 - Loss: -0.232 (delta=-0.025394)
[2025-05-07 16:55:04,770] INFO:  Iter 46/100 - Loss: -0.257 (delta=-0.025488)
[2025-05-07 16:55:05,404] INFO:  Iter 47/100 - Loss: -0.283 (delta=-0.025554)
[2025-05-07 16:55:06,237] INFO:  Iter 48/100 - Loss: -0.308 (delta=-0.025601)
[2025-05-07 16:55:06,987] INFO:  Iter 49/100 - Loss: -0.334 (delta=-0.025737)
[2025-05-07 16:55:07,554] INFO:  Iter 50/100 - Loss: -0.360 (delta=-0.025794)
[2025-05-07 16:55:08,136] INFO:  Iter 51/100 - Loss: -0.386 (delta=-0.025838)
[2025-05-07 16:55:08,704] INFO:  Iter 52/100 - Loss: -0.412 (delta=-0.025918)
[2025-05-07 16:55:09,382] INFO:  Iter 53/100 - Loss: -0.438 (delta=-0.025982)
[2025-05-07 16:55:09,999] INFO:  Iter 54/100 - Loss: -0.464 (delta=-0.026007)
[2025-05-07 16:55:10,587] INFO:  Iter 55/100 - Loss: -0.490 (delta=-0.026038)
[2025-05-07 16:55:11,178] INFO:  Iter 56/100 - Loss: -0.516 (delta=-0.026136)
[2025-05-07 16:55:12,087] INFO:  Iter 57/100 - Loss: -0.542 (delta=-0.026118)
[2025-05-07 16:55:12,790] INFO:  Iter 58/100 - Loss: -0.568 (delta=-0.026223)
[2025-05-07 16:55:13,370] INFO:  Iter 59/100 - Loss: -0.594 (delta=-0.026247)
[2025-05-07 16:55:13,937] INFO:  Iter 60/100 - Loss: -0.621 (delta=-0.026262)
[2025-05-07 16:55:14,654] INFO:  Iter 61/100 - Loss: -0.647 (delta=-0.026264)
[2025-05-07 16:55:15,234] INFO:  Iter 62/100 - Loss: -0.673 (delta=-0.026342)
[2025-05-07 16:55:15,804] INFO:  Iter 63/100 - Loss: -0.700 (delta=-0.026322)
[2025-05-07 16:55:16,387] INFO:  Iter 64/100 - Loss: -0.726 (delta=-0.026392)
[2025-05-07 16:55:16,969] INFO:  Iter 65/100 - Loss: -0.752 (delta=-0.026361)
[2025-05-07 16:55:17,470] INFO:  Iter 66/100 - Loss: -0.779 (delta=-0.026422)
[2025-05-07 16:55:18,220] INFO:  Iter 67/100 - Loss: -0.805 (delta=-0.026437)
[2025-05-07 16:55:19,053] INFO:  Iter 68/100 - Loss: -0.832 (delta=-0.026416)
[2025-05-07 16:55:19,553] INFO:  Iter 69/100 - Loss: -0.858 (delta=-0.026461)
[2025-05-07 16:55:20,087] INFO:  Iter 70/100 - Loss: -0.884 (delta=-0.026424)
[2025-05-07 16:55:20,654] INFO:  Iter 71/100 - Loss: -0.911 (delta=-0.026470)
[2025-05-07 16:55:21,254] INFO:  Iter 72/100 - Loss: -0.937 (delta=-0.026429)
[2025-05-07 16:55:22,053] INFO:  Iter 73/100 - Loss: -0.964 (delta=-0.026473)
[2025-05-07 16:55:22,623] INFO:  Iter 74/100 - Loss: -0.990 (delta=-0.026439)
[2025-05-07 16:55:23,347] INFO:  Iter 75/100 - Loss: -1.017 (delta=-0.026472)
[2025-05-07 16:55:23,854] INFO:  Iter 76/100 - Loss: -1.043 (delta=-0.026440)
[2025-05-07 16:55:24,524] INFO:  Iter 77/100 - Loss: -1.070 (delta=-0.026463)
[2025-05-07 16:55:25,139] INFO:  Iter 78/100 - Loss: -1.096 (delta=-0.026403)
[2025-05-07 16:55:25,604] INFO:  Iter 79/100 - Loss: -1.122 (delta=-0.026446)
[2025-05-07 16:55:26,270] INFO:  Iter 80/100 - Loss: -1.149 (delta=-0.026428)
[2025-05-07 16:55:26,823] INFO:  Iter 81/100 - Loss: -1.175 (delta=-0.026369)
[2025-05-07 16:55:27,419] INFO:  Iter 82/100 - Loss: -1.202 (delta=-0.026444)
[2025-05-07 16:55:27,919] INFO:  Iter 83/100 - Loss: -1.228 (delta=-0.026401)
[2025-05-07 16:55:28,420] INFO:  Iter 84/100 - Loss: -1.254 (delta=-0.026328)
[2025-05-07 16:55:29,153] INFO:  Iter 85/100 - Loss: -1.281 (delta=-0.026324)
[2025-05-07 16:55:29,637] INFO:  Iter 86/100 - Loss: -1.307 (delta=-0.026389)
[2025-05-07 16:55:30,337] INFO:  Iter 87/100 - Loss: -1.333 (delta=-0.026272)
[2025-05-07 16:55:31,148] INFO:  Iter 88/100 - Loss: -1.360 (delta=-0.026269)
[2025-05-07 16:55:31,666] INFO:  Iter 89/100 - Loss: -1.386 (delta=-0.026233)
[2025-05-07 16:55:32,237] INFO:  Iter 90/100 - Loss: -1.412 (delta=-0.026205)
[2025-05-07 16:55:32,821] INFO:  Iter 91/100 - Loss: -1.438 (delta=-0.026237)
[2025-05-07 16:55:33,447] INFO:  Iter 92/100 - Loss: -1.465 (delta=-0.026152)
[2025-05-07 16:55:33,981] INFO:  Iter 93/100 - Loss: -1.491 (delta=-0.026159)
[2025-05-07 16:55:34,620] INFO:  Iter 94/100 - Loss: -1.517 (delta=-0.026132)
[2025-05-07 16:55:35,371] INFO:  Iter 95/100 - Loss: -1.543 (delta=-0.026054)
[2025-05-07 16:55:36,190] INFO:  Iter 96/100 - Loss: -1.569 (delta=-0.025987)
[2025-05-07 16:55:36,695] INFO:  Iter 97/100 - Loss: -1.595 (delta=-0.025899)
[2025-05-07 16:55:37,301] INFO:  Iter 98/100 - Loss: -1.621 (delta=-0.025957)
[2025-05-07 16:55:37,990] INFO:  Iter 99/100 - Loss: -1.647 (delta=-0.025995)
[2025-05-07 16:55:38,688] INFO:  Iter 100/100 - Loss: -1.673 (delta=-0.025886)
[2025-05-07 16:55:39,437] INFO:  Iter 1/100 - Loss: 0.755 (delta=inf)
[2025-05-07 16:55:40,304] INFO:  Iter 2/100 - Loss: 0.736 (delta=-0.018478)
[2025-05-07 16:55:40,966] INFO:  Iter 3/100 - Loss: 0.718 (delta=-0.018621)
[2025-05-07 16:55:41,506] INFO:  Iter 4/100 - Loss: 0.699 (delta=-0.018783)
[2025-05-07 16:55:42,068] INFO:  Iter 5/100 - Loss: 0.680 (delta=-0.018965)
[2025-05-07 16:55:42,703] INFO:  Iter 6/100 - Loss: 0.661 (delta=-0.019157)
[2025-05-07 16:55:43,419] INFO:  Iter 7/100 - Loss: 0.642 (delta=-0.019363)
[2025-05-07 16:55:44,204] INFO:  Iter 8/100 - Loss: 0.622 (delta=-0.019554)
[2025-05-07 16:55:44,855] INFO:  Iter 9/100 - Loss: 0.602 (delta=-0.019775)
[2025-05-07 16:55:45,400] INFO:  Iter 10/100 - Loss: 0.582 (delta=-0.019947)
[2025-05-07 16:55:46,214] INFO:  Iter 11/100 - Loss: 0.562 (delta=-0.020148)
[2025-05-07 16:55:47,137] INFO:  Iter 12/100 - Loss: 0.542 (delta=-0.020363)
[2025-05-07 16:55:47,720] INFO:  Iter 13/100 - Loss: 0.521 (delta=-0.020530)
[2025-05-07 16:55:48,404] INFO:  Iter 14/100 - Loss: 0.500 (delta=-0.020745)
[2025-05-07 16:55:49,004] INFO:  Iter 15/100 - Loss: 0.480 (delta=-0.020935)
[2025-05-07 16:55:49,570] INFO:  Iter 16/100 - Loss: 0.458 (delta=-0.021140)
[2025-05-07 16:55:50,216] INFO:  Iter 17/100 - Loss: 0.437 (delta=-0.021329)
[2025-05-07 16:55:50,787] INFO:  Iter 18/100 - Loss: 0.416 (delta=-0.021539)
[2025-05-07 16:55:51,370] INFO:  Iter 19/100 - Loss: 0.394 (delta=-0.021728)
[2025-05-07 16:55:51,937] INFO:  Iter 20/100 - Loss: 0.372 (delta=-0.021940)
[2025-05-07 16:55:52,570] INFO:  Iter 21/100 - Loss: 0.350 (delta=-0.022146)
[2025-05-07 16:55:53,190] INFO:  Iter 22/100 - Loss: 0.327 (delta=-0.022293)
[2025-05-07 16:55:53,837] INFO:  Iter 23/100 - Loss: 0.305 (delta=-0.022547)
[2025-05-07 16:55:54,489] INFO:  Iter 24/100 - Loss: 0.282 (delta=-0.022705)
[2025-05-07 16:55:55,316] INFO:  Iter 25/100 - Loss: 0.259 (delta=-0.022847)
[2025-05-07 16:55:55,903] INFO:  Iter 26/100 - Loss: 0.236 (delta=-0.023048)
[2025-05-07 16:55:56,473] INFO:  Iter 27/100 - Loss: 0.213 (delta=-0.023205)
[2025-05-07 16:55:57,077] INFO:  Iter 28/100 - Loss: 0.190 (delta=-0.023352)
[2025-05-07 16:55:57,649] INFO:  Iter 29/100 - Loss: 0.166 (delta=-0.023489)
[2025-05-07 16:55:58,244] INFO:  Iter 30/100 - Loss: 0.143 (delta=-0.023493)
[2025-05-07 16:55:58,950] INFO:  Iter 31/100 - Loss: 0.119 (delta=-0.023880)
[2025-05-07 16:55:59,486] INFO:  Iter 32/100 - Loss: 0.095 (delta=-0.023954)
[2025-05-07 16:56:00,072] INFO:  Iter 33/100 - Loss: 0.071 (delta=-0.024213)
[2025-05-07 16:56:00,691] INFO:  Iter 34/100 - Loss: 0.047 (delta=-0.024186)
[2025-05-07 16:56:01,413] INFO:  Iter 35/100 - Loss: 0.022 (delta=-0.024365)
[2025-05-07 16:56:01,984] INFO:  Iter 36/100 - Loss: -0.002 (delta=-0.024517)
[2025-05-07 16:56:02,619] INFO:  Iter 37/100 - Loss: -0.027 (delta=-0.024655)
[2025-05-07 16:56:03,174] INFO:  Iter 38/100 - Loss: -0.052 (delta=-0.024664)
[2025-05-07 16:56:03,750] INFO:  Iter 39/100 - Loss: -0.077 (delta=-0.024930)
[2025-05-07 16:56:04,334] INFO:  Iter 40/100 - Loss: -0.102 (delta=-0.024933)
[2025-05-07 16:56:04,903] INFO:  Iter 41/100 - Loss: -0.127 (delta=-0.025034)
[2025-05-07 16:56:05,456] INFO:  Iter 42/100 - Loss: -0.152 (delta=-0.025168)
[2025-05-07 16:56:06,065] INFO:  Iter 43/100 - Loss: -0.177 (delta=-0.025330)
[2025-05-07 16:56:06,586] INFO:  Iter 44/100 - Loss: -0.202 (delta=-0.025335)
[2025-05-07 16:56:07,450] INFO:  Iter 45/100 - Loss: -0.228 (delta=-0.025458)
[2025-05-07 16:56:08,358] INFO:  Iter 46/100 - Loss: -0.253 (delta=-0.025504)
[2025-05-07 16:56:09,169] INFO:  Iter 47/100 - Loss: -0.279 (delta=-0.025559)
[2025-05-07 16:56:09,732] INFO:  Iter 48/100 - Loss: -0.305 (delta=-0.025751)
[2025-05-07 16:56:10,486] INFO:  Iter 49/100 - Loss: -0.330 (delta=-0.025795)
[2025-05-07 16:56:11,279] INFO:  Iter 50/100 - Loss: -0.356 (delta=-0.025809)
[2025-05-07 16:56:11,795] INFO:  Iter 51/100 - Loss: -0.382 (delta=-0.025803)
[2025-05-07 16:56:12,373] INFO:  Iter 52/100 - Loss: -0.408 (delta=-0.026045)
[2025-05-07 16:56:12,954] INFO:  Iter 53/100 - Loss: -0.434 (delta=-0.026031)
[2025-05-07 16:56:13,535] INFO:  Iter 54/100 - Loss: -0.460 (delta=-0.025890)
[2025-05-07 16:56:14,086] INFO:  Iter 55/100 - Loss: -0.486 (delta=-0.026287)
[2025-05-07 16:56:14,752] INFO:  Iter 56/100 - Loss: -0.512 (delta=-0.026091)
[2025-05-07 16:56:15,469] INFO:  Iter 57/100 - Loss: -0.539 (delta=-0.026168)
[2025-05-07 16:56:15,968] INFO:  Iter 58/100 - Loss: -0.565 (delta=-0.026201)

In [18]:
bdt

{1: <radp.digital_twin.rf.bayesian.bayesian_engine.BayesianDigitalTwin at 0x1d3aa3d5e10>,
 2: <radp.digital_twin.rf.bayesian.bayesian_engine.BayesianDigitalTwin at 0x1d3fe758190>,
 3: <radp.digital_twin.rf.bayesian.bayesian_engine.BayesianDigitalTwin at 0x1d3fe758d00>}

In [19]:
params2 = {
    "ue_tracks_generation": {
            "params": {
                "simulation_duration": 3600,
                "simulation_time_interval_seconds": 0.01,
                "num_ticks": 50,
                "num_batches": 1,
                "ue_class_distribution": {
                    "stationary": {
                        "count": 10,
                        "velocity": 0,
                        "velocity_variance": 1
                    },
                    "pedestrian": {
                        "count": 5,
                        "velocity": 2,
                        "velocity_variance": 1
                    },
                    "cyclist": {
                        "count": 7,
                        "velocity": 5,
                        "velocity_variance": 1
                    },
                    "car": {
                        "count": 10,
                        "velocity": 20,
                        "velocity_variance": 1
                    }
                },
                "lat_lon_boundaries": {
                    "min_lat": -90,
                    "max_lat": 90,
                    "min_lon": -180,
                    "max_lon": 180
                },
                "gauss_markov_params": {
                    "alpha": 0.8,
                    "variance": 0.5,
                    "rng_seed": 42,
                    "lon_x_dims": 100,
                    "lon_y_dims": 100,
                    "// TODO": "Account for supporting the user choosing the anchor_loc and cov_around_anchor.",
                    "// Current implementation": "the UE Tracks generator will not be using these values.",
                    "// anchor_loc": {},
                    "// cov_around_anchor": {}
            }
        }
    }
}

In [20]:
prediction_data = get_ue_data(params2)

In [21]:
prediction_data.head()

   mock_ue_id         lon        lat  tick
0           0   48.510339 -16.462645     0
1           1   19.286613  63.617111     0
2           2   21.315702 -47.889952     0
3           3  -70.559364 -79.511709     0
4           4 -168.916011 -39.338640     0

In [22]:
predictions, full_prediction_df = _predictions(
    pred_data=prediction_data,
    topology=topology,
    bayesian_digital_twins = bdt
)

Combined DataFrame:       mock_ue_id   longitude   latitude  tick  cell_lat  cell_lon  cell_id  \
0              0   48.510339 -16.462645     0     -90.0    -180.0        1
1              0   48.510339 -16.462645     0       0.0       0.0        2
2              0   48.510339 -16.462645     0      90.0     180.0        3
3              1   19.286613  63.617111     0     -90.0    -180.0        1
4              1   19.286613  63.617111     0       0.0       0.0        2
...          ...         ...        ...   ...       ...       ...      ...
4795          30  -64.060471  70.447505    49       0.0       0.0        2
4796          30  -64.060471  70.447505    49      90.0     180.0        3
4797          31 -152.742476  51.756565    49     -90.0    -180.0        1
4798          31 -152.742476  51.756565    49       0.0       0.0        2
4799          31 -152.742476  51.756565    49      90.0     180.0        3

      cell_az_deg  cell_carrier_freq_mhz
0               0                   2800
1             120                   2800
2             240                   2800
3               0                   2800
4             120                   2800
...           ...                    ...
4795          120                   2800
4796          240                   2800
4797            0                   2800
4798          120                   2800
4799          240                   2800

[4800 rows x 9 columns]

c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\gpytorch\distributions\multivariate_normal.py:319: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(

In [24]:
predictions.head()

        loc_x      loc_y  cell_id   sinr_db    rsrp_dbm
0   48.510339 -16.462645      2.0 -2.701067 -102.223811
1   19.286613  63.617111      3.0 -2.269515 -101.852432
2   21.315702 -47.889952      1.0 -2.645710 -102.127219
3  -70.559364 -79.511709      1.0 -1.630991 -101.313783
4 -168.916011 -39.338640      1.0 -2.507067 -102.250907

In [ ]:
full_prediction_df.head()

# cell_rxpwr_dbm --> calculated
# rxpower_dbm --> predicted

,mock_ue_id,loc_x,loc_y,tick,cell_lat,cell_lon,cell_id,cell_az_deg,cell_carrier_freq_mhz,log_distance,cell_rxpwr_dbm,relative_bearing,rxpower_dbm,rxpower_stddev_dbm,pred_means
0,0,48.510339,-16.462645,0,-90.0,-180.0,1,0,2800,15.917947,-102.430902,228.510339,-102.436820,0.032373,-102.436820
1,1,19.286613,63.617111,0,-90.0,-180.0,1,0,2800,16.654617,-102.823854,199.286613,-102.834308,0.032368,-102.834308
2,2,21.315702,-47.889952,0,-90.0,-180.0,1,0,2800,15.360440,-102.121234,201.315702,-102.127219,0.032362,-102.127219
3,3,-70.559364,-79.511709,0,-90.0,-180.0,1,0,2800,13.970414,-101.297346,109.440636,-101.313783,0.032955,-101.313783
4,4,-168.916011,-39.338640,0,-90.0,-180.0,1,0,2800,15.545318,-102.225153,11.083989,-102.250907,0.033513,-102.250907

In [27]:
# Training from scratch done now will update the exisitng BDT
update_not_from_scratch = train_or_update_rf_twin(update_data,topology,bdt)

Combined DataFrame:        longitude   latitude  cell_rxpwr_dbm  cell_lat  cell_lon  cell_id  \
0     -43.264737 -30.862211      -99.812392     -90.0    -180.0        1
1     -43.264737 -30.862211      -99.812392       0.0       0.0        2
2     -43.264737 -30.862211      -99.812392      90.0     180.0        3
3      54.978193 -55.259842      -99.512981     -90.0    -180.0        1
4      54.978193 -55.259842      -99.512981       0.0       0.0        2
...          ...        ...             ...       ...       ...      ...
17995  89.254786 -82.596233     -100.385621       0.0       0.0        2
17996  89.254786 -82.596233     -100.385621      90.0     180.0        3
17997  20.088340 -55.786882     -100.297751     -90.0    -180.0        1
17998  20.088340 -55.786882     -100.297751       0.0       0.0        2
17999  20.088340 -55.786882     -100.297751      90.0     180.0        3

       cell_az_deg  cell_carrier_freq_mhz
0                0                   2800
1              120                   2800
2              240                   2800
3                0                   2800
4              120                   2800
...            ...                    ...
17995          120                   2800
17996          240                   2800
17997            0                   2800
17998          120                   2800
17999          240                   2800

[18000 rows x 8 columns]
Updated_List  [       longitude   latitude  cell_rxpwr_dbm  cell_lat  cell_lon  cell_id  \
0       0.637310  10.230353      -99.976404     -90.0    -180.0        1
1     126.033860 -43.276470     -100.174406     -90.0    -180.0        1
2     157.387307  32.211302      -99.799616     -90.0    -180.0        1
3       0.133809  31.074341     -100.200028     -90.0    -180.0        1
4     -80.239680 -40.015335      -99.718861     -90.0    -180.0        1
...          ...        ...             ...       ...       ...      ...
5995  -86.317956 -69.265685     -100.343891     -90.0    -180.0        1
5996   81.235513  24.337051      -99.991492     -90.0    -180.0        1
5997   39.675933  68.457496     -100.341243     -90.0    -180.0        1
5998  -32.876896 -17.143153      -99.543231     -90.0    -180.0        1
5999  -23.739368  -1.522312      -99.293293     -90.0    -180.0        1

      cell_az_deg  cell_carrier_freq_mhz  log_distance  relative_bearing
0               0                   2800     16.227625        180.637310
1               0                   2800     15.464402        306.033860
2               0                   2800     16.425905        337.387307
3               0                   2800     16.416559        180.133809
4               0                   2800     15.531870         99.760320
...           ...                    ...           ...               ...
5995            0                   2800     14.651944         93.682044
5996            0                   2800     16.359305        261.235513
5997            0                   2800     16.685640        219.675933
5998            0                   2800     15.908650        147.123104
5999            0                   2800     16.102904        156.260632

[6000 rows x 10 columns],        longitude   latitude  cell_rxpwr_dbm  cell_lat  cell_lon  cell_id  \
0       0.637310  10.230353      -99.976404       0.0       0.0        2
1     126.033860 -43.276470     -100.174406       0.0       0.0        2
2     157.387307  32.211302      -99.799616       0.0       0.0        2
3       0.133809  31.074341     -100.200028       0.0       0.0        2
4     -80.239680 -40.015335      -99.718861       0.0       0.0        2
...          ...        ...             ...       ...       ...      ...
5995  -86.317956 -69.265685     -100.343891       0.0       0.0        2
5996   81.235513  24.337051      -99.991492       0.0       0.0        2
5997   39.675933  68.457496     -100.341243       0.0       0.0        2
5998  -32.876896 -17.143153      -99.543231       0.0       0.0        2
5999  -23.739368  -1.522312      -99.293293       0.0       0.0        2

      cell_az_deg  cell_carrier_freq_mhz  log_distance  relative_bearing
0             120                   2800     13.947430        243.526750
1             120                   2800     16.368202         19.342513
2             120                   2800     16.571438        271.396066
3             120                   2800     15.056545        240.222041
4             120                   2800     16.033436        109.572773
...           ...                    ...           ...               ...
5995          120                   2800     16.105382         80.695145
5996          120                   2800     16.027113        305.409277
5997          120                   2800     15.918577        254.146052
5998          120                   2800     15.220967        120.392729
5999          120                   2800     14.789222        146.223170

[6000 rows x 10 columns],        longitude   latitude  cell_rxpwr_dbm  cell_lat  cell_lon  cell_id  \
0       0.637310  10.230353      -99.976404      90.0     180.0        3
1     126.033860 -43.276470     -100.174406      90.0     180.0        3
2     157.387307  32.211302      -99.799616      90.0     180.0        3
3       0.133809  31.074341     -100.200028      90.0     180.0        3
4     -80.239680 -40.015335      -99.718861      90.0     180.0        3
...          ...        ...             ...       ...       ...      ...
5995  -86.317956 -69.265685     -100.343891      90.0     180.0        3
5996   81.235513  24.337051      -99.991492      90.0     180.0        3
5997   39.675933  68.457496     -100.341243      90.0     180.0        3
5998  -32.876896 -17.143153      -99.543231      90.0     180.0        3
5999  -23.739368  -1.522312      -99.293293      90.0     180.0        3

      cell_az_deg  cell_carrier_freq_mhz  log_distance  relative_bearing
0             240                   2800     15.999297        119.362690
1             240                   2800     16.512580        353.966140
2             240                   2800     15.676947        322.612693
3             240                   2800     15.696431        119.866191
4             240                   2800     16.487806        200.239680
...           ...                    ...           ...               ...
5995          240                   2800     16.690728        206.317956
5996          240                   2800     15.804689         38.764487
5997          240                   2800     14.690182         80.324067
5998          240                   2800     16.294320        152.876896
5999          240                   2800     16.136737        143.739368

[6000 rows x 10 columns]]

c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-06 to the diagonal
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-05 to the diagonal
  warnings.warn(
c:\Users\rafid\OneDrive\Desktop\VSCode\maveric\.venv\lib\site-packages\linear_operator\utils\cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-04 to the diagonal
  warnings.warn(

An unexpected error occurred: Matrix not positive definite after repeatedly adding jitter up to 1.0e-04.